### ISSUE TITLE
AMD VCE and NVIDIA NVENC support

### ISSUE THREAD

**Issue by mrdeathjr28** [MaartenBaert/ssr#124]
Hi and first thanks for your works

Its possible add AMD VCE and Nvidia NVENC support, on nvenc lastest afterburner show interesting news for developers courtesy guru3d

http://forum.guru3d.com/showthread.php?t=385204&page=11

This is lastest announces on msi afterburner for amd vce and nvidia nvenc

(Good news, RTSS 6.1.0 beta is expected soon. Full changes list includes the following:

• Improved encoding plugins architecture:
o Encoder benchmark results are no longer affected by encoder initialization time
o Now the plugins are allowed to start encoding frames without specifying the header prior to encoding. MKV container implementation has been also improved to provide support for delayed header encoding
• Improved dedicated encoder server service:
o Seriously optimized data exchange path between video capture engine and dedicated encoder. Data exchange related performance overhead is seriously reduced and close to invisible now
• Improved Intel QuickSync H.264 encoder plugin:
o Added wait loop to encoding routine to prevent frame dropping when VPP input queue is full. Such frame dropping caused by queue overflow could cause the benchmark to be stopped with MFX_ERR_MEMORY_ALLOC error
o Increased upper adjustable bitrate limit to 50 Mbps
o Output bitstream is now dynamically resizable to allow encoding video at 40 Mbps and higher bitrates
• Added AMD VCE H.264 encoder plugin:
o New plugin uses AMD Accelerated Parallel Processing SDK and AMD OpenVideo API to access fixed function H.264 encoder unit built into AMD RADEON HD 7xxx and newer AMD GPU families. The plugin is able to encode H.264 video in up to 1080p resolution at up to 60 FPS framerate
o The pluging GUI provides you adjustable encoding bitrate and AMD’s recommended speed, balanced and quality presets. However, each preset is represented by independent CFG file and can be additionally tweaked by experienced users if necessary
• Various protections and improvements for low memory conditions:
o Added exception handling for memory allocation routines
o Now encoder input queue size is limited to 256MB in 32-bit applications
o Improved encoder input queue memory management and reduced memory footprint for VFW and external plugin compression modes
• Framerate calculation fix for Outcast, introduced in the previous version, is no longer hardcoded. Now it is being applied at application profile level to selected executables only to avoid breaking support for other applications handling multiple swap chains differently (e.g. Dragon Age : Origins)
• Added raster 3D On-Screen Display rendering mode support for Rayman Legends and ARMA II rendering engines
• Updated profiles list

And special note for those who hate searching: there will be NO Mantle support until AMD release Mantle specs and SDK)

(Holy ****! With all this AMD related coding during the last weeks I totally missed very important note in the release notes for 334.67 drivers:
- Now supports NVENC SDK allowing developers to use Kepler-based GeForce GPUs for video encoding.

NVIDIA finally dedided to open free access to NVENC SDK on GeForce GPUs. Previously it only worked on Quadro/Tesla series cards only and required NVIDIA license key to be used on GeForce series GPU. Now it works on GeForce as well so any software developer can use NVENC SDK on GeForce cards without that licensing nonsens.

Edit: I think it is worth delaying 6.1.0 release a bit to create and add NVENC plugin to this build as well. I expect to get it working within a week or so. )

**Comment by Hiradur** [comment]
@MaartenBaert 
> I do know that Intel QuickSync is nowhere close to x264 in terms of quality and bit rate.

With 4th generation (Haswell) and newer Intel processors the quality of Quicksync is much better (https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video ) and definitely worth to consider for real time recording of CPU intensive applications.
There is some information on how to get hardware acceleration with ffmpeg here: https://trac.ffmpeg.org/wiki/HWAccelIntro

It would be nice to have support for HW acceleration in SSR.

**Comment by MaartenBaert** [comment]
NVENC already works if you compile FFmpeg with support for it. FFmpeg seems to have Quick Sync support as well (h264_qsv), and it supports NV12 which SSR can generate, so in theory it should just work. I haven't tested it though.

**Comment by mrdeathjr28** [comment]
Maybe can be good idea thinking towards future if SSR could have FFMPEG embebbed version (own ffmpeg version) for prevent this issues

**Comment by Hiradur** [comment]
> NVENC already works if you compile FFmpeg with support for it. FFmpeg seems to have Quick Sync support as well (h264_qsv), and it supports NV12 which SSR can generate, so in theory it should just work. I haven't tested it though.

Good to know, I was already wondering if that was the case. I may try Quicksync in the future.

**Comment by MaartenBaert** [comment]
@mrdeathjr28 Sadly licensing issues make that impossible. Distributing FFmpeg with NVENC support in binary form, even with source code available, is not allowed because of a conflict between the GPL and NVIDIA's license. The only way to get it is to compile it yourself.

In case you were wondering, yes, OBS does this anyway and this is a violation of the GPL. I won't do the same.
