### ISSUE TITLE
Recording only the desktop

### ISSUE THREAD

**Issue by koolkanga** [MaartenBaert/ssr#182]
Using Elementary stable with SSR for several weeks, with no problems with recording or sound. It now refuses to record anything other than the desktop and seems to be just stuck on recording a JPG image of the desktop.

**Comment by pduzinski** [comment]
Have same issue using Ubuntu 14.05 LTS in virtualbox, which doesn't have package xorg-driver-fglrx.
Is there another package to reinstall similar to that suggested by koolkanga or another method to try?
Thanks!

**Comment by MaartenBaert** [comment]
Disable hardware acceleration in VirtualBox. Or just record from the host operating system instead of the guest. This is usually more efficient too.
