### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ceremcem** [MaartenBaert/ssr#201]
I'm trying to compile ssr on Debian Jessie. 

```
In file included from /usr/include/c++/4.8/cassert:43:0,
                 from ./Global.h:25,
                 from AV/Output/AudioEncoder.cpp:20:
AV/Output/AudioEncoder.cpp: In member function ‘virtual bool AudioEncoder::EncodeFrame(AVFrame*)’:
AV/Output/AudioEncoder.cpp:141:17: error: ‘AVFrame’ has no member named ‘channels’
   assert(frame->channels == GetStream()->codec->channels);
                 ^
Makefile:1113: recipe for target 'AV/Output/simplescreenrecorder-AudioEncoder.o' failed
make[2]: *** [AV/Output/simplescreenrecorder-AudioEncoder.o] Error 1
make[2]: Leaving directory '/home/ceremcem/test/ssr/src'
Makefile:417: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ceremcem/test/ssr'
Makefile:348: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by magnadian** [comment]
Hi guys,
  I think I've found an alternative solution for this issue. I had the same problem but I updated my repositories from debian jessie to debian SID, then I made:
# apt-get update
# apt-get install libavcodec-dev
this also installed  all the dependencies needed for libavcodec-dev
Once installed, I returned the repositories back to jessie, and then I could compile with no errors:
./configure
make && sudo make install
Now I have SSR up and running ok.
Hope this also works for you!!
