### ISSUE TITLE
OpenGL Recording Playonlinux

### ISSUE THREAD

**Issue by ghost** [MaartenBaert/ssr#211]
Hi Maarten! Is there a way to set up opengl recording to games running through POL? I've read the instructions on your website but they are for straight wine.

Thank you.

**Comment by inukaze** [comment]
Hi there someone can tellme if posible record using OpenGL from the game "Ragnarok Online" from Steam Client, using PlayOnLinux ???

I wanna run directly the game, and record the OpenGL output :D 

Some method ?

Thank you for any help can give me
