### ISSUE TITLE
Improved tray icon

### ISSUE THREAD

**Issue by orschiro** [MaartenBaert/ssr#226]
Hi @MaartenBaert 

Thanks a lot for developing this great, feature-rich, yet simple recording tool!

I noticed that the currently used tray icon could have some polishing. 

On my system at least, it looks very blurry:

![](http://i.imgur.com/HBjZSid.jpg)

Is this a generic issue or specific on my system?

Installed version:

```
simplescreenrecorder 0.3.0-1
Arch Linux 64Bit
```

Thanks for your advice!

**Comment by inukaze** [comment]
Hi there i am under Debian 8 Jessie Stable , my SSR was compiled manually , the unique thing i dont have "Tray icon" . how i fix it ?

From where SSR reads the icon , and its using SVG icons ?

**Comment by MaartenBaert** [comment]
@inukaze Please open a new issue, this is not the same problem at all.

Missing tray icons are almost always a configuration problem of your desktop environment. Make sure that your panel has a 'notification area' as well as an 'indicator applet' if your distribution/DE supports those. If you still can't get it fixed that way, and all other Qt applications (e.g. VLC) do have a system tray icon, then I will look into it.
