### ISSUE TITLE
Debian

### ISSUE THREAD

**Issue by IotaSpencer** [MaartenBaert/ssr#256]
Can you add a debian .deb/repo so that debian users don't have to compile (I mean come on, ubuntu is based on debian :P)

**Comment by aquila62** [comment]
I agree with IotaSpencer, would be nice to use aptitude to install simplescreenrecorder under the stable release of Debian.  Ubuntu and other distributions should derive their packages from Debian, not the other way around. :)

**Comment by trebmuh** [comment]
@aquila62 : please look at https://github.com/MaartenBaert/ssr/issues/481 .

**Comment by Sunderland93** [comment]
I provide Debian-packages for SSR in my Debian 8 repo https://build.opensuse.org/project/show/home:Sunderland93

**Comment by trebmuh** [comment]
SSR entered the debian repo for stretch. Please see: https://tracker.debian.org/pkg/simplescreenrecorder
@MaartenBaert : I suggest this thread to be closed now.
