### ISSUE TITLE
eBuild bug.

### ISSUE THREAD

**Issue by JinxTheFox** [MaartenBaert/ssr#264]
The new update gets me this.

emerge: there are no ebuilds to satisfy "x11-libs/libX11[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?]".
(dependency required by "media-video/simplescreenrecorder-0.3.1-r1::anders-larsson" [ebuild])

If you could look into this that would be wonderful.

EDIT: This is with 0.3.1-r1, 0.3.1 seems to work OK.

**Comment by hartwork** [comment]
Can this ticket be closed?

**Comment by anders-larsson** [comment]
Gentoo is fully multilib now both in stable and unstable. This issue should be closed imho.
