### ISSUE TITLE
Possible NVENC Support

### ISSUE THREAD

**Issue by mrdeathjr28** [MaartenBaert/ssr#266]
Hi i post if possible add NVENC support to simplescreen recorder, in nvidia 346.16 drivers open nvenc and this project put ffmpeg with nvenc support

https://github.com/Brainiarc7/ffmpeg_libnvenc

And this link have information about compiling

https://github.com/Brainiarc7/ffmpeg_libnvenc/commit/51aff481dd536fed36365d6b11618c59b0c24d36

I leave this example using this ffmpeg with nvenc support

https://www.youtube.com/watch?v=P-kzKUF4BRs

Thanks

**Comment by SoftwareSchlosser** [comment]
I tried running ssr using LD_LIBRARY_PATH but it still loads the older systems libraries:

The command:
LD_LIBRARY_PATH=/usr/local/lib simplescreenrecorder

Any suggestions?

**Comment by Shished** [comment]
вт, 18 авг. 2015, 13:27, SoftwareSchlosser <notifications@github.com>:

> I tried running ssr using LD_LIBRARY_PATH but it still loads the older
> systems libraries:
>
> The command:
> LD_LIBRARY_PATH=/usr/local/lib simplescreenrecorder
>
> Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MaartenBaert/ssr/issues/266#issuecomment-132158800>.
>
You need to build ffmpeg from that git repo the you need to use includes
from compiled libavcodec to compile the SSR.

**Comment by SoftwareSchlosser** [comment]
ffmpeg was already compiled with nvenc support (not from git but that shouldn't make a difference)

ssr now seems to use the right libav... libs but it still doesn't show nvenc as option.

This is what I tried:
 ./simple-build-and-install --without-jack --with-ffmpeg=/usr/local/src/ffmpeg/ffmpeg-2.6.3

Also tried adding this:
--with-libavcodec=/usr/local/src/ffmpeg/ffmpeg-2.6.3/libavcodec

**Comment by SoftwareSchlosser** [comment]
I investigated the source code and added some debug output.
Turns out that ssr in fact loads the right libs but in the function VideoEncoder::AVCodecIsSupported the check for AVCodecSupportsPixelFormat fails for all formats provided by nvenc.

**Comment by MaartenBaert** [comment]
Added! I didn't do much testing but it appears to work just fine. Now the only obstacle is getting people to compile their own ffmpeg ...

I've also added real NV12 support to FastScaler, so it doesn't have to rely on swscale anymore. NV12 is actually a pretty nice format, the memory layout is more efficient than standard YUV420:
```
[BenchmarkConvert] BGRA 1920x1080 to YUV420 1920x1080  |  SWScale   5484 us  |  Fallback   3668 us ( 66%)  |  SSSE3   1303 us ( 35%)
[BenchmarkConvert] BGRA 1920x1080 to NV12   1920x1080  |  SWScale   7716 us  |  Fallback   2865 us ( 37%)  |  SSSE3   1226 us ( 42%)
```
SWScale apparently doesn't have decent code for NV12, so the dedicated converter is really helping a lot. SSR CPU usage is now lower than ever. Have fun!

**Comment by mrdeathjr28** [comment]
Many thanks to https://github.com/SoftwareSchlosser and https://github.com/MaartenBaert for add this feature more later make some tests

**Comment by mikhailnov** [comment]
Hello, starting from ffmpeg 3.2 nvenc is complied out-of-the-box and is supported upstream, no ffmpeg rebuilding is needed. I do not see nvenc in codec list. While it does work in ffmpeg.

**Comment by MaartenBaert** [comment]
Just tested this with the default ffmpeg package from Arch Linux, for me NVENC is showing up in the list and it works just fine. Are you using the latest SSR?

**Comment by ChipmunkV** [comment]
Not showing up.

Ubuntu 17.04
simplescreenrecorder 0.3.8
ffmpeg 3.2.4

FFmpeg has it, ssr 0.3.8 was after the patch. So there is some new problem.
