### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by eson57** [MaartenBaert/ssr#276]
Hi,
I'm ready to start translate, if you want it?

eson

**Comment by eson57** [comment]
Ok, translation finished. Please download from my domain.
http://svenskasprakfiler.se/tempfiles/simplescreenrecorder_sv.ts

**Comment by MaartenBaert** [comment]
Added. Thanks :).

**Comment by eson57** [comment]
I've made a few minor adjustments because of users request. No big deal, just to correct translation for the next release.
Please find updated file at link below.
http://svenskasprakfiler.se/tempfiles/simplescreenrecorder_sv.ts

**Comment by MaartenBaert** [comment]
Thanks, done.
