### ISSUE TITLE
disable SSSE3

### ISSUE THREAD

**Issue by wolfwood** [MaartenBaert/ssr#296]
hi, I'm on an AMD Phenom II without SSSE3 support. It would be nice to be able to get the SSE2 stuffs without disabling ASM completely, however I'm having an issue currently even with the --disable-x86_asm route.

/var/tmp/portage/media-video/simplescreenrecorder-0.3.2-r1/work/ssr-0.3.2/src/Benchmark.cpp: In function 'void BenchmarkScale(unsigned int, unsigned in
t, unsigned int, unsigned int)':
/var/tmp/portage/media-video/simplescreenrecorder-0.3.2-r1/work/ssr-0.3.2/src/Benchmark.cpp:94:20: error: 'CPUFeatures' has not been declared
  bool use_ssse3 = (CPUFeatures::HasMMX() && CPUFeatures::HasSSE() && CPUFeatures::HasSSE2() && CPUFeatures::HasSSE3() && CPUFeatures::HasSSSE3());

I'm using @anders-larsson gentoo-overlay to build version 0.3.2-r1, with a patch to pass --disable-x86_asm.  I get the same error building in a fresh check out of this repo, but using the the config flags chosen by the overlay.

**Comment by wolfwood** [comment]
sorry, I got ahead of myself.

I was attempting to disable asm because of issues linking with the SSSE3 gcc builtins, but that was a failure due to LTO, sorry.  the unmanagled project builds without LTO just fine.

However, it does seem that perhaps --disable-x86_asm no longer functions properly.

**Comment by MaartenBaert** [comment]
I see. I've fixed it now.

**Comment by anders-larsson** [comment]
@wolfwood Feel free to create a pull request to my gentoo-overlay to if you want your changes merged into the ebuild itself or tell me what needs to be done.

**Comment by wolfwood** [comment]
I do not believe any changes to the overlay are necessary.  SSR does an admirable job of CPU feature detection so there is no need to disable features at compile time. Thank you both.
