### ISSUE TITLE
Garry's Mod not recording in OpenGL record mode

### ISSUE THREAD

**Issue by williambl** [MaartenBaert/ssr#297]
So, I've been trying to record videos on Garry's Mod, which runs through Steam. I did everything in the instructions for recording steam games and then tried to record, and got this in the ssr log: [PageRecord::StartOutput] Starting output ...
[PageRecord::StartOutput] Error: Could not get the size of the OpenGL application because the GLInject input has not been created.
[PageRecord::StartOutput] Error: Something went wrong during initialization.

What could be the problem and is there a way to fix it?

**Comment by williambl** [comment]
Also, I'm using ubuntu 14.04.

**Comment by williambl** [comment]
Also, I'm using ubuntu 14.04.

**Comment by williambl** [comment]
Also, I'm using ubuntu 14.04.

**Comment by williambl** [comment]
Also, I'm using ubuntu 14.04.

**Comment by williambl** [comment]
Also, I'm using ubuntu 14.04.

**Comment by williambl** [comment]
Sorry the commenting system glitched and now I can't delete those /\

**Comment by Lucki** [comment]
Start Steam in a terminal to see the output of ssr-glinject. Maybe that's helpful.

**Comment by williambl** [comment]
Weird. I cant find any mention of it...

**Comment by williambl** [comment]
Wait- I have found it.. It said:
ssr-glinject: LD_PRELOAD = :/home/william/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/william/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so:libssr-glinject.so
ssr-glinject: command = /home/william/.local/share/Steam/steamapps/common/GarrysMod/hl2.sh -steam -game garrysmod
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[SSR-GLInject] Library loaded (64-bit).
pid 6599 != 6598, skipping destruction (fork without exec?)
[SSR-GLInject] Library unloaded.
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
[SSR-GLInject] Library loaded (64-bit).
ERROR: ld.so: object '/home/william/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
[SSR-GLInject] Library loaded (32-bit).

**Comment by MaartenBaert** [comment]
Have you installed the 32-bit glinject library (i.e. did you run ```sudo apt-get install simplescreenrecorder-lib:i386```)?

This may be related to a problem I just fixed. If you still encounter the problem, please wait for version 0.3.3 and try again.

**Comment by williambl** [comment]
Yes I did install 32-bit libs.

**Comment by williambl** [comment]
@MaartenBaert Turns out recording via OpenGL doesn't work AT ALL. Even if I set the launch automatically thing with a non-steam game (Minecraft), it still gives me the same error.

**Comment by MaartenBaert** [comment]
Are you using SSR 0.3.3 now?

Try starting a simple OpenGL program from the terminal:
```
ssr-glinject glxgears
```
Try to record it. If it doesn't work, please post the full output that you see in the terminal (not the SSR error message, I need the messages from ssr-glinject).

**Comment by williambl** [comment]
No I have not updated yet. I'll update and try again soon.

**Comment by williambl** [comment]
@MaartenBaert After updating, the problem still persists. I cannot record anything in OpenGL mode...

**Comment by williambl** [comment]
the glx-gears won't record either. I get this:
ssr-glinject: LD_PRELOAD = :libssr-glinject.so
ssr-glinject: command = glxgears
[SSR-GLInject] Library loaded (64-bit).
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
[SSR-GLInject] Warning: glXSwapBuffers called without existing frame grabber, creating one assuming window == drawable.
[SSR-GLInject] [GLXFrameGrabber 1] Created GLX frame grabber.
[SSR-GLInject] [/dev/shm/ssr-channel-william/video-1046579815-9257-glx0001-glxgears] Created video stream.
[SSR-GLInject] OpenGL version = 3.0 (3.0 Mesa 10.1.3).
[SSR-GLInject] [/dev/shm/ssr-channel-william/video-1046579815-9257-glx0001-glxgears] frame size = 300x300.

**Comment by ubuntuaddicted** [comment]
According to the log, it's recording a 300x300 window of glxgears. Is the file 0 bytes in size or what do you means its not recording?

**Comment by ubuntuaddicted** [comment]
Sorry, I'm on mobile and I forgot to ask if you tried to enable the preview? Does preview show glxgears. Do you have write permissions to /dev/?

**Comment by williambl** [comment]
Preview does not work either...

**Comment by williambl** [comment]
By 'does not record' I mean nothing happens when I click Start Recording. I
just shows me an error: [PageRecord::StartOutput] Error: Could not get the
size of the OpenGL application because the GLInject input has not been
created.

Preview does the same thing. I do not have access to /dev/ I will try it
with sudo.

**Comment by williambl** [comment]
Nope, even if I type sudo ssr-glinject glxgears SSR still doesn't detect it.

**Comment by MaartenBaert** [comment]
Did you modify the 'channel' field in 'OpenGL settings'?

**Comment by williambl** [comment]
no.

**Comment by MaartenBaert** [comment]
Can you please send me the full SSR log (which is saved at ~/.ssr/logs, it includes more info than the graphical interface will show you)? I also need your settings file (~/.ssr/settings.conf).

**Comment by williambl** [comment]
ssr log: ==================== SSR started ====================
SimpleScreenRecorder 0.3.3
Compiled with GCC 4.8.2
Qt: header 4.8.6, lib 4.8.6
libavformat: header 54.20.4, lib 54.20.4
libavcodec: header 54.35.0, lib 54.35.0
libavutil: header 52.3.0, lib 52.3.0
libswscale: header 2.1.1, lib 2.1.1
[CPUFeatures::Detect] CPU features: mmx sse sse2 sse3 ssse3 sse4_1 sse4_2 avx bmi1
[ALSAInput::GetSourceList] Generating source list ...
[ALSAInput::GetSourceList] Found card: [hw:0] HDA ATI SB
[ALSAInput::GetSourceList] Found device: [hw:0,0] HDA ATI SB: ALC887-VD Analog
[ALSAInput::GetSourceList] Found device: [hw:0,2] HDA ATI SB: ALC887-VD Alt Analog
[ALSAInput::GetSourceList] Found card: [hw:1] HD-Audio Generic
[ALSAInput::GetSourceList] Found card: [hw:2] C-Media USB Audio Device
[ALSAInput::GetSourceList] Found device: [hw:2,0] C-Media USB Audio Device: USB Audio
[PulseAudioInput::GetSourceList] Generating source list ...
[SourceNamesCallback] Found source: [alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor] Monitor of HD-Audio Generic Digital Stereo (HDMI)
[SourceNamesCallback] Found source: [alsa_output.pci-0000_00_14.2.analog-stereo.monitor] Monitor of Built-in Audio Analogue Stereo
[SourceNamesCallback] Found source: [alsa_input.pci-0000_00_14.2.analog-stereo] Built-in Audio Analogue Stereo
[SourceNamesCallback] Found source: [alsa_output.usb-0d8c_C-Media_USB_Audio_Device-00-Device.analog-stereo.monitor] Monitor of C-Media USB Audio Device    Analogue Stereo
[SourceNamesCallback] Found source: [alsa_input.usb-0d8c_C-Media_USB_Audio_Device-00-Device.analog-mono] C-Media USB Audio Device    Analogue Mono
[PageRecord::StartPage] Starting page ...
[SSRVideoStreamWatcher::Init] Added pre-existing stream video-17064076290-5014-glx0004-java.
[GLInjectInput::InputThread] Input thread started.
[SSRVideoStreamReader::Init] Created video stream reader.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
[1;31m[JACKInput::Init] Error: Could not connect to JACK![0m
[1;31m[PageRecord::StartPage] Error: Something went wrong during initialization.[0m
[GLInjectInput::~GLInjectInput] Stopping input thread ...
[GLInjectInput::InputThread] Input thread stopped.
[SSRVideoStreamReader::Init] Destroyed video stream reader.
[PageRecord::StartPage] Started page.
[PageRecord::StartOutput] Starting output ...
[1;31m[PageRecord::StartOutput] Error: Could not get the size of the OpenGL application because the GLInject input has not been created.[0m
[1;31m[PageRecord::StartOutput] Error: Something went wrong during initialization.[0m
[PageRecord::StopPage] Stopping page ...
[PageRecord::StopPage] Stopped page.
==================== SSR stopped ====================

ssr settings:
[global]
nvidia_disable_flipping=ask

[input]
profile=Gmod
video_area=glinject
video_area_screen=0
video_x=0
video_y=0
video_w=1920
video_h=1080
video_frame_rate=30
video_scale=false
video_scaled_w=854
video_scaled_h=480
video_record_cursor=true
audio_enabled=true
audio_backend=jack
audio_alsa_source=default
audio_pulseaudio_source=alsa_output.pci-0000_00_14.2.analog-stereo.monitor
audio_jack_connect_system_capture=true
audio_jack_connect_system_playback=true
glinject_channel=
glinject_relax_permissions=false
glinject_command=
glinject_working_directory=
glinject_auto_launch=false
glinject_limit_fps=false

[output]
profile=Gmod
file=/home/william/crackedgamersvids/unedited/gmod/gmod_test.mkv
separate_files=false
container=mkv
container_av=3g2
video_codec=h264
video_codec_av=asv1
video_kbit_rate=5000
video_h264_crf=23
video_h264_preset=4
video_vp8_cpu_used=5
video_options=
video_allow_frame_skipping=true
audio_codec=vorbis
audio_codec_av=aac
audio_kbit_rate=128
audio_options=

[record]
hotkey_enable=true
hotkey_ctrl=true
hotkey_shift=false
hotkey_alt=true
hotkey_super=true
hotkey_key=17
sound_notifications_enable=false
preview_frame_rate=10

**Comment by williambl** [comment]
Thanks for your help so far.

**Comment by MaartenBaert** [comment]
The log clearly tells you what the issue is: you have chosen JACK but there is no JACK server running. I don't think this has anything to do with Garry's Mod, unless it is somehow killing the JACK server.
