### ISSUE TITLE
[Feature Request]  Scheduler/Timer

### ISSUE THREAD

**Issue by dkebler** [MaartenBaert/ssr#301]
Allow the recording to be launched based on TOD or Delay plus duration instead of only by the current manual record button.   

examples:  Recording to start at 18:30 and record for 2 hours
                   Start recording after 5 minute delay and record for 10 minutes

**Comment by StripedMonkey** [comment]
Sorry if I sound rude or that I don't like this idea but,
Why? I get the Start recording after a 5 second delay (Although I think
that you should just use the bindings) but why would you immediately want
to stop the recording after 10 minutes exactly?

**Comment by dkebler** [comment]
The request is so that one can record live streams for which one may not be
present to start and stop.
The delay/duration request isn't really needed but if one implemented a TOD
start/end adding the alternate delay or duration option would be easy and
maybe more useful to some.  Several screen recorders have this feature.
http://www.softdivshareware.com/recordzilla-screen-recorder-schedule.html

On Tue, Jan 27, 2015 at 11:06 AM, Noah <notifications@github.com> wrote:

> Sorry if I sound rude or that I don't like this idea but,
> Why? I get the Start recording after a 5 second delay (Although I think
> that you should just use the bindings) but why would you immediately want
> to stop the recording after 10 minutes exactly?
>
> On Tue, Jan 27, 2015 at 1:56 PM, dkebler <notifications@github.com>
> wrote:
>
> > Allow the recording to be launched based on TOD or Delay plus duration
> > instead of only by the current manual record button.
> >
> > examples: Recording to start at 18:30 and record for 2 hours
> > Start recording after 5 minute delay and record for 10 minutes
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/MaartenBaert/ssr/issues/301>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MaartenBaert/ssr/issues/301#issuecomment-71707255>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by MaartenBaert** [comment]
This is already partially implemented in the record-schedule branch. But that branch contains many other incomplete features and is not usable right now.

**Comment by josephgbr** [comment]
@MaartenBaert Do you have any suggestion of workaround while this feature is not fully implemented?
