### ISSUE TITLE
Qt5/No Keyboard Input

### ISSUE THREAD

**Issue by ikeydoherty** [MaartenBaert/ssr#308]
I'm entirely unsure where/what this issue is specific to, but I'm only able to recreate it with ssr.

Qt5 build (64-bit only) on Evolve OS, using the Budgie Desktop.. keyboard input doesn't work on
ssr. Mainly checking if you've encountered anything similar before, because more than likely its
an issue our end.

(CTRL+C CTRL+V = no go. Copy/paste works, so I copy/paste a filename into the dialog.)

**Comment by MaartenBaert** [comment]
I've never encountered this problem before. SSR compiled with Qt5 works fine for me except for some minor bugs in Qt5 itself (e.g. the system tray icon is missing).

If you think it's a problem on your end, you may want to disable the HotkeyListener class to see if the problem goes away. The best way to disable it is to comment out all lines that refer to HotkeyListener or HotkeyCallback in Main.cpp and PageRecord.cpp.

**Comment by ikeydoherty** [comment]
Problem finally resolved, Qt5 specific issue here:

export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb

Fixes the issue :)
