### ISSUE TITLE
GStreamer error: negotiation problem.

### ISSUE THREAD

**Issue by oshihirii** [MaartenBaert/ssr#309]
**Environment**

OS:  Linux Mint 17.1 Cinnamon 64 Bit
Kernel:  3.16.0-29-generic

**Steps to duplicate**

    sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder
    sudo apt-get update
    sudo apt-get install simplescreenrecorder

as per:  http://www.maartenbaert.be/simplescreenrecorder

Record screen 3 and save as mp4, all other settings default.

**Error**

Attempt to play (in default `Videos` application) and get error:

    An error occurred
    GStreamer error: negotiation problem

**Comment by oshihirii** [comment]
**Update**

It plays in VLC media player.

**Comment by StripedMonkey** [comment]
It might be because the codec is not supported What are you using to record
audio?

**Comment by oshihirii** [comment]
The default mic on laptop:

Acer Aspire E1-570

Is there a specific command I can run to fetch any other system information required to troubleshoot?

**Comment by StripedMonkey** [comment]
I meant the audio codec thingy. (Very technical I know)
I have had issues before where I needed to change the codec for sound
because it was not supported.

**Comment by MaartenBaert** [comment]
You are using an uncommon combination which GStreamer can't play. Try MKV + H.264 + MP3, this works in most players. You can replace MKV with MP4 if you want, this will play even on most smartphones and tablets, but the problem with MP4 is that the files will be corrupted if the recording is interrupted at any point in time.

**Comment by oshihirii** [comment]
@StripedMonkey - the settings were mainly the default ones:

- `Backend`:`Pulse Audio`  
- `Source`:`Monitor of Built-in Audio Analog Stereo`  
- `Container`:`MP4` - changed from `MKV`
- `Video`:`H.264`
- `Codec`:`Vorbis`

@MaartenBaert - thanks for the information, I will try those settings next time.

**Comment by MaartenBaert** [comment]
MP4 and Vorbis are an uncommon combination, not all players support it. I really recommend using MKV instead.

**Comment by oshihirii** [comment]
@MaartenBaert Thank you for the heads up.
