### ISSUE TITLE
[Feature Request] Recording Indicator

### ISSUE THREAD

**Issue by Purplewelshy** [MaartenBaert/ssr#314]
I use Super+ r to start and stop recording with simplescreenrecorder minimised. It would be useful if there was some form of indicator showing that recording was taking place, something like the title of the minimised program flashing to show it is recording etc.

**Comment by ubuntuaddicted** [comment]
there is already, a little red circle shows up in your system tray.

**Comment by Purplewelshy** [comment]
Here is a screenshot of my PC running simplescreenrecorder, I cant see 
any little red circle:


On 01/03/15 04:34, Ubu the Tech Guru wrote:
>
> there is already, a little red circle shows up in your system tray.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MaartenBaert/ssr/issues/314#issuecomment-76573913>.
>

-- 
My From

My sig

**Comment by Purplewelshy** [comment]
I sent the screenshot using Thunderbird, seems that this site does not support imbedded images from Thunderbird, so here is a link to the screenshot:
 
![for_github](https://cloud.githubusercontent.com/assets/11250525/6430145/da2edc88-bff5-11e4-8cfd-64ebee58cc18.png)

**Comment by ubuntuaddicted** [comment]
I'm not sure then, I have it. Are you using the latest version? Maybe your window manager isn't playing nice and it's just not showing the systray indicator.

**Comment by Purplewelshy** [comment]
SimpleScreenRecorder 0.3.3 running on Ubuntu Studio 14.04, XFCE windows manager.

**Comment by ubuntuaddicted** [comment]
Here's my XFCE 4.12 in Ubuntu 14.04 https://lh3.googleusercontent.com/-hlaOOFjbMHQ/VPMdbdCQSnI/AAAAAAAADWg/4__gbDn0wjk/w711-h806-no/ssr_notification_systray.jpg

**Comment by Purplewelshy** [comment]
Thanks, I added an indicator plugin and it now works.

**Comment by ubuntuaddicted** [comment]
OH, so you were missing an indicator applet in your system tray? Makes sense. Glad you got it figured out
