### ISSUE TITLE
Save as GIF Format

### ISSUE THREAD

**Issue by babam86** [MaartenBaert/ssr#322]
Add the ability to save as GIF format.

Thanks.

**Comment by StripedMonkey** [comment]
Correct me if I'm wrong but this is already possible. GIF format is one of
the "Other" codecs if i'm not mistaken.

**Comment by Lucki** [comment]
Please don't use gif - let it die. #196

**Comment by StripedMonkey** [comment]
So in short you don't want to use GIF as the method of recording. If you so
wish you may convert it into a GIF later but actually recording in it would
be a bad idea.

**Comment by MaartenBaert** [comment]
Duplicate of #196. Consider using WebM instead. It is supported by both Firefox and Chrome and the image quality is actually usable, unlike GIF.
