### ISSUE TITLE
openSUSE / ffmpeg / pkgconfig

### ISSUE THREAD

**Issue by DAP-DarkneSS** [MaartenBaert/ssr#327]
I've recently found ffmpeg at openSUSE:Factory (the next release) and tried to move
simplescreenrecorder package from packman (repo with software with legal problems), however `configure` complains:
[  189s] checking libavformat/avformat.h usability... no
[  189s] checking libavformat/avformat.h presence... no
[  189s] checking for libavformat/avformat.h... no
[  189s] configure: error: required header missing
https://build.opensuse.org/package/show/home:DarkSS/simplescreenrecorder
 
Of course it is built at packman just fine. openSUSE:Factory mailing list user tells: «ssr ought to use pkgconfig to detect its location and not just AC_CHECK_HEADERS». Any tips please?

**Comment by MaartenBaert** [comment]
Done. Please try it again with the latest version from the master branch.

**Comment by DAP-DarkneSS** [comment]
Thank you very much. All builds are fine.

**Comment by DAP-DarkneSS** [comment]
Finally since openSUSE Tumbleweed / 13.3 ssr can be installed from the default repositories.
