### ISSUE TITLE
Can't build and compile it

### ISSUE THREAD

**Issue by nifker** [MaartenBaert/ssr#336]
When I try to run the install script it failes because its missing a library and shows this error:
<code>checking for glPushAttrib in -lGL... no</code>
What can I do to fix this?

**Comment by MaartenBaert** [comment]
Read the README - you probably forgot a 32-bit library, or you are using an Ubuntu-based distro and you didn't create the required symlinks.

**Comment by nifker** [comment]
Already fixed this I don't know how but after a few new tries it worked.
