### ISSUE TITLE
Recording options disabled

### ISSUE THREAD

**Issue by matiasw** [MaartenBaert/ssr#340]
Hi,
This may well be user error on my part, but after compiling and installing SSR using the simple-build-and-install script on Debian sid, I can not figure out how to record the screen. The window that greets me on running simplescreenrecorder simply has a button to invoke the About dialog, and not much more (see screenshot). The option to Start recording in the pop-up menu from the system tray dialog is disabled/grayed out.
![screenshot_2015-06-14_ssr](https://cloud.githubusercontent.com/assets/184965/8148456/86bbe5c8-12a7-11e5-9832-283b23b30fa5.png)

**Comment by iamgreaser** [comment]
There's supposed to be a "Continue" button on the bottom of the window. Try maximising it if it isn't already maximised, as I think it's getting clipped off or something. Or maybe try dragging the window up higher.

**Comment by matiasw** [comment]
That window is, indeed, maximized. In windowed mode, the window resize arrows show up, but the window is not actually resizable.
I was able to close the startup window and progress from there by dragging the window beyond the top border of my desktop. This worked for the following pages as well, so I'm closing this issue.
Thank you for helping, and for providing the world with a piece of programming!
