### ISSUE TITLE
Won't record full-screen applications

### ISSUE THREAD

**Issue by williambl** [MaartenBaert/ssr#349]
Me again. This time I don't think it's just me being an idiot though. 

When recording a full screen application, I either get a black recording (Gmod) or a recording of the desktop and windows beneath the full screen app (Minecraft). OpenGL recording works, but I get a file which is only 854 x 480.
There are no errors. It just can't see the application in Full Screen.

I'm running Ubuntu 14.04.

**Comment by StripedMonkey** [comment]
In using the fullscreen setting or OpenGL?

**Comment by williambl** [comment]
OpenGL recording works, but I get a file which is only 854 x 480. Fullscreen just gives me the issue.

**Comment by StripedMonkey** [comment]
Scaling? those are the exact default dimensions. you might want to change
that

**Comment by williambl** [comment]
Will scaling actually improve quality or just upscale?

**Comment by StripedMonkey** [comment]
I don't think it changes quality other than downscaling which decreases
quality. Could be wrong though I don't use that feature too often.

**Comment by MaartenBaert** [comment]
Scaling forces a specific output resolution, nothing more. SSR always scales from the input resolution (which isn't constant in the case of OpenGL recording) to the output resolution. If the two resolutions match, then no scaling happens.

If you don't enable scaling, SSR will infer the output resolution based on the current input resolution at the moment you start the recording. In the case of minecraft, that means 854x480 if you start the recording before going fullscreen. And once the output resolution is set, it won't change.

Recording fullscreen games without OpenGL recording can be tricky, it depends on the video driver and the window manager. If possible, use OpenGL recording.

**Comment by williambl** [comment]
Thanks. I use OpenGL now.
