### ISSUE TITLE
Debian compiling

### ISSUE THREAD

**Issue by introlinux** [MaartenBaert/ssr#353]
I'm trying to compile ssr in a debian testing system and I found the dependences list in the readme file wasn't complete, I had to install also this:

 libpulse-dev libasound2-dev libxi-dev libxext-dev libxshmfence-dev libxfixes-dev libswscale-dev libavformat-dev

But now I'm stopped because some library is missing and I don't know what could it be. The out of compiling:

 ./simple-build-and-install 
Detecting x86/x64 ...
x86/x64 = --enable-x86-asm
Detecting ffmpeg/libav ...
Detected libav.
Configuring ...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for a sed that does not truncate output... (cached) /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for QT4... yes
checking for moc-qt4... /usr/bin/moc-qt4
checking for rcc-qt4... no
checking for rcc... /usr/lib/i386-linux-gnu/qt4/bin/rcc
checking for uic-qt4... /usr/bin/uic-qt4
checking for lupdate-qt4... /usr/bin/lupdate-qt4
checking for lrelease-qt4... /usr/bin/lrelease-qt4
checking for clock_gettime in -lrt... yes
checking for dlfcn.h... (cached) yes
checking for dlsym in -ldl... yes
checking for FFMPEG... yes
checking X11/Xlib.h usability... yes
checking X11/Xlib.h presence... yes
checking for X11/Xlib.h... yes
checking for X11/Xutil.h... yes
checking for XOpenDisplay in -lX11... yes
checking for X11/extensions/Xfixes.h... yes
checking for XFixesGetCursorImage in -lXfixes... yes
checking for X11/extensions/XShm.h... yes
checking for XShmCreateImage in -lXext... yes
checking for X11/extensions/XInput2.h... yes
checking for XIQueryVersion in -lXi... yes
checking alsa/asoundlib.h usability... yes
checking alsa/asoundlib.h presence... yes
checking for alsa/asoundlib.h... yes
checking for snd_pcm_open in -lasound... yes
checking pulse/context.h usability... yes
checking pulse/context.h presence... yes
checking for pulse/context.h... yes
checking for pa_context_new in -lpulse... no
configure: error: required library missing

**Comment by MaartenBaert** [comment]
Check the config.log file in the build folder, it will contain the actual error message.

**Comment by Yaakov-Belch** [comment]
You are missing the debian package `libpulse-dev`.  Follow the installation instructions from the README.md file:

    sudo dpkg --add-architecture i386
    sudo apt-get update
    sudo apt-get install build-essential pkg-config qt4-qmake libqt4-dev libavformat-dev \
      libavcodec-dev libavutil-dev libswscale-dev libasound2-dev libpulse-dev libjack-jackd2-dev \
      libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxfixes-dev libxext-dev libxi-dev g++-multilib \
      libx11-6 libxext6 libxfixes3 \
      libglu1-mesa-dev:i386 libx11-dev:i386 libxfixes-dev:i386 libgl1-mesa-dev:i386 \
      desktop-file-utils

This will install the required packages --- your installation will then succeed.
See also issue #413.

Explanation how to debug such missing dependency problems:

* The last line before the error message reads: `checking for pa_context_new in -lpulse... no`.
* This means that the library `libpulse` was not found on your debian system. (-l is short for lib).
* Google for `libpulse debian` and find out that the package `libpulse-dev` contains the needed library.
* Install this package and continue the installation...
* Note that the simplescreenrecorder on 64-bit systems builds also some 32-bit libraries.  Thus, instead of `libpulse-dev`, the package `libpulse-dev:i386` may be missing.  You can check this by manually executing the steps in `./simple-build-and-install` to see where the configuration fails (or by simply installing the normal 64-bit package and the `:i386` 32-bit package).

I hope this explanation helps for similar problems in the future.

**Comment by MaartenBaert** [comment]
32-bit libpulse is not needed, only 64-bit. Since the original message says that libpulse-dev was already installed, I suspect there is another problem. Double-check if libpulse has been installed, and check the error message in config.log to get the actual error message.

**Comment by trebmuh** [comment]
SSR is now in Debian unstable and testing. See https://tracker.debian.org/pkg/simplescreenrecorder .
@MaartenBaert : same here (again). I suggest to close it.

**Comment by MaartenBaert** [comment]
I can't believe we have that many Debian issues. Thanks for going through them all.

**Comment by trebmuh** [comment]
@MaartenBaert : no worries. I already spotted some others so I'll keep pinging you on those.

I'm glad that helps reducing the number of issue here.
