### ISSUE TITLE
Time-lapse

### ISSUE THREAD

**Issue by croizier** [MaartenBaert/ssr#361]
How to record a long, slow moving animation into a short, fast moving video?
I target a speed up between 2 and 5, and do not need audio.

**Comment by ubuntuaddicted** [comment]
you'll have to use a video editor like kdenlive or openshot and apply a speed filter to the original clip so that it appears to play 2 to 5 times as fast.

**Comment by StripedMonkey** [comment]
I would suggest klindive

On Sun, Aug 30, 2015 at 2:50 PM, Ubu the Tech Guru <notifications@github.com
