### ISSUE TITLE
Changing localization

### ISSUE THREAD

**Issue by darealshinji** [MaartenBaert/ssr#364]
Is there an easy way to change the localization? I've tried different environment variables but none of them worked. The only "solution" I found so far was to temporary move the directory `/usr/share/translations` to enable English. Why would I want this? I.e. to create a tutorial in an international language.
An environment variable or command line option to force a certain language would be convenient.

**Comment by trebmuh** [comment]
If you're running a linux box, `LANG=FR simplescreenrecorder` works.

**Comment by MaartenBaert** [comment]
Actually, the correct environment variable is LC_MESSAGES. For English, you would use:
```
LC_MESSAGES=en_US.UTF-8 simplescreenrecorder
```
LANG is used only when LC_MESSAGES is not set. LC_MESSAGES takes precedence.

**Comment by trebmuh** [comment]
Even better then.
Thanks for the tips Marteen.

**Comment by darealshinji** [comment]
Using `LC_MESSAGES=en_US.UTF-8` and `LANG=en_US.UTF-8` doesn't work, it's still in my local language. I'm using Ubuntu 14.04.

**Comment by darealshinji** [comment]
Running `LANGUAGE=en simplescreenrecorder` did it.
