### ISSUE TITLE
Ubuntu 15.10 PPA Support

### ISSUE THREAD

**Issue by myromance123** [MaartenBaert/ssr#380]
Hi!

I've noticed there is no Ubuntu 15.10 Wily support in the Simplescreenrecorder PPA. Will this be added anytime soon? Ubuntu 15.10 will be launching in about a week, and I'm currently using it and would love to use SSR on it :)

**Comment by superlex** [comment]
I agree with myromance123 :+1:

**Comment by rauldipeas** [comment]
More one on the support request.

**Comment by ml2mst** [comment]
I tried tricking by using the Vivid repository and this is the error message I've got in Synaptic
![ssr_fout](https://cloud.githubusercontent.com/assets/15306999/10714291/d1dc95d0-7ae8-11e5-9113-9d8f4dd3c126.png)

**Comment by rauldipeas** [comment]
I tried to use vivid trick too, same error.

**Comment by runn1ng** [comment]
+1

**Comment by Tlewis334** [comment]
Please fix. +1

**Comment by Twistx77** [comment]
+1

**Comment by Ryochan7** [comment]
+1

**Comment by MaartenBaert** [comment]
Done :).

**Comment by rauldipeas** [comment]
Great! Thanks!

**Comment by ChrisGiltnane** [comment]
Many thanks, much appreciated.

On 1 November 2015 at 21:28, MaartenBaert <notifications@github.com> wrote:

> Done :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MaartenBaert/ssr/issues/380#issuecomment-152865172>.
>



-- 
Regards Chris Giltnane

**Comment by ml2mst** [comment]
Thanks Maarten!
