### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by runn1ng** [MaartenBaert/ssr#382]
Since the PPA does not work for 15.10, I decided to compile it myself.

What I got though is this (after what seems like some autoconf output)
 
     checking for XOpenDisplay in -lX11... no
     configure: error: required library missing

I have no idea what that means

**Comment by trebmuh** [comment]
It means that the system you're trying to build SSR on is missing a library. If you want to compile it yourself, you want to read at the README.md : https://github.com/MaartenBaert/ssr

**Comment by Yaakov-Belch** [comment]
I had the same problem on Debian 64bit --- and solved it (see issue #413):  In addition to the packages mentioned in the README.md file, you also need to install the following Debian packages:

    libglu1-mesa-dev:i386 libx11-dev:i386 libxfixes-dev:i386 libgl1-mesa-dev:i386
    desktop-file-utils

Accepting the pull request for issue #413 should resolve this issue.

**Comment by Yaakov-Belch** [comment]
@runn1ng --- the README has been updated.  Please check that you can now build the simplescreenrecorder following the official instructions.  If it works for you --- please close this ticket as 'solved'.

**Comment by runn1ng** [comment]
Yep

**Comment by phaux** [comment]
I get the same error in Fedora 23 64bit
