### ISSUE TITLE
Build error on Ubuntu 15.10

### ISSUE THREAD

**Issue by pyprism** [MaartenBaert/ssr#384]
Hi , 
I tried to compile SSR on my ubuntu machine , but I cant able to install dependency . 
```
The following packages have unmet dependencies:
 libavcodec-dev : Depends: libavcodec-ffmpeg56 (= 7:2.7.2-1build1) but it is not going to be installed

```

**Comment by MaartenBaert** [comment]
I just tried it myself and all the dependencies listed in the readme file install just fine. I don't see any problems ...

**Comment by MaartenBaert** [comment]
By the way, I've added a package for 15.10 to the PPA now.

**Comment by pyprism** [comment]
Thanks  :smile:
