### ISSUE TITLE
Fedora 21 // Update README to include additional dependencies

### ISSUE THREAD

**Issue by Prannon** [MaartenBaert/ssr#385]
Hello,

While compiling SSR on fedora21, I ran into a few issues that required additional package installations to resolve. I encountered these issues after following all of the instructions given in the README.md file (including installing the needed packages via yum). 

**************************************
Issue #1) During library checks:
checking for gluErrorString in -lGLU... no
configure: error: required library missing

From ./build/config.log
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.9.2/../../../libGLU.so when searching for -lGLU
/usr/bin/ld: skipping incompatible /lib/libGLU.so when searching for -lGLU
/usr/bin/ld: skipping incompatible /usr/lib/libGLU.so when searching for -lGLU

Resolved by:
Installing mesa-libGLU-devel-9.0.0-7.fc21.x86_64.

Recommendation: 
Include mesa-libGLU-devel.x86_64 in README.md for Fedora under "Build Dependencies." 
**************************************
**************************************
Issue #2: During library checks: 
/usr/bin/ld: skipping incompatible /usr/lib64/libXext.so when searching for -lXext
/usr/bin/ld: cannot find -lXext

Resolved by:
Installing libXext-devel-1.3.3-2.fc21.i686.

Recommendation: 
Include libXext-devel.i686 in README.md for Fedora under "Build Dependencies."
**************************************

**Comment by MaartenBaert** [comment]
Done. I've tried to write it in such a way that it will also work on 32-bit machines.
