### ISSUE TITLE
After last update a vertical rainbow line appears

### ISSUE THREAD

**Issue by NikosEfthias** [MaartenBaert/ssr#388]
After last update a vertical rainbow line appears
heres the example of the line 
![screenshot from 2015-11-04 15 05 21](https://cloud.githubusercontent.com/assets/9097437/10937651/82aecdf0-8305-11e5-9174-e18e4011d7d4.png)

and here my system info
![screenshot from 2015-11-04 15 03 54](https://cloud.githubusercontent.com/assets/9097437/10937664/930b0092-8305-11e5-8ded-484fb79e8558.png)
![screenshot from 2015-11-04 15 01 35](https://cloud.githubusercontent.com/assets/9097437/10937665/930f2a1e-8305-11e5-9dab-3eeaaeb74009.png)

**Comment by trebmuh** [comment]
Looks to be a duplicated of https://github.com/MaartenBaert/ssr/issues/360
