### ISSUE TITLE
AUTOHIDE WINDOW

### ISSUE THREAD

**Issue by padukakerol** [MaartenBaert/ssr#391]
How to autohide the window after pressing start recording button (Ctrl+R)?

**Comment by MaartenBaert** [comment]
It doesn't work like that. You need to hide the window before you start recording, otherwise it will still be visible the first frame. Hide it first (click the system tray icon), then press the hotkey.

**Comment by padukakerol** [comment]
owh.. sorry sir, my bad.
thanks anyway.
