### ISSUE TITLE
Unable to launch Dota2 with the launch option "ssr-glinject %command%"

### ISSUE THREAD

**Issue by TimotheeJeannin** [MaartenBaert/ssr#393]
Hi,

I was using SSR on Ubuntu 14.04 to record Dota2 without issue. 

I switched to another computer that has Ubuntu 15.10 and whenever I put the `ssr-glinject %command%` launch option the game just doesn't start. There is no error message, it just says `Preparing to launch Dota2` then the popup closes and the game does not start. 

Let me know if I can do something to further diagnose the problem. :)

I hope we will be able to fix this. :) Thank your awesome work.

**Comment by TimotheeJeannin** [comment]
When I run `ssr-glinject steam steam://rungameid/570`, I have:

    [SSR-GLInject] Library loaded (64-bit).
    [SSR-GLInject] Library loaded (64-bit).
    grep: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    grep: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    grep: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    grep: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    grep: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    grep: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    awk: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    awk: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libssr-glinject.so)
    [SSR-GLInject] Library loaded (64-bit).
    /home/tim/.local/share/Steam/ubuntu12_32/steam: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/i386-linux-gnu/libssr-glinject.so)
    /home/tim/.local/share/Steam/ubuntu12_32/steam: /home/tim/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/i386-linux-gnu/libssr-glinject.so)

**Comment by ErkanMDR** [comment]
Same problem here.
`Game update: AppID 570 "Dota 2", ProcID 6840, IP 0.0.0.0:0
ERROR: ld.so: object '/home/erkanmdr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/erkanmdr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ssr-glinject: LD_PRELOAD = :/home/erkanmdr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so:/home/erkanmdr/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so:libssr-glinject.so
ssr-glinject: command = /home/erkanmdr/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh
ERROR: ld.so: object '/home/erkanmdr/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/bash: /home/erkanmdr/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libssr-glinject.so)
/bin/bash: /home/erkanmdr/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libssr-glinject.so)
Game removed: AppID 570 "Dota 2", ProcID 6840 
No cached sticky mapping in ActivateActionSet.
`

**Comment by ErkanMDR** [comment]
Same problem here

**Comment by StripedMonkey** [comment]
I believe that the issue is that you are not disabling the Steam Overlay,
If you read the guide it specifically says that you need to disable the
overlay because it can causes these kinds of issues.

**Comment by ErkanMDR** [comment]
Already disabled Steam Overlay

**Comment by MaartenBaert** [comment]
The game wants to use an old C++ library (from Ubuntu 12.04) and glinject wants a newer one (from your own distribution). The solution is to download libssr-glinject.so from Ubuntu 12.04 and put it in the Steam runtime folder. This is explained here: #214

Make sure that the version of libssr-glinject you use matches the version of SSR. I'm hoping that I can somehow automate this in the future.
