### ISSUE TITLE
RHEL6 Qt4 not found

### ISSUE THREAD

**Issue by OrcunSeden** [MaartenBaert/ssr#395]
I am using RHEL6 64 bit. I try to install SSR 0.3.6 with rpm -i. But it gives dependency error. libQtGui.so.4 is needed by SSR. I have compiled Qt4.8.6 and i have defined QTDIR, LD_LIBRARY_PATH=QTDIR/lib but dependency error still exists. Do i need to define any other variable to make SSR found QtGui.so.4.8.6. I have compiled Qt 4.8.6 both 32 and 64 bit.
./configure also says Qt4 not found and exists.

Thank you

**Comment by MaartenBaert** [comment]
You don't need LD_LIBRARY_PATH to compile. The configure script uses pkg-config to find Qt, if it is set up correctly then this should just work. If configure fails, take a look at the config.log file in the build directory, it will contain the errors messages.

**Comment by OrcunSeden** [comment]
It has been solved. Thank you
