### ISSUE TITLE
Feature Request: Automatic datestamp filenames

### ISSUE THREAD

**Issue by arcooke** [MaartenBaert/ssr#404]
Instead of requiring the user to manually set a filename each time a video is recorded, I think it would be nice if there was a way to just select the folder where videos go, and then have files automatically created with a datestamp as the filename.  Just to make the setup process a smidge quicker.

Nice work on the software, it works very well.

**Comment by MaartenBaert** [comment]
![ssr-segments](https://cloud.githubusercontent.com/assets/829608/11602016/80fec502-9ad7-11e5-8fcf-c726a2f84825.png)

;)

**Comment by arcooke** [comment]
Oops.  I thought that did something else :)

Thanks for all the arrows pointing me in the right direction
