### ISSUE TITLE
no tray icon

### ISSUE THREAD

**Issue by jojopara** [MaartenBaert/ssr#408]
Hello,

From sometime now, the red icon in the system tray when recording has disappeared.  I have upgraded Linux Mint to Rosa, the latest edition.

**Comment by MaartenBaert** [comment]
In most cases this is a problem with your taskbar setup. Icons won't appear unless there is a 'notification area' present. On some Ubuntu-based distributions you also need the 'application indicator', which looks similar but is not identical. Are other application icons, like VLC, still visible?

**Comment by jojopara** [comment]
Thank you for your prompt reply!

I don't know much about Linux and I don't know either about taskbar setup and the like you mention (I did some research though).  VLC and Video are also  not present.

**Comment by jojopara** [comment]
I tweaked the settings and now VLC is visible

**Comment by MaartenBaert** [comment]
Which desktop environment are you using? MATE or Cinnamon?

**Comment by jojopara** [comment]
Cinnamon.

Sorry for not writing it.

**Comment by MaartenBaert** [comment]
Can you post the SSR log file here? It's saved in ~/.ssr/logs.

**Comment by jojopara** [comment]
I also posted a help ticket on Mint forum.  The following advice worked: "Open the general settings of Cinnamon and disable the support for indicators."
