### ISSUE TITLE
Build fails on CentOS 6

### ISSUE THREAD

**Issue by probonopd** [MaartenBaert/ssr#410]
I am trying to build on CentOS 6 but the linker fails.

I suspect it has to do with http://stackoverflow.com/questions/26450822/attempting-to-compile-a-32-bit-application-on-centos-results-in-error

**Comment by probonopd** [comment]
Workaround:

```
cd /
wget http://people.centos.org/~tru/devtools-2/6/i386/RPMS/devtoolset-2-libstdc++-devel-4.8.2-15.el6.i686.rpm -O - | rpm2cpio | cpio -idm
cd -
```

What is the proper way to do this?

**Comment by MaartenBaert** [comment]
I don't know, I've never tried to compile SSR on CentOS. Many distributions require some kind of hack to be able to build 32-bit libraries (e.g. all the Ubuntu-based ones require some extra symlinks in the 32-bit library folder).

**Comment by probonopd** [comment]
OK, so I assume it is ok as it is. Thanks.
