### ISSUE TITLE
Debian64 build-instructions (missing libraries) (with pull request)

### ISSUE THREAD

**Issue by Yaakov-Belch** [MaartenBaert/ssr#413]
The build instructions for Debian 64bit fail because a few required packages had not been included in the build instructions:

    libglu1-mesa-dev:i386 libxfixes-dev:i386 
      (instead of libglu1-mesa:i386 libxfixes:i386 --- we need the headers)
    libx11-dev:i386 libgl1-mesa-dev:i386

    desktop-file-utils (needed for the post-install script)

After these packages are added, the ./simple-build-and-install script succeeds.

I submitted a [pull request](https://github.com/MaartenBaert/ssr/pull/412)  for the documentation --- no code changes are needed.

**Comment by MaartenBaert** [comment]
Closing since this has been merged now.
