### ISSUE TITLE
Debian build fail

### ISSUE THREAD

**Issue by amarildojr** [MaartenBaert/ssr#433]
For starters, it seems I must add an "-f" to the symbolic links:

> asd@amarildo:/usr/lib/i386-linux-gnu$ sudo ln -s libGL.so.1 libGL.so
> ln: failed to create symbolic link ‘libGL.so’: File exists
> asd@amarildo:/usr/lib/i386-linux-gnu$ sudo ln -s libGLU.so.1 libGLU.so
> ln: failed to create symbolic link ‘libGLU.so’: File exists
> asd@amarildo:/usr/lib/i386-linux-gnu$ sudo ln -s libX11.so.6 libX11.so
> ln: failed to create symbolic link ‘libX11.so’: File exists
> asd@amarildo:/usr/lib/i386-linux-gnu$ sudo ln -s libXext.so.6 libXext.so
> ln: failed to create symbolic link ‘libXext.so’: File exists
> asd@amarildo:/usr/lib/i386-linux-gnu$ sudo ln -s libXfixes.so.3 libXfixes.so
> ln: failed to create symbolic link ‘libXfixes.so’: File exists

Then, this happens:

> asd@amarildo:~/Downloads/ssr-master$ ./simple-build-and-install 
> bash: ./simple-build-and-install: /bin/bash: bad interpreter: Permission denied

What could be happening?

Debian sid

**Comment by tannx** [comment]
Looks it like a bug of debian. I got the same issue #418 and still can't do nothing.

**Comment by amarildojr** [comment]
@tannx Do like me: Add the MX15 repo, then install SSR from there :)

Instructions: http://main.mepis-deb.org/

**Comment by tannx** [comment]
@amarildojr 
it's didn't worked for me, it needs more dependencies from another source.
![screenshot from 2016-03-18 04-14-06](https://cloud.githubusercontent.com/assets/5285684/13859755/e9992b86-ecbf-11e5-9951-d2bdc8f9f60e.png)

**Comment by trebmuh** [comment]
SSR is now in Debian unstable and testing. See https://tracker.debian.org/pkg/simplescreenrecorder .
@MaartenBaert : same here. I suggest to close it.
