### ISSUE TITLE
Debian repository contains SSR

### ISSUE THREAD

**Issue by Sunderland93** [MaartenBaert/ssr#435]
Hi, Maarten. I created Debian repository on build.opensuse.com and added Simple Screen Recorder package. Main program called simplescreenrecorder, GLInject library - libssr-glinject. Here is a repository address deb http://download.opensuse.org/repositories/home:/Sunderland93/Debian_8.0/ /
and project page https://build.opensuse.org/project/show/home:Sunderland93

**Comment by trebmuh** [comment]
SSR entered the official Debian repo: https://tracker.debian.org/pkg/simplescreenrecorder
@MaartenBaert : I suggest this thread to be closed now.
