### ISSUE TITLE
Recording an app in OpenGL mode ran as a different user does not work; it removes the 'abandoned' stream

### ISSUE THREAD

**Issue by Fishkin** [MaartenBaert/ssr#440]
I want to run an OpenGL application as a different user and record it (full screen works fine but is flickery). It just doesn't work in OpenGL mode, it seems to "delete" the stream it finds in /dev/shm/ssr-Test no matter what I do. This only happens when I launch the application as a different user. Otherwise it works fine.

I've stumbled across this problem which is a real deal-breaker for me as far as OpenGL recording is concerned (I really need to use a different user). For simplicity I resorted to using glxgears for testing and a channel called 'Test'. Goes without saying that I enabled "relaxed permissions".

I have a simple launch script that uses gksudo to switch users and launches glxgears from there as the other user (called him test). This is my test launch script right now:

#!/bin/sh
nohup gksudo -S -u test -- sh -c 'LD_PRELOAD=libssr-glinject.so SSR_GLX_DEBUG=0 SSR_STREAM_RELAX_PERMISSIONS=1 SSR_CHANNEL=Test nohup glxgears >/tmp/log 2>&1 &' >/dev/null 2>&1 </dev/null &

It's a very simple script that just switches user (with nohup so the shell doesn't stay in memory while the app is running) and assigns the respective environment variables. Note that I can't launch it from SSR since it will switch users when doing so, and I *need* the launcher for that reason.

Then I launch SSR and of course enable the "Relaxed shared memory permissions (insecure)" option, and put the channel as 'Test', and I proceed to go to the Recording window. As soon as I get to the recording window, it deletes the stream!!! Same thing happens if I am already at the Record window and THEN launch the application, it will instantly delete the stream. This is what it says:

[SSRVideoStreamWatcher::GetChanges] Added stream 18881930573-12275-glx0001-glxgears.
[SSRVideoStreamReader::Init] Created video stream reader.
[SSRVideoStreamWatcher::Init] Deleted abandoned stream 18881930573-12275-glx0001-glxgears.
[SSRVideoStreamReader::Init] Destroyed video stream reader.

Here's the /tmp/log  (the terminal output)

[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library loaded (64-bit).
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
[SSR-GLInject] Warning: glXSwapBuffers called without existing frame grabber, creating one assuming window == drawable.
[SSR-GLInject] [GLXFrameGrabber 1] Created GLX frame grabber.
[SSR-GLInject] [/dev/shm/ssr-Test/video-18881930573-12275-glx0001-glxgears] Created video stream.
[SSR-GLInject] Warning: Using relaxed file permissions, any user on this machine will be able to read or manipulate the stream!
[SSR-GLInject] OpenGL version = 4.5 (4.5.0 NVIDIA 358.16).
[SSR-GLInject] [/dev/shm/ssr-Test/video-18881930573-12275-glx0001-glxgears] frame size = 300x300.

If I replace the '-u test' part with my username (the main user), it will work since it won't switch users. This only shows up when using another user, it seems it flags the stream as abandoned, no idea why.

Is there something I have to do more than this? Am I missing something or is this a bug? The same thing happens with 32-bit programs and even Wine and yes I did install the i386 lib of course.

**Comment by MaartenBaert** [comment]
Looks like I never actually tested this functionality, because I found multiple problems with it. Oops.
