### ISSUE TITLE
record audio mixer?

### ISSUE THREAD

**Issue by gwald** [MaartenBaert/ssr#443]
Hi,
Is there a way to record what comes out of the speakers? ie via a mixer?
Under JACK, there's "record system speakers", :
"[PageRecord::StartPage] Starting page ...
[JACKInput::Init] Error: Could not connect to JACK!
[PageRecord::StartPage] Error: Something went wrong during initialization.
[PageRecord::StartPage] Started page.
[SimpleSynth::Init] Warning: Buffer size 2048 is not supported, using 3072 instead. This is not a problem.
[PageRecord::StartInput] Starting input ...
[SimpleSynth::SynthThread] Synth thread started.
[MakeThreadHighPriority] Warning: Can't increase the thread priority."

I'm using Mint linux 17.1 with no problems recording the mic.
Cheers

**Comment by MaartenBaert** [comment]
Read this:
http://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/
JACK requires some extra work, but it is the most reliable option.
