### ISSUE TITLE
Cursor highlighting.

### ISSUE THREAD

**Issue by aihimel** [MaartenBaert/ssr#447]
Hello,
Is their any way to highlight the cursor when recording video?
Thanks for the great software.

**Comment by MaartenBaert** [comment]
Not yet, but I've added it to the todo list.

**Comment by ronjouch** [comment]
In case that helps, adding is [a screencast (mp4, 560kB)](https://dl.dropboxusercontent.com/u/13140569/fscapture-mouse-click-ux.mp4) of such highlighting as done by [FastStone Capture](http://faststone.org/FSCaptureDetail.htm), a neat capture tool I use when running Windows. The individually actionable features are:

- Yellow translucent circle around cursor
- On mouse click: ripples around cursor
- On mouse click: emulated mouse click sound
