### ISSUE TITLE
PPA needs higher security

### ISSUE THREAD

**Issue by LiamDawe** [MaartenBaert/ssr#448]
Just to let you know, the PPA needs to be adjusted since Ubuntu 16.04 requires higher security:

W: http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu/dists/xenial/InRelease: Signature by key 4DEDB3E05F043CA185176AC0409C8B51283EC8CD uses weak digest algorithm (SHA1)

**Comment by MaartenBaert** [comment]
As far as I know that's not my key. I only sign the [source package](https://launchpad.net/~maarten-baert/+archive/ubuntu/simplescreenrecorder/+files/simplescreenrecorder_0.3.6+1~ppa1~xenial1.dsc), and that one is actually signed with SHA256. What am I supposed to do to change the other signatures?

**Comment by LiamDawe** [comment]
I've asked for you, as there seems to be no guide that I can find on it, as it's affecting a number of PPA's I have at the moment. Will keep you posted.

**Comment by LiamDawe** [comment]
You're right, it's a problem there end to sort out it seems: https://bugs.launchpad.net/launchpad/+bug/1556666
