### ISSUE TITLE
Arch Linux XFCE4 splash is missing continue button

### ISSUE THREAD

**Issue by Sanjurjo7** [MaartenBaert/ssr#450]
The continue button is missing.

I've tried resizing it, full screening it, looking for errors. Nothing.

![screenshot_2016-05-01_11-22-13](https://cloud.githubusercontent.com/assets/9040826/14942614/e6c4910a-0f8f-11e6-8f55-ecab02d2f52d.png)
![screenshot_2016-05-01_10-58-26](https://cloud.githubusercontent.com/assets/9040826/14942615/e6c7c406-0f8f-11e6-8827-602dea92c1df.png)

any ideas?

**Comment by Sanjurjo7** [comment]
Basically, no matter what I do, there are bits of the window off the bottom of the screen.

**Comment by Brottweiler** [comment]
I think the window is just too big for your screen... There's a limit on how small you can make it.

Can you try to just hold <kbd>ALT</kbd> and move it upwards? There's something, maybe the text or the DPI, that makes the window too big.

**Comment by Sanjurjo7** [comment]
my screen's 1366X768 I've tried moving it, but no matter how high it goes it always has a bottom cut out of it.

**Comment by Sanjurjo7** [comment]
Oh, snap, I didn't know you could alt drag the window. That worked. Looking for the window settings not to alter it.

Thanks Brottweiler

**Comment by Brottweiler** [comment]
Yeah, so now you can see the bottom because you can press and move it anywhere and not just pressing the title bar. So that confirmes the window is larger than your screen, which seems to be another issue unrelated to SSR.

**Comment by MaartenBaert** [comment]
I think there is something wrong with your system theme, because the text isn't supposed to have that much empty space between the lines. This is just making the window much bigger than necessary.
