### ISSUE TITLE
in minecraft simplescreenrecorder drags screen back to desktop during each hot key initiation (rendering hot key function)

### ISSUE THREAD

**Issue by Rodartist** [MaartenBaert/ssr#453]
basically as title says it. here is an example on my neices minecraft...
it would be nice if the desktop didnt show at the start of the video:

https://www.youtube.com/watch?v=Nt_-0-z31fs

**Comment by MaartenBaert** [comment]
Use the hotkey to start the recording. That's why it exists :).

**Comment by Rodartist** [comment]
Though that was using the hot key, is there a way to avoid the refocusing the window when activating via hot key?

**Comment by StripedMonkey** [comment]
You do not have to have the SSR recording window selected in order to start
recording. Not sure why you would think that you have to have it open. :P
