### ISSUE TITLE
Debian 64: libglu1-mesa-dev conflicts with libglu1-mesa-dev:i386

### ISSUE THREAD

**Issue by DBerke** [MaartenBaert/ssr#459]
While following the instructions for installation on Debian 8 stable (64-bit), running the given apt-get command with the list of packages produced the following error and didn't install anything:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglu1-mesa-dev : Conflicts: libglu1-mesa-dev:i386 but 9.0.0-2 is to be installed
 libglu1-mesa-dev:i386 : Conflicts: libglu1-mesa-dev but 9.0.0-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Running apt-get line-by-line on the list of packages succeeded in installing them, apart from those two, where I could have either one installed at a time but installing the other would uninstall the first. I've got an NVIDIA graphics card so I figured missing mesa packages wouldn't be a problem, and indeed I haven't had any trouble with using SSR for the week or so I've been testing it. But I thought I'd point out the conflict in case someone else runs into it.

**Comment by laykatz** [comment]
Thank you for this I just ran across the same issue on Debian Jessie 8 fresh install

**Comment by MaartenBaert** [comment]
Maybe the situation has changed, when I was testing things I needed those packages in order to compile the 32-bit version of libssr-glinject successfully. You don't need them to run SSR, just for compiling.
