### ISSUE TITLE
Debian Jessie

### ISSUE THREAD

**Issue by bonbonboi** [MaartenBaert/ssr#467]
Hello, I did everything could be done, still getting this error:
checking for gluErrorString in -lGLU... no
configure: error: required library missing

**Comment by trebmuh** [comment]
Hi,
You should install the "libglu1-mesa-dev" package.

**Comment by bonbonboi** [comment]
Already installed.

**Comment by bonbonboi** [comment]
Well, I solved finally, the issue was not mentioned in README.md file, 
$sudo dpkg --add-architecture i386
$sudo apt-get update
$sudo apt-get install build-essential pkg-config qt4-qmake libqt4-dev libavformat-dev \
    libavcodec-dev libavutil-dev libswscale-dev libasound2-dev libpulse-dev libjack-jackd2-dev \
    libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxfixes-dev libxext-dev libxi-dev g++-multilib \
    libx11-6 libxext6 libxfixes3 \
    libglu1-mesa-dev:i386 libx11-dev:i386 libxfixes-dev:i386 libgl1-mesa-dev:i386 \
    desktop-file-utils

The missing package is: libglu1-mesa:i386
Was an epic compilation took me a significant time to figure out the missing parts.
