### ISSUE TITLE
Black screen in rendered video

### ISSUE THREAD

**Issue by Hunkofchunk** [MaartenBaert/ssr#477]
Every time I finish a recording the output video is always black however, my sound works perfectly. I am using an arch linux operating system with a nvidia graphics card (proprietary).

**Here is the contents of my settings.conf**
[global]
nvidia_disable_flipping=ask

[input]
profile=Luke%27s%20Studio
video_area=screen
video_area_screen=1
video_x=0
video_y=0
video_w=1920
video_h=1080
video_frame_rate=30
video_scale=false
video_scaled_w=854
video_scaled_h=480
video_record_cursor=true
audio_enabled=true
audio_backend=pulseaudio
audio_alsa_source=default
audio_pulseaudio_source=alsa_input.usb-Samson_Technologies_Samson_C01U_Pro_Mic-00.analog-stereo
audio_jack_connect_system_capture=true
audio_jack_connect_system_playback=false

Here is an example video: [My Second Recording-2016-08-14_14.46.54.mkv.tar.gz](https://github.com/MaartenBaert/ssr/files/417944/My.Second.Recording-2016-08-14_14.46.54.mkv.tar.gz)

**Comment by MaartenBaert** [comment]
That video file looks just fine here. Could it be a problem with your video player?

**Comment by Hunkofchunk** [comment]
No worries. I had just fixed the issue. It turns out I hadn't installed a
VLC player.

Thank you for replying and on a free service as well! :)

I'll mark my thread as solved on your github page.
