### ISSUE TITLE
Feature Request to add vdaapi

### ISSUE THREAD

**Issue by rp2pilot** [MaartenBaert/ssr#480]
The latest version of FFmpeg support GPU assisted h264 encoding through vaapi.    Encode speed for h264 is about 3 times faster than x264 CPU encoding.  Adding this capability would dramatically improve live screen capture. 

I have had some success using x11grab as the input, but it would be far nicer to encapsulate the details in SimpleScreenRecorder.

**Comment by MaartenBaert** [comment]
Duplicate of #466.
