### ISSUE TITLE
SSR - no codecs that ffmpeg has

### ISSUE THREAD

**Issue by pashinin** [MaartenBaert/ssr#488]
I've updated my ffmpeg in both paths (`/usr/bin`, `/usr/local/bin`) to have NVENC codec:

```
DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_vdpau ) (encoders: libx264 libx264rgb h264_nvenc h264_vaapi nvenc nvenc_h264 )
D.VIL. hap                  Vidvox Hap decoder
DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (encoders: nvenc_hevc hevc_nvenc hevc_vaapi )
```

But in SSR there are no `nvenc_` codecs. What can be wrong?

**Comment by MaartenBaert** [comment]
No idea, it did work for me. Are you using the latest SSR?

Try running ```ldd /usr/bin/simplescreenrecorder``` to ensure that you are really loading the right FFmpeg.

**Comment by pashinin** [comment]
https://gist.github.com/pashinin/fdf012fe55c3d583666dc54944ffd17c

I just run ffmpeg for now. If anyone have it - reopen
