### ISSUE TITLE
[JACKInput::Init] Error:

### ISSUE THREAD

**Issue by jojopara** [MaartenBaert/ssr#494]
Hello,

When I try to record, I get the following:
'[PageRecord::StartPage] Starting page ...
[JACKInput::Init] Error: Could not connect to JACK!
[PageRecord::StartPage] Error: Something went wrong during initialization.
[PageRecord::StartPage] Started page.'

The output is not readable in players.

Thank you!

I panic\ked as I needed to record something  urgently!  My Backend tab had changed to JACK and thus the issue.  Returning it to ALSA corrected the small problem.

**Comment by StripedMonkey** [comment]
If I may ask, what was the issue?

**Comment by jojopara** [comment]
Certainly!


Somehow there was /JACK/ from the pull-down menu against /Backend/ on 
the second window of the programme after start.  When I put it to /ALSA/ 
the probrlem got corrected; I do not know whehter I can record sound or 
not now as it was not needed.

Regards,

George

**Comment by jojopara** [comment]
Please reply, if you have received mu answers as I do not know how 
Github system works.

**Comment by StripedMonkey** [comment]
I got it :P
