### ISSUE TITLE
Gnome 3 - Invisible tray icon

### ISSUE THREAD

**Issue by xalalau** [MaartenBaert/ssr#495]
Hello!

I'm using Ubuntu Gnome with the staging ppa:
https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging

And I'm getting this error:
```
---@----:~$ simplescreenrecorder 
==================== SSR iniciado ====================
SimpleScreenRecorder 0.3.6
Compiled with GCC 5.3.1
Qt: header 4.8.7, lib 4.8.7
libavformat: header 56.40.101, lib 56.40.101
libavcodec: header 56.60.100, lib 56.60.100
libavutil: header 54.31.100, lib 54.31.100
libswscale: header 3.1.101, lib 3.1.101
[CPUFeatures::Detect] Recursos da CPU: mmx sse sse2 sse3 ssse3 sse4_1 sse4_2 avx
[ALSAInput::GetSourceList] Gerando lista de fontes ...
[ALSAInput::GetSourceList] Encontrada placa: [hw:0] HDA Intel PCH
[ALSAInput::GetSourceList] Encontrado dispositivo: [hw:0,0] HDA Intel PCH: CX20590 Analog
[PulseAudioInput::GetSourceList] Gerando lista de fontes ...
[SourceNamesCallback] Fonte encontrada: [alsa_output.pci-0000_00_1b.0.analog-stereo.monitor] Monitor of Áudio interno Estéreo analógico
[SourceNamesCallback] Fonte encontrada: [alsa_input.pci-0000_00_1b.0.analog-stereo] Áudio interno Estéreo analógico
QSystemTrayIcon::setVisible: No Icon set
```

![Error](http://i.imgur.com/RMoOG8c.png)

An invisible tray icon only for simplescreenrecorder...

How do I fix it?

Thanks.

**Comment by MaartenBaert** [comment]
SSR is trying to load the icon but it can't find it. It should be located in /usr/share/icons/hicolor/WxH/apps/simplescreenrecorder.png. Was SSR installed properly?

**Comment by xalalau** [comment]
Well, I just fallowed the install instructions, there was no compiling or extra steps.
```
sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder
sudo apt-get update
sudo apt-get install simplescreenrecorder
# if you want to record 32-bit OpenGL applications on a 64-bit system:
sudo apt-get install simplescreenrecorder-lib:i386
```
The desktop and OpenGL games are record-able and the options work, only the icons are problematic.

http://imgur.com/a/xs7dX
The screenshots show that I have a bunch of SSR pngs/svgs installed by default but no "/usr/share/icons/hicolor/WxH/apps/" folder.
I created this myself and moved the 22x22 png icons there (+ svgs, later), but nothing happened... http://i.imgur.com/0avJncP.png

**Comment by MaartenBaert** [comment]
The 'WxH' was just an example, that's where the size goes ;).
I have no idea why SSR can't find the icon, my best guess is that your current icon theme isn't standard compliant and forgot to inherit the 'hicolor' theme. You could try to fix this by opening the ```index.theme``` file for your icon theme and add ```hicolor``` to the ```Inherits``` key under ```[Icon Theme]```. For example, this is what the ```index.theme``` file for the Faenza theme looks like:
```
[Icon Theme]
Name=Faenza
Inherits=gnome,hicolor
Comment=Icon theme project with tilish style, by Tiheum
Directories=emblems/8,actions/16,animations/16,apps/16,categories/16,devices/16,emblems/16,mimetypes/16,places/16,status/16,stock/16,actions/22,animations/22,apps/22,categories/22,devices/22,emblems/22,mimetypes/22,places/22,status/22,stock/22,actions/24,animations/24,apps/24,categories/24,devices/24,emblems/24,mimetypes/24,places/24,status/24,stock/24,actions/32,animations/32,apps/32,categories/32,devices/32,emblems/32,mimetypes/32,places/32,status/32,stock/32,actions/48,animations/48,apps/48,categories/48,devices/48,emblems/48,mimetypes/48,places/48,status/48,stock/48,actions/64,animations/64,apps/64,categories/64,devices/64,emblems/64,mimetypes/64,places/64,status/64,stock/64,actions/96,animations/96,apps/96,categories/96,devices/96,emblems/96,mimetypes/96,places/96,status/96,stock/96,actions/scalable,apps/scalable,categories/scalable,devices/scalable,emblems/scalable,mimetypes/scalable,places/scalable,status/scalable,stock/scalable
```

**Comment by xalalau** [comment]
Omg... WxH kkkk lol
Anyway, I tried what you suggested and a little more. I changed the Inherits (for Adwaita), restarted the PC, changed the icon theme for hicolor, restarted again, but it's still invisible.
I think I'll need to somehow bind a notification telling whether it's on or off, it's better than nothing... I don't know. Damn.

**Comment by xalalau** [comment]
Hi

I """solved""" the problem by writing and running this script:

```
#!/bin/bash

program="simplescreenrecorder"
icon_theme_from="hicolor"
icon_theme_to="Adwaita"

echo
echo "Coping \"$program\" icons from \"$icon_theme_from\" to \"$icon_theme_to\"..."
echo
for file in $(find /usr/share/icons/$icon_theme_from -type f -follow); do
    if [[ $file == *"$program"* ]]; then
        file_aux=""
        dir_aux=""
        IFS='/' read -r -a array <<< "$file"
        for element in "${array[@]}"; do
            if [[ $element = *[!\ ]* ]]; then
                if [[ $element == *"$icon_theme_from"* ]]; then
                    file_aux=$file_aux"/"$icon_theme_to
                else
                    file_aux=$file_aux"/"$element
                fi
            fi
        done
        dir_aux=$(dirname $file_aux)
        if [ -d "$dir_aux" ]; then
            sudo cp $file $file_aux
            echo [OK] $file_aux
        else
            echo [--] $file
        fi
    fi
done
echo
echo "Done!"
echo
```

![script](http://i.imgur.com/5gtI9xP.png)
![bug_ok](http://i.imgur.com/2o5cu6C.png)

But the icon is not correctly aligned for some reason...
Ugly as hell...

Anyway, I think we can close this report now.
