### ISSUE TITLE
can't compile on armv7hl

### ISSUE THREAD

**Issue by martinkg** [MaartenBaert/ssr#497]
In file included from elfhacks.c:20:0:
elfhacks.h:63:3: error: #error neither __elf32 nor __elf64 is defined
 # error neither __elf32 nor __elf64 is defined
   ^~~~~
elfhacks.c:34:37: error: unknown type name 'ElfW_Sword'
 int eh_find_next_dyn(eh_obj_t *obj, ElfW_Sword tag, int i, ElfW(Dyn) **next);
                                     ^~~~~~~~~~
elfhacks.c:422:37: error: unknown type name 'ElfW_Sword'
 int eh_find_next_dyn(eh_obj_t *obj, ElfW_Sword tag, int i, ElfW(Dyn) **next)
                                     ^~~~~~~~~~
elfhacks.c: In function 'eh_set_rela_plt':
elfhacks.c:456:6: warning: implicit declaration of function 'eh_find_next_dyn' [-Wimplicit-function-declaration]
  if (eh_find_next_dyn(obj, DT_PLTRELSZ, p, &relasize))
      ^~~~~~~~~~~~~~~~
elfhacks.c:460:20: warning: implicit declaration of function 'ELFW_R_SYM' [-Wimplicit-function-declaration]
   if (!obj->symtab[ELFW_R_SYM(rela[i].r_info)].st_name)
                    ^~~~~~~~~~
make[2]: *** [Makefile:505: libssr_glinject_la-elfhacks.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from Hook.cpp:11:0:
elfhacks.h:63:3: error: #error neither __elf32 nor __elf64 is defined
 # error neither __elf32 nor __elf64 is defined
   ^~~~~
make[2]: *** [Makefile:550: libssr_glinject_la-Hook.lo] Error 1

complete messages on the rpmfusion build server:
http://koji.rpmfusion.org/kojifiles/work/tasks/8145/38145/build.log

**Comment by martinkg** [comment]
was already requested on 16 August 2012
https://github.com/nullkey/glc/issues/38

**Comment by Kicer86** [comment]
As a fast workaround you may try pass --disable-glinjectlib to configure if you do not need glinject

**Comment by martinkg** [comment]
thanks for your feedback.
