### ISSUE TITLE
[Ubuntu 16.10] Muxer.cpp:100:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’; did you mean ‘codec’?

### ISSUE THREAD

**Issue by ckorn** [MaartenBaert/ssr#503]
The build fails here on Ubuntu 16.10:

```
AV/Output/Muxer.cpp: In member function ‘VideoEncoder* Muxer::AddVideoEncoder(const QString&, const std::vector<std::pair<QString, QString> >&, unsigned int, unsigned int, unsigned int, unsigned int)’:
AV/Output/Muxer.cpp:100:46: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’; did you mean ‘codec’?
   if(avcodec_parameters_from_context(stream->codecpar, codec_context) < 0) {
```

This is the entire build log:
https://paste.ubuntuusers.de/423193/

// For my reference: https://paste.ubuntuusers.de/423198/

**Comment by MaartenBaert** [comment]
Ubuntu 16.10 has switched from libav back to ffmpeg again. So you should remove the --disable-ffmpeg-versions configure flag.

**Comment by ckorn** [comment]
Works, thanks.

**Comment by jishnujayakumar** [comment]
Hey @MaartenBaert, 
How did you fix that? 
Can you tell the exact command or steps?

**Comment by MaartenBaert** [comment]
@jishnujayakumar The build system has switched to CMake. Read the README file.

**Comment by liangguohao66** [comment]
centos, same error.  what's is the solution?  @ckorn 

avformat.c: In function 'no_video_decode_packets':
avformat.c:2464:59: error: 'AVStream {aka struct AVStream}' has no member named 'codecpar'; did you mean 'codec'?
   switch_packetizer_feed_extradata(context->packetizer, st->codecpar->extradata, st->codecpar->extradata_size);
