### ISSUE TITLE
SSR stopped Segmentation fault

### ISSUE THREAD

**Issue by Vascom** [MaartenBaert/ssr#508]
Every time I exit from SSR I see:
==================== SSR stopped ====================
Segmentation fault (core dumped)

and nonzero exit status.

Is this a problem? Can you solve it?

**Comment by MaartenBaert** [comment]
If it happens after the 'SSR stopped' message, it can't really do any harm anymore, but clearly it's not something that should be happening at all. You would have to run it from a debugger to see what is actually going on. Try starting SSR with ```gdb simplescreenrecorder``` followed by ```run```, and when it crashes, type ```bt full``` and post the output here.

**Comment by Vascom** [comment]
Done:

Starting program: /usr/bin/simplescreenrecorder 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe1f3e700 (LWP 14245)]
==================== SSR started ====================
SimpleScreenRecorder 0.3.8
Compiled with GCC 6.2.1
Qt: header 5.6.1, lib 5.6.1
libavformat: header 57.41.100, lib 57.25.100
libavcodec: header 57.48.101, lib 57.24.102
libavutil: header 55.28.100, lib 55.17.103
libswscale: header 4.1.100, lib 4.0.100
[CPUFeatures::Detect] CPU features: mmx sse sse2 sse3
[New Thread 0x7fffd4c1b700 (LWP 14246)]
[ALSAInput::GetSourceList] Generating source list ...
[ALSAInput::GetSourceList] Found card: [hw:0] HDA Intel
[ALSAInput::GetSourceList] Found device: [hw:0,0] HDA Intel: ALC882 Analog
[ALSAInput::GetSourceList] Found device: [hw:0,2] HDA Intel: ALC882 Alt Analog
[PulseAudioInput::GetSourceList] Generating source list ...
[SourceNamesCallback] Found source: [alsa_output.pci-0000_00_1b.0.analog-stereo.monitor] Monitor of ?????????? ????? ?????????? ??????
Detaching after fork from child process 14247.
==================== SSR stopped ====================
[Thread 0x7fffe1f3e700 (LWP 14245) exited]
[Thread 0x7fffd4c1b700 (LWP 14246) exited]

Thread 1 "simplescreenrec" received signal SIGSEGV, Segmentation fault.
0x00007ffff499b9b3 in QIcon::~QIcon() () from /lib64/libQt5Gui.so.5
(gdb) bt full
#0  0x00007ffff499b9b3 in QIcon::~QIcon() () at /lib64/libQt5Gui.so.5
#1  0x00007ffff49a9058 in ScalableEntry::~ScalableEntry() () at /lib64/libQt5Gui.so.5
#2  0x00007ffff49a2a3e in QIconLoaderEngine::~QIconLoaderEngine() () at /lib64/libQt5Gui.so.5
#3  0x00007ffff49a2ad9 in QIconLoaderEngine::~QIconLoaderEngine() () at /lib64/libQt5Gui.so.5
#4  0x00007ffff499b9b6 in QIcon::~QIcon() () at /lib64/libQt5Gui.so.5
#5  0x00007ffff30b4258 in __run_exit_handlers () at /lib64/libc.so.6
#6  0x00007ffff30b42a5 in  () at /lib64/libc.so.6
#7  0x00007ffff309b738 in __libc_start_main () at /lib64/libc.so.6
#8  0x000000000041dd79 in _start ()

**Comment by MaartenBaert** [comment]
That's a Qt5 bug in the code that is supposed to handle SVG icons. I can't do anything about this. Which Linux distribution is this? Did you compile SSR yourself or was this a precompiled package?

**Comment by Vascom** [comment]
It is in Fedora 24. I am maintainer of simplescreenrecorder in rpmfusion repo.
In Fedora 25 with Qt 5.7.0 problem is absent.

**Comment by MaartenBaert** [comment]
In that case, you could try to compile with Qt4 instead, it is usually much more stable. Otherwise you would have to update Qt to 5.7 on Fedora 24 which I assume is not an option.

You may also be able to work around the issue by removing the file:
/usr/share/icons/hicolor/scalable/apps/simplescreenrecorder.svg
That's assuming it's only the SVG file that causes the problem. SSR contains fixed-size icons for all common sizes so removing the SVG should not be a big problem.

**Comment by Vascom** [comment]
Thanks.
Because it is not SSR problem I will remove svg from package may be.
