### ISSUE TITLE
Debian official repo

### ISSUE THREAD

**Issue by trebmuh** [MaartenBaert/ssr#510]
Hi Marteen and all

Just letting you know that SSR is on its way to get included in the next Debian stable since it did enter the NEW queue today ( https://ftp-master.debian.org/new.html -> https://ftp-master.debian.org/new/simplescreenrecorder_0.3.6-1.html ).

Hope that helps.

References: https://github.com/MaartenBaert/ssr/issues/455 https://github.com/MaartenBaert/ssr/issues/435 https://github.com/MaartenBaert/ssr/issues/481 https://github.com/MaartenBaert/ssr/issues/256 https://github.com/MaartenBaert/ssr/issues/306 https://github.com/MaartenBaert/ssr/issues/418

**Comment by Sunderland93** [comment]
Great! And when it is added to the repository?

**Comment by trebmuh** [comment]
When Stretch will be ready (this is Debian).

**Comment by trebmuh** [comment]
It's in for stretch: https://tracker.debian.org/pkg/simplescreenrecorder
Closing then.

**Comment by trebmuh** [comment]
@MaartenBaert : now that 0.3.8 is in the official repository for debian (here : https://packages.debian.org/simplescreenrecorder ), would you mind adding a line here : http://www.maartenbaert.be/simplescreenrecorder/#download ?

**Comment by MaartenBaert** [comment]
Done.

**Comment by trebmuh** [comment]
Thanks @MaartenBaert
