### ISSUE TITLE
Issue with tray icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [MaartenBaert/ssr#520]
Can you please rename the normal indicator from `simplescreenrecorder` to `simplescreenrecorder-indicator`? This issue causes many issues as if you use a theme that provides both the tray icon and the application icon, the application icon will be picked up instead of the tray icon. 
The theme can provide the tray icon (monochrome one) for smaller sizes (16,22,24) but in this case, it will cause some visibility issues on larger/smaller screens as either the application icon will be used a tray icon or vice-versa. 
Here's a screenshot of the issue using Numix Circle theme
![ba912ef2-d971-11e6-9d5c-db13822b1865](https://cloud.githubusercontent.com/assets/7660997/21967054/11ffae4c-db80-11e6-9ed4-948c73a622cc.png)
This can be easily fixed by copying the same icon and renaming it to `simplescreenrecorder-indicator` and adding few lines of code. 
I will create a PR to adresse this

**Comment by MaartenBaert** [comment]
Ok, makes sense. I will wait for the pull request.

**Comment by bil-elmoussaoui** [comment]
Done :)
