### ISSUE TITLE
blinking

### ISSUE THREAD

**Issue by jojopara** [MaartenBaert/ssr#530]
Hello,
 I had no issues with Mint Cinnamon.  I switched to Majnaro Cinnamon=  I have blinking when recording.
See 
https://mega.nz/#!NUsWFABQ!JhT0TKcKlBu1ckIgv5Xz_9ot6GjMfa1NPMfsVBniq-4

Decryption key

!JhT0TKcKlBu1ckIgv5Xz_9ot6GjMfa1NPMfsVBniq-4

**Comment by MaartenBaert** [comment]
Unfortunately there is not much I can do about this. It's a known issue with some compositing window managers, notably those based on Mutter (this includes Cinnamon). I don't know why you did not have issues previously.
