### ISSUE TITLE
Audio switching to microphone during recording

### ISSUE THREAD

**Issue by brmbrmcar** [MaartenBaert/ssr#531]
This is possibly a pulseaudio issue, I understand.

Sometimes when I record, I get the following warning:

> [PulseAudioInput::InputThread] Warning: Stream was moved to a different source.

and the microphone activates. Any way of fixing this? It is getting annoying.

**Comment by MaartenBaert** [comment]
SSR doesn't cause this, it's a notification that PulseAudio itself has moved SSR to a different source. I have no control over this. Try reading the PulseAudio logs to figure out why it is doing this.
