### ISSUE TITLE
Missing Panel Icon even when app is running

### ISSUE THREAD

**Issue by rstreeter** [MaartenBaert/ssr#540]
I was using the app just last week and the panel icon was present, and when i tried to use it the other day it was gone. I was wondering why this was happening, and how I might be able to fix this.
![screenshot at 07-24-55](https://cloud.githubusercontent.com/assets/500779/26494628/2e3a698c-41e5-11e7-8327-6762272972d6.png)
![screenshot at 07-27-19](https://cloud.githubusercontent.com/assets/500779/26494629/2e3acf30-41e5-11e7-983a-2ed0b0a162fb.png)

I am using Xubuntu 16.04

**Comment by MaartenBaert** [comment]
This usually happens with icon themes that are not configured correctly. There is a default 'hicolor' icon theme where regular applications (including SSR) put their default icons. The user can then install other icon themes which provide different icons, like you have done. These icon themes are supposed to have the 'hicolor' theme configured as a fallback, so that missing icons will be taken from the default theme, but that's not happening here.

There are two solutions for this. One is to modify the `index.theme` file of the icon theme to include 'hicolor' as a fallback, for example:
```
[Icon Theme]
Name=Faenza
Inherits=hicolor
```
This may interfere with future updates though. The other solution is to copy the SSR icons into your icon theme. The full list for SSR is:
```
./96x96/apps/simplescreenrecorder-idle.png
./96x96/apps/simplescreenrecorder.png
./96x96/apps/simplescreenrecorder-recording.png
./96x96/apps/simplescreenrecorder-paused.png
./96x96/apps/simplescreenrecorder-error.png
./64x64/apps/simplescreenrecorder-idle.png
./64x64/apps/simplescreenrecorder.png
./64x64/apps/simplescreenrecorder-recording.png
./64x64/apps/simplescreenrecorder-paused.png
./64x64/apps/simplescreenrecorder-error.png
./48x48/apps/simplescreenrecorder-idle.png
./48x48/apps/simplescreenrecorder.png
./48x48/apps/simplescreenrecorder-recording.png
./48x48/apps/simplescreenrecorder-paused.png
./48x48/apps/simplescreenrecorder-error.png
./24x24/apps/simplescreenrecorder-idle.png
./24x24/apps/simplescreenrecorder.png
./24x24/apps/simplescreenrecorder-recording.png
./24x24/apps/simplescreenrecorder-paused.png
./24x24/apps/simplescreenrecorder-error.png
./16x16/apps/simplescreenrecorder-idle.png
./16x16/apps/simplescreenrecorder.png
./16x16/apps/simplescreenrecorder-recording.png
./16x16/apps/simplescreenrecorder-paused.png
./16x16/apps/simplescreenrecorder-error.png
./256x256/apps/simplescreenrecorder-idle.png
./256x256/apps/simplescreenrecorder.png
./256x256/apps/simplescreenrecorder-recording.png
./256x256/apps/simplescreenrecorder-paused.png
./256x256/apps/simplescreenrecorder-error.png
./22x22/apps/simplescreenrecorder-idle.png
./22x22/apps/simplescreenrecorder.png
./22x22/apps/simplescreenrecorder-recording.png
./22x22/apps/simplescreenrecorder-paused.png
./22x22/apps/simplescreenrecorder-error.png
./192x192/apps/simplescreenrecorder-idle.png
./192x192/apps/simplescreenrecorder.png
./192x192/apps/simplescreenrecorder-recording.png
./192x192/apps/simplescreenrecorder-paused.png
./192x192/apps/simplescreenrecorder-error.png
./scalable/apps/simplescreenrecorder-error.svg
./scalable/apps/simplescreenrecorder-idle.svg
./scalable/apps/simplescreenrecorder-recording.svg
./scalable/apps/simplescreenrecorder.svg
./scalable/apps/simplescreenrecorder-paused.svg
./32x32/apps/simplescreenrecorder-idle.png
./32x32/apps/simplescreenrecorder.png
./32x32/apps/simplescreenrecorder-recording.png
./32x32/apps/simplescreenrecorder-paused.png
./32x32/apps/simplescreenrecorder-error.png
./128x128/apps/simplescreenrecorder-idle.png
./128x128/apps/simplescreenrecorder.png
./128x128/apps/simplescreenrecorder-recording.png
./128x128/apps/simplescreenrecorder-paused.png
./128x128/apps/simplescreenrecorder-error.png
```

**Comment by rstreeter** [comment]
It is the same with any icon theme I try.

**Comment by glaubersm** [comment]
any progress?
ssr installed from git has the same bug.

**Comment by MaartenBaert** [comment]
I have no control over this. I'm using standard Qt functionality, if that doesn't work, it's either a Qt bug or a flaw in the way your distro has set up the system tray. In either case I can't fix this.

**Comment by glaubersm** [comment]
ssr installed on kde neon distribution via ppa repository has the same bug.
But the system tray icon is available in opensuse tumbleweed running kde plasma.
