### ISSUE TITLE
Timed Recording

### ISSUE THREAD

**Issue by chhackm** [MaartenBaert/ssr#542]
No Linux recorder seems to have this feature, so I guess it's non-trivial to engineer, but the ability to preset a maximum duration for the recording would be just fantastic.

**Comment by MaartenBaert** [comment]
It's already on the todo list.

**Comment by xdya** [comment]
Need timed recording too (eg. a timer to restrict the recording duration). Seems not yet provided?

**Comment by mitchd123** [comment]
Until this  feature is implemented, here's a messy but effective workaround.  Use the sleep command with pkill.   Use the default MKV container which recovers from a crashed session, unlike MP4.  If an MP4 container is required, one could experiment with 'separate file per segment' to test MP4, and extending the recording time to get a clean close of the file/segment. (I have not tried this, MKV is fine for me) 

For example to record for 1 hour:

- run the following command in a terminal window:   (60 minutes + 5 minute buffer )
       sleep 65m && pkill simplescreen**rec**

Run simplescreenrecorder as you normally would, knowing that pkill will stop it in 65 minutes. 

One can then edit the output video file to trim off the beginning and end with the program avidemux.

**Comment by your-diary** [comment]
Using [`ssr_timer.sh`](https://github.com/your-diary/ssr_timer) I wrote, you can pause recording after some specified time.

**Comment by PaulAndrewAnderson** [comment]
LM-20.1 user here. Love SimpleScreenRecorder! Issue: I sleep 8pm to 4am or so; I love this routine as I spend my time outdoors in the wee hours of the morning. However, during baseball season, so many games that I stream start at 7pm (local time), and so I fall asleep watching them, and so, I just skip them (bummer). Then I thought; if I start recording a game at 7pm then go to bed, I can watch it the following morning. Problem is, as you know, it will just keep going. The only current solution is to buy an HDML-Cloner Box Pro (https://www.amazon.com/dp/B012T1D0IG) capture box with schedule recording. That would pretty much render SSR obsolete, but, add another pricey device to the pile. A simple begin/end recording function would take the program from a manual screen recorder, like so many others, and almost take it to the level of DVR. I'd still have to initiate the live sports stream, but then it would not have to be babysat afterwards; one can sleep or just leave the house. In other live stream situations, such as (e.g.) Paramount/CBS live TV, streams like that could be left on, and SSR setup to begin/end a recording. That would be awesome! FYI ~ PaulAndrewAndferson.org

**Comment by maowerner** [comment]
Seeing this issue is stil open and also mentioned earlier in #59 and  #301 this does not yet seem to be implemented. I would also very much like to set a recording schedule when to start and stop the recording.
@MaartenBaert are there already some ideas how to implement this / how not to implement this? If you give me a few pointers I would like to contribute.

**Comment by MaartenBaert** [comment]
It has been implemented for a long time now - if you don't see the recording schedule button then you are using an outdated version of SSR.
