### ISSUE TITLE
Simple Screen Recorder records sound only with black screen

### ISSUE THREAD

**Issue by KhitMinnyo** [MaartenBaert/ssr#565]
I am using Kali Linux 2017.1 64bit Version
I installed SimpleScreenRecorder and recorded many screen-castings. 
But, Now, I'm facing a knotty problem.
SSR records sound but not include Screencasting .

![screenshot from 2017-08-18 17-59-10](https://user-images.githubusercontent.com/31130776/29457186-f7ae367a-83e6-11e7-968d-00024bc8ff6c.png)
Please, Help me with this. 

Thanks

**Comment by isapir** [comment]
I'm facing the same issue on Fedora 26 64bit

**Comment by isapir** [comment]
This seems to be an issue with [Wayland](https://wayland.freedesktop.org/), which is the default with modern Fedora distributions.  Switching to X11 resolves this issue.

**Comment by QuImUfu** [comment]
which makes this another duplicate of #431

**Comment by isapir** [comment]
I agree.  AFAIC this one can be closed as duplicate.

**Comment by KhitMinnyo** [comment]
Thank for your help. Now I'm OK. Thanks

**Comment by AdnanHodzic** [comment]
I just had this problem on Debian 10 Buster a year and half later after this issue was initially opened. 

Switching back to X11 fixed the issue. But I was curious if there are plans to support Wayland in future? 

Thanks

**Comment by umeklinks** [comment]
Hello, I don't know if you have fixed this bug but you haven't let me help out because I ran into same issue. Here's a solution (I'm running on Fedora 30):

Your need to Configuring Xorg as the default GNOME session. On your terminal open your `custom.conf` by typing the this command `sudo nano /etc/gdm/custom.conf` and uncomment `WaylandEnable=false` if it's commented but must be set to `false`

Then, on the [daemon] section just under `WaylandEnable=false` add this line `DefaultSession=gnome-xorg.desktop` and save the file. Then try running your Screen Recorder program again.
Congratulations.

However, if `nano` command is not working please try installing it by running the command 
`sudo dnf install nano` or `sudo apt-get install nano` which ever one works for you.

**Comment by isapir** [comment]
Thanks, I'll try it if I bump into the issue again.  IIRC, last time I switched my login to X11 to resolve the issue.

**Comment by MrAbdurakhimov** [comment]
I am having this issue on Linux 18.04 but I don't have anything on (https://github.com/MaartenBaert/ssr/issues/565#issuecomment-518389403)

**Comment by MrAbdurakhimov** [comment]
It didn't work

**Comment by europ** [comment]
I have the same problem.

It records mouse and sound but it does not record the screen.

```
$ date
Mon 13 Apr 10:51:27 CEST 2020

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 30 (Thirty)
Release:        30
Codename:       Thirty

$ echo $XDG_SESSION_TYPE
wayland

$ loginctl show-session 2 -p Type
Type=wayland

$ dnf info simplescreenrecorder
Installed Packages
Name         : simplescreenrecorder
Version      : 0.3.11
Release      : 7.fc30
Architecture : x86_64
Size         : 3.7 M
Source       : simplescreenrecorder-0.3.11-7.fc30.src.rpm
Repository   : @System
From repo    : rpmfusion-free
Summary      : Simple Screen Recorder is a screen recorder for Linux
URL          : http://www.maartenbaert.be/simplescreenrecorder/
License      : GPLv3
Description  : It is a screen recorder for Linux.
             : Despite the name, this program is actually quite complex.
             : It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC
```

![Screenshot from 2020-04-13 10-58-22](https://user-images.githubusercontent.com/22373707/79108058-d36cf400-7d75-11ea-953b-b854494e1b91.png)

**Comment by europ** [comment]
It can be fixed by following the instructions in https://github.com/MaartenBaert/ssr/issues/565#issuecomment-518389403

1. open `/etc/gdm/custom.conf` in a text editor as root
2. change the `[deamon]` group to the example below
```
[daemon]
WaylandEnable=false
DefaultSession=gnome-xorg.desktop
```
3. reboot

**Comment by Trospector** [comment]
Do try viewing the recording file in another viewer or browser before trying more complicated things.

I have this strange situation where for one particular recording (.mp4) file, VLC on Lubuntu shows me garbled video (sometimes just a black screen, sometimes flickering black and white rectangles) with good audio. Fortunately I happened to think out about trying to view the file in another viewer (Firefox browser) and that shows both video and audio perfect! Here are the details:

Lubuntu 19.04 Disco
LXQt 0.14.1
recording file: .mp4, 53.6 MiB, about 30 minutes long
SimpleScreenRecorder 0.3.11
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[0000560fe5b1e570] main libvlc: Running vlc with the default interface.
