### ISSUE TITLE
use a prefix or postfix when creating a new file

### ISSUE THREAD

**Issue by jabbalaci** [MaartenBaert/ssr#574]
I have a request: at the moment, we need to specify the name of the output file, e.g. "out.mp4". If I make two videos, there is a chance that the second video overwrites the first one. It would be nice if the program could detect that the specified file exists and it would create a new file with a different name, e.g. "out-2.mp4", then "out-3.mp4", etc. Or, a timestamp could also be added to the filename and the problem is solved.

**Comment by QuImUfu** [comment]
This is already possible via the "separate file per segment" checkbox.

**Comment by jabbalaci** [comment]
Thanks, but it's not the same. The "separate file per segment" option will create a new file when you just even pause the video. I would like the following behavior:

* When just pausing and resuming a video, don't create a new video.
* When I stop a video and save it, then close the video file. If I start recording again, then save the video to a new file.

I used gtk-recordMyDesktop and that software worked like this. I had some other problems with gtk-recordMyDesktop and that's why I started using ssr.

**Comment by QuImUfu** [comment]
You can easily put them back together with a program like Openshot. You can even do it **very** easily and quickly with ffmpeg. ( see: https://trac.ffmpeg.org/wiki/Concatenate )

Although i agree that the behaviour you want would be more intuitive and useful than the current available behaviors.

**Comment by MaartenBaert** [comment]
See #562.
