### ISSUE TITLE
[Feature Request] bash command to start recording

### ISSUE THREAD

**Issue by avikalpg** [MaartenBaert/ssr#575]
I anyway launch the program from the terminal using the command "simplescreenrecorder". It is currently a pain to start recording every time. Even when I need the same configuration, I have to click 3 times of a GUI to start recording again. It will be so much better if I can call the simplescreenrecorder command from the terminal with flags to specify the configuration I need and still get the performance (which ffmpeg or avconv do not provide).

**Comment by MaartenBaert** [comment]
It's already on the todo list, but this requires some changes to how the program works internally.

Note that you can already start recording with the global hotkey even if you aren't at the recording page (assuming the settings are correct - you probably want to enable 'separate file per segment' to get a unique file name for every video). This works even when the window is hidden. You can start the program in hidden form with ```simplescreenrecorder --start-hidden```.

**Comment by avikalpg** [comment]
Thanks Maarten, it helped a lot. I used `simplescreenrecorder --start-hidden` along with `xdotool` in a script to accomplish what I wanted.
