### ISSUE TITLE
File size reported incorrectly

### ISSUE THREAD

**Issue by Ryan8781** [MaartenBaert/ssr#584]
The file size values reported by SSR are not entirely correct. The calculations use powers of 1024, with labels “kB”, “MB” and “GB”. According to [the ISO/IEC 80000 standard](https://en.wikipedia.org/wiki/ISO/IEC_80000), 1 kB should be 1000 B, not 1024 B. If powers of 1024 are used, then the units are kibibytes, mebibytes, gibibytes, etc, denoted “KiB”, “MiB”, “GiB”, etc. See also [the Wikipedia article on binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) and [the UnitsPolicy page on the Ubuntu Wiki](https://wiki.ubuntu.com/UnitsPolicy).

This is also the common behaviour in file managers; Thunar and Nautilus use powers of 1000 to display the file size, with labels such as “kB”, “MB”, etc. It's kind of confusing to see the size differ in SSR and in my file manager.

I believe the code that does this is in [`PageRecord.cpp`](https://github.com/MaartenBaert/ssr/blob/adcf816093f639d21b6834d9a650c3a0fd670b8e/src/GUI/PageRecord.cpp), in the `ReadableSize` function.

One possible solution would be to change the calculations to use powers of 1000 instead of 1024. This is the solution I would recommend, because, at least from my experience, most Linux applications report sizes with the power of 1000, following the ISO/IEC 80000 standard.

Another thing I noticed is that the bit rate is denoted “bps”, “kbps”, “Mbps”, etc. I would also suggest changing “bps” to “bit/s”. According to the same ISO/IEC 80000 standard, and as well to Ubuntu's UnitsPolicy, the symbol for bit should be “bit”, not “b”.

**Comment by MaartenBaert** [comment]
This is one of those cases where the standards say one thing and users end up doing something completely different. There are sound technical reasons for using block sizes that are powers of two. I can change the suffixes if you want, but I don't feel like using block sizes like '1000' and '1000000' that are completely meaningless in a binary architecture.

That being said, apparently it is more common in video encoding to interpret '1 kbps' (or '1 kbit/s' if you want) as '1000 bits per second', and this is also the convention that FFmpeg follows, so I will go with that.
