### ISSUE TITLE
glinject/Hook.cpp is missing 'extern char **environ;'

### ISSUE THREAD

**Issue by yurivict** [MaartenBaert/ssr#586]

**Comment by MaartenBaert** [comment]
This is already done in <unistd.h>. What platform are you compiling on?

**Comment by yurivict** [comment]
FreeBSD.

**Comment by MaartenBaert** [comment]
ElfHacks doesn't support BSD so there is no way this is going to work anyway. You should disable GLInject completely. (`-DWITH_GLINJECT=FALSE`).

**Comment by yurivict** [comment]
Thanks!
