### ISSUE TITLE
compile error on clearlinux

### ISSUE THREAD

**Issue by tuxutku** [MaartenBaert/ssr#587]
uname -a:
Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.13.11-428.native #2 SMP Thu Nov 2 12:15:44 UTC 2017 x86_64 GNU/Linux

[list of installed bundles](https://github.com/MaartenBaert/ssr/files/1464617/list_of_installed_bundles.txt)

[output of the terminal](https://github.com/MaartenBaert/ssr/files/1464616/output.txt)

Error:
In file included from /home/utku/Programlar/ssr/src/AV/Input/GLInjectInput.cpp:20:0:
/home/utku/Programlar/ssr/src/Global.h:339:30: error: ‘AVFrac’ does not name a type; did you mean ‘FFFrac’?
 inline double ToDouble(const AVFrac& f) {
                              ^~~~~~
                              FFFrac
/home/utku/Programlar/ssr/src/Global.h: In function ‘double ToDouble(const int&)’:
/home/utku/Programlar/ssr/src/Global.h:340:20: error: request for member ‘val’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                    ^~~
/home/utku/Programlar/ssr/src/Global.h:340:37: error: request for member ‘num’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                                     ^~~
/home/utku/Programlar/ssr/src/Global.h:340:54: error: request for member ‘den’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                                                      ^~~
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/build.make:157: src/CMakeFiles/simplescreenrecorder.dir/AV/Input/GLInjectInput.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 46%] Built target ssr-glinject32
In file included from /home/utku/Programlar/ssr/src/AV/Input/ALSAInput.cpp:20:0:
/home/utku/Programlar/ssr/src/Global.h:339:30: error: ‘AVFrac’ does not name a type; did you mean ‘FFFrac’?
 inline double ToDouble(const AVFrac& f) {
                              ^~~~~~
                              FFFrac
/home/utku/Programlar/ssr/src/Global.h: In function ‘double ToDouble(const int&)’:
/home/utku/Programlar/ssr/src/Global.h:340:20: error: request for member ‘val’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                    ^~~
/home/utku/Programlar/ssr/src/Global.h:340:37: error: request for member ‘num’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                                     ^~~
/home/utku/Programlar/ssr/src/Global.h:340:54: error: request for member ‘den’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                                                      ^~~
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/build.make:133: src/CMakeFiles/simplescreenrecorder.dir/AV/Input/ALSAInput.cpp.o] Error 1
In file included from /home/utku/Programlar/ssr/src/AV/Input/JACKInput.cpp:20:0:
/home/utku/Programlar/ssr/src/Global.h:339:30: error: ‘AVFrac’ does not name a type; did you mean ‘FFFrac’?
 inline double ToDouble(const AVFrac& f) {
                              ^~~~~~
                              FFFrac
/home/utku/Programlar/ssr/src/Global.h: In function ‘double ToDouble(const int&)’:
/home/utku/Programlar/ssr/src/Global.h:340:20: error: request for member ‘val’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                    ^~~
/home/utku/Programlar/ssr/src/Global.h:340:37: error: request for member ‘num’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                                     ^~~
/home/utku/Programlar/ssr/src/Global.h:340:54: error: request for member ‘den’ in ‘f’, which is of non-class type ‘const int’
  return (double) f.val + (double) f.num / (double) f.den;
                                                      ^~~
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/build.make:181: src/CMakeFiles/simplescreenrecorder.dir/AV/Input/JACKInput.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: src/CMakeFiles/simplescreenrecorder.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by MaartenBaert** [comment]
Are you using FFmpeg or Libav? Neither is listed in your list of installed bundles. Also, which FFmpeg/Libav version are you using?

**Comment by MaartenBaert** [comment]
Actually that function isn't used anywhere anymore, I think I only ever used it in some old compatibility code for ancient libav versions. I've removed it, try compiling again (from the master branch).

**Comment by tuxutku** [comment]
master branch has a diffrent error:
[terminal log](https://github.com/MaartenBaert/ssr/files/1468106/second_log.txt)

/home/utku/Programlar/New Folder/ssr/src/AV/Output/AudioEncoder.cpp: In member function ‘unsigned int AudioEncoder::GetFrameSize()’:
/home/utku/Programlar/New Folder/ssr/src/AV/Output/AudioEncoder.cpp:62:51: error: ‘CODEC_CAP_VARIABLE_FRAME_SIZE’ was not declared in this scope
  return (GetCodecContext()->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)? DEFAULT_FRAME_SAMPLES : GetCodecContext()->frame_size;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/utku/Programlar/New Folder/ssr/src/AV/Output/AudioEncoder.cpp:62:51: note: suggested alternative: ‘AV_CODEC_CAP_VARIABLE_FRAME_SIZE’
  return (GetCodecContext()->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)? DEFAULT_FRAME_SAMPLES : GetCodecContext()->frame_size;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   AV_CODEC_CAP_VARIABLE_FRAME_SIZE
/home/utku/Programlar/New Folder/ssr/src/AV/Output/AudioEncoder.cpp: In static member function ‘static void AudioEncoder::PrepareStream(AVStream*, AVCodecContext*, AVCodec*, AVDictionary**, const std::vector<std::pair<QString, QString> >&, unsigned int, unsigned int, unsigned int)’:
/home/utku/Programlar/New Folder/ssr/src/AV/Output/AudioEncoder.cpp:126:28: error: ‘CODEC_FLAG_QSCALE’ was not declared in this scope
    codec_context->flags |= CODEC_FLAG_QSCALE;
                            ^~~~~~~~~~~~~~~~~
/home/utku/Programlar/New Folder/ssr/src/AV/Output/AudioEncoder.cpp:126:28: note: suggested alternative: ‘AV_CODEC_FLAG_QSCALE’
    codec_context->flags |= CODEC_FLAG_QSCALE;
                            ^~~~~~~~~~~~~~~~~
                            AV_CODEC_FLAG_QSCALE
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/build.make:301: src/CMakeFiles/simplescreenrecorder.dir/AV/Output/AudioEncoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: src/CMakeFiles/simplescreenrecorder.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by MaartenBaert** [comment]
You are using a version of FFmpeg that hasn't been released yet, I can't easily test for that. Can you revert to the latest stable FFmpeg (version 3.4)?

**Comment by tuxutku** [comment]
now i am having errors when linking executables (many undefiened object errors), i don't know how to solve this error so i am trying to build ffmpeg with shared libraries to see if it does something

**Comment by tuxutku** [comment]
successfully build the simple screen recorder after building ffmpeg with shared libraries, but i have a new error:

utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ simplescreenrecorder --logfile
Incompatible processor. This Qt build requires the following features:
    aes
Aborted. Incompatible processor: missing feature 0x2000000 - aes.
Aborted (core dumped)

**Comment by tuxutku** [comment]
my processor does not have aes [https://ark.intel.com/tr/products/50178/Intel-Core-i3-380M-Processor-3M-Cache-2_53-GHz](https://ark.intel.com/tr/products/50178/Intel-Core-i3-380M-Processor-3M-Cache-2_53-GHz) looks like i have to compile qt from source

**Comment by tuxutku** [comment]
I couldn't compiled qt wıth my computer but build was succesfull so i am closing this issue now
