### ISSUE TITLE
Please have a cmake option enabling/disabling ALSA

### ISSUE THREAD

**Issue by yurivict** [MaartenBaert/ssr#608]
Now ALSA just appears in the combobox. BSD systems generally don't have ALSA.

**Comment by MaartenBaert** [comment]
Done.

**Comment by MaartenBaert** [comment]
Note that I also had to disable sound notifications when compiling without ALSA, so I have removed the GUI controls for this as well.

**Comment by yurivict** [comment]
> Note that I also had to disable sound notifications when compiling without ALSA

Oh no, sound notifications shouldn't depend on ALSA. You should consider using something more universal, like OpenAL for for sound. Depending on ALSA in any features makes program linux-only, because ALSA in linux-only.

**Comment by MaartenBaert** [comment]
I'd rather implement OSS support (or some other API) for BSD. I don't want to add yet another abstraction layer. My experience with those is that they introduce new bugs and don't provide me with enough low-level access to do what I want. That's the reason why I already implemented ALSA, PulseAudio and JACK separately.

The main roadblock for me is that I would have to do all development in a VM, and I have zero experience with *BSD.

**Comment by yurivict** [comment]
> OSS support

Yes, do it!

I personally also like Jack, a professional-grade audio server.

Then, there is the PulseAudio, a so-so thingie that is nevertheless ubiquitous.

**Comment by OlegTiurin** [comment]
Hi, MaartenBaert,
what about OSS support on linux for simplescreenrecorder?

**Comment by MaartenBaert** [comment]
I can't test OSS and AFAIK it isn't really used anymore on Linux, but if you want to implement it (e.g. for BSD) then that's fine.

**Comment by OlegTiurin** [comment]
My problem is that my audio card does not have original driver for linux and can work with oss only.
So, if I disable in cmake ALSA, this will compile with OSS support automatically?

**Comment by MaartenBaert** [comment]
There is no OSS support except for the ALSA plugin. I can't test with OSS since it doesn't work on my system, so I can't develop it. You should be able to compile with ALSA even if your system uses OSS.

**Comment by OlegTiurin** [comment]
OK, I'll try. Thank you for you help, have a good day!
