### ISSUE TITLE
Still installs bin/ssr-glinject when -DWITH_GLINJECT:BOOL=OFF is specified

### ISSUE THREAD

**Issue by yurivict** [MaartenBaert/ssr#609]
This cmake option disables the shared library```lib/libssr-glinject.so```, but these files are still being installed:
```
bin/ssr-glinject
man/man1/ssr-glinject.1.gz
```

**Comment by MaartenBaert** [comment]
Now fixed with new option `WITH_OPENGL_RECORDING`.

**Comment by yurivict** [comment]
Thanks!
