### ISSUE TITLE
Error with qt 5.10

### ISSUE THREAD

**Issue by vdemir** [MaartenBaert/ssr#612]
[![image](https://i.hizliresim.com/6JRzEk.png)](https://hizliresim.com/6JRzEk)

**Comment by MaartenBaert** [comment]
I'm guessing that there's something seriously wrong with your DPI settings. Qt5 apparently thinks that your screen is very small, so it is making all buttons extremely big. Do other Qt5 apps have the same problem?

**Comment by vdemir** [comment]
qt returned to normal after all 5.10 package updates. Thank you.
