### ISSUE TITLE
registration name while capturing

### ISSUE THREAD

**Issue by vdemir** [MaartenBaert/ssr#616]
We want to enter the current registration name while capturing from the video screen. For your information.

**Comment by ZoeyGlobe** [comment]
Perhaps they're recommending you add the option to change the OpenGL capture channel name whilst recording @MaartenBaert

**Comment by vdemir** [comment]
I apologize for not explaining better. For example, a video name can be given. But when we shoot multiple videos, we can separate the videos with pause. And the name is automatically given. Can we update the video name actively when pause-start?

**Comment by MaartenBaert** [comment]
I still don't understand what exactly you want to do. You can always save the recording, go back to the output page, change the file name, and start a new recording. You can also use the default names (with timestamp) and just rename the video file in your file manager.

**Comment by vdemir** [comment]
admin I think I have a special situation. I capture the video series from a live stream and the pause key is enough to separate the videos. Then I have to go back and change the names of the recorded videos. And as a result dozens of videos accumulate and it is not easy to change their individual names. What I want is to be able to change the name while the video is being recorded.

**Comment by QuImUfu** [comment]
to capture a livestream use youtube-dl or streamlink. They are faster, less resource intensive, require less manual interaction and support all major streaming sites.

**Comment by MaartenBaert** [comment]
@vdemir I think the number of people who use SSR this way is pretty small, so I can't justify giving up GUI space for a feature like this. It just makes the interface more confusing, especially because what you want to do is already perfectly possible with a regular file manager.
