### ISSUE TITLE
Timed recording

### ISSUE THREAD

**Issue by R7914T** [MaartenBaert/ssr#617]
Can you please suggest a way to stop a screen recording by stating a time when it is to be stopped? I am looking for help to stop a recording when I am not able to be with my computer. I am using ubuntu 16.04. I am hoping there is a command line or gui  that can cause the recorder to stop but to safely write to disk any buffered frames still to be written.

**Comment by MaartenBaert** [comment]
Already on the todo list, this is probably the #1 feature request by now.

**Comment by xdya** [comment]
Need timed recording too (eg. a timer to restrict the recording duration). This feature seems not yet provided?
