### ISSUE TITLE
Use a modern supported fdo system tray protocol: statusnotifiericons

### ISSUE THREAD

**Issue by franksouza183** [MaartenBaert/ssr#624]
Quote the conversation seems more appropriate than retell it, so here goes:

From https://bugs.kde.org/show_bug.cgi?id=389990 :

> Frank Souza 2018-02-07 07:27:47 UTC
> 
> Sorry if I missed the related product.
> 
> I already noticed this in earlier versions of KDE. There is a certain loss of quality in some icons when rendered on system tray regardless its size, as you can see here: https://i.imgur.com/Zhm8H3p.png. Look's like some kind of antialising or scaling is being applied. That is the icon of Simple Screen Recorder clearly modified just for tests. In this example, the graphic is rendered with 22 x 22px, the icon has exactly the same dimensions and also, as you can see, has only squares, so no antialiasing should be visible.
> 
> Sorry for the bad english

> David Edmundson 2018-02-07 12:08:15 UTC
> And that icon is using xemded?
> 
> You can easily find out by running killall xembedsniproxy and see if the icon vanishes.
> 
> If so, please file a bug with that application to use a modern supported fdo  system tray protocol: statusnotifiericons

> Frank Souza 2018-02-07 18:09:13 UTC
> 
> Yes, this one uses xembed, but I do not think a proper solution ask all developers for these programs (including some abandoned but still heavily used). Why not fill out a bug report for the xembed team and make them render things as they should? These icons are displayed correctly in other environments, such as xfce, cinamon, gnome-shell.

> David Edmundson 2018-02-07 18:51:25 UTC
> > Why not fill out a bug report for the xembed team and make them render things as they should?
> 
> You have, that team is me. I didn't say I would close this.
> 
> However, please file a bug with that application to use a modern supported fdo  system tray protocol: statusnotifiericons

Thank you for this amazing tool

**Comment by minlexx** [comment]
Qt5 Applications with KDE Plasma 5 installed use SNI's automatically.
Qt4 apps require sni-qt to be installed

**Comment by franksouza183** [comment]
@minlexx, installing sni-qt made it works, thanks. This can be a workaround to SSR, but not for other programs running in root mode, for example. Anyway thanks!

**Comment by MaartenBaert** [comment]
SSR is just using the default system tray API provided by Qt. So the correct solution is to fix this by installing the necessary Qt plugins, not by changing SSR.
