### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by shoober420** [MaartenBaert/ssr#625]
When trying to compile on Arch Linux 64bit, I get the following error.

[ 27%] Building CXX object src/CMakeFiles/simplescreenrecorder.dir/AV/Output/AudioEncoder.cpp.o
/home/abc/simplescreenrecorder-git/src/ssr/src/AV/Output/AudioEncoder.cpp: In member function ‘unsigned int AudioEncoder::GetFrameSize()’:
/home/abc/simplescreenrecorder-git/src/ssr/src/AV/Output/AudioEncoder.cpp:61:51: error: ‘CODEC_CAP_VARIABLE_FRAME_SIZE’ was not declared in this scope
  return (GetCodecContext()->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)? DEFAULT_FRAME_SAMPLES : GetCodecContext()->frame_size;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/abc/simplescreenrecorder-git/src/ssr/src/AV/Output/AudioEncoder.cpp:61:51: note: suggested alternative: ‘AV_CODEC_CAP_VARIABLE_FRAME_SIZE’
  return (GetCodecContext()->codec->capabilities & CODEC_CAP_VARIABLE_FRAME_SIZE)? DEFAULT_FRAME_SAMPLES : GetCodecContext()->frame_size;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   AV_CODEC_CAP_VARIABLE_FRAME_SIZE
/home/abc/simplescreenrecorder-git/src/ssr/src/AV/Output/AudioEncoder.cpp: In static member function ‘static void AudioEncoder::PrepareStream(AVStream*, AVCodecContext*, AVCodec*, AVDictionary**, const std::vector<std::pair<QString, QString> >&, unsigned int, unsigned int, unsigned int)’:
/home/abc/simplescreenrecorder-git/src/ssr/src/AV/Output/AudioEncoder.cpp:125:28: error: ‘CODEC_FLAG_QSCALE’ was not declared in this scope
    codec_context->flags |= CODEC_FLAG_QSCALE;
                            ^~~~~~~~~~~~~~~~~
/home/abc/simplescreenrecorder-git/src/ssr/src/AV/Output/AudioEncoder.cpp:125:28: note: suggested alternative: ‘AV_CODEC_FLAG_QSCALE’
    codec_context->flags |= CODEC_FLAG_QSCALE;
                            ^~~~~~~~~~~~~~~~~
                            AV_CODEC_FLAG_QSCALE
make[2]: *** [src/CMakeFiles/simplescreenrecorder.dir/build.make:238: src/CMakeFiles/simplescreenrecorder.dir/AV/Output/AudioEncoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: src/CMakeFiles/simplescreenrecorder.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
[%]

**Comment by juozaspo** [comment]
What is your compilation command line, did you run ./simple-build-and-install script first?
You might need a package that includes libavcodec/avcodec.h, as variables such as CODEC_CAP_VARIABLE_FRAME_SIZE are defined there.

**Comment by shoober420** [comment]
I figured it out. It was because I was using the git development versions of ffmpeg.
