### ISSUE TITLE
SSR detects wrong screen resolution when I increase display scale on KDE Plasma X11

### ISSUE THREAD

**Issue by glaubersm** [MaartenBaert/ssr#629]
Hi
I use SSR on Arch Linux running KDE Plasma 5.12.1 under X11.
In KDE settings is configured 1080p as my screen resolution and 1.2 as display scale, but SSR shows 1600x900. See screenshot.
When I set 1 as display scale, SSR shows the correct resolution (1080p).

![screenshot_20180213_192743](https://user-images.githubusercontent.com/15967631/36175328-2d38059a-10f6-11e8-80f5-38924488cbc7.png)

**Comment by MaartenBaert** [comment]
Interesting. I'm using the standard Qt functions to detect screen layout (QDesktopWidget). What happens when you use the 'record a fixed rectangle' option to enter a rectangle the size of your screen? Does the recording frame that gets displayed have the correct size? Note, the code for drawing the recording frame has changed recently, so it would be best to recompile SSR from source if you want to test this.

**Comment by vdemir** [comment]
I have a similar problem. The resolution of videos I capture from the screen drops to 480p when uploaded with YouTube settings. I could not find the solution.

**Comment by MaartenBaert** [comment]
I know that this is probably not what you're looking for, but have you tried increasing your DPI settings (to make the text in applications bigger) instead of using screen scaling? Because I don't think there's an easy solution for this problem in SSR.

**Comment by Aetf** [comment]
Actually the issue also present when choosing "select rectangle". The pixel numbers detected after selecting the rectangle are divided by the desktop scale factor. I have the scale factor set to 2, so I have to manually multiply 4 numbers (left, top, width, height) by 2 to get the correct area recorded.

**Comment by ValdikSS** [comment]
@MaartenBaert, please check this page: http://doc.qt.io/qt-5/highdpi.html
I think you need to set Qt::AA_Use96Dpi in rectangle selection code.

Temporary workaround for users is to run SSR with the following command:
`QT_SCREEN_SCALE_FACTORS= simplescreenrecorder`

**Comment by carlonluca** [comment]
I think the patch I proposed in #668 fixes this.

**Comment by es20490446e** [comment]
Same on Deepin:
https://youtu.be/Ox8CLfHczVU

**Comment by rkfg** [comment]
I built the latest version from master and it seems to be fixed for me. Both full screen resolution and rectangle selection work correctly.

**Comment by es20490446e** [comment]
I confirm this is fixed in master.
