### ISSUE TITLE
Feature request: USB microphone

### ISSUE THREAD

**Issue by huubvanniekerk** [MaartenBaert/ssr#630]
After a lot of struggling with increasing static noise on my mini-jack input, I finally found the advise to try a USB microphone. This does work great, but only with Audacity (in my case). Trying to select the USB microphone in simplescreenrecorder leads to nothing. Using Audacity and ssr simultaneously works but takes a lot of extra work. Hence the request to add USB microphone input for audio.

Thanks.

**Comment by MaartenBaert** [comment]
I use a USB microphone with SSR all the time and it works fine. In fact I don't think I've used any other microphone in the last 4 years. You must be doing something wrong with the settings.

**Comment by huubvanniekerk** [comment]
As it turns out, I was. So request withdrawn.

**Comment by StripedMonkey** [comment]
close the issue?
