### ISSUE TITLE
Fails to build with WITH_GLINJECT=OFF: undefined reference to `PageInput::OnGLInjectDialog()'

### ISSUE THREAD

**Issue by yurivict** [MaartenBaert/ssr#636]
```
src/CMakeFiles/simplescreenrecorder.dir/simplescreenrecorder_autogen/mocs_compilation.cpp.o: In function `PageInput::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
src/simplescreenrecorder_autogen/mocs_compilation.cpp:(.text+0xd66): undefined reference to `PageInput::OnGLInjectDialog()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Version 0.3.10

**Comment by MaartenBaert** [comment]
Tested with both Qt 4.8.7 and 5.10.1, but I don't get this error. Which version of Qt and CMake are you using?

**Comment by yurivict** [comment]
cmake-3.10.2
qt-4.8.7

**Comment by yurivict** [comment]
Building with ```-DWITH_QT5=ON -DWITH_GLINJECT=OFF -DWITH_OPENGL_RECORDING=OFF```.

**Comment by MaartenBaert** [comment]
Exactly the same as me then. Which commands did you use to compile SSR?

**Comment by yurivict** [comment]
All configure arguments:
```-DWITH_JACK:BOOL=false -DWITH_PULSEAUDIO:BOOL=false -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector"  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector"  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector"  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DWITH_QT5:BOOL=ON -DWITH_GLINJECT:BOOL=OFF -DWITH_OPENGL_RECORDING:BOOL=OFF -GNinja```
