### ISSUE TITLE
Can't build with Qt < 5.9

### ISSUE THREAD

**Issue by Vascom** [MaartenBaert/ssr#638]
As I see in https://github.com/MaartenBaert/ssr/commit/9625ee4461a3a49c8910c81aaf4cd8c15642d8e8#diff-5c9e63f122b1e4ef80b24b06cbcaa712 commit you added isCompositingManagerRunning and it not available for Qt less than 5.9. So I can't build ssr for RHEL/CentOS 7 because it has only 5.6.2.
It is new requirement or can be fixed?

**Comment by Vascom** [comment]
I found answer in simple-build-and-install script.
Can you add required versions of dependencies to README?

**Comment by MaartenBaert** [comment]
Technically I could add support for this, but I would recommend compiling with Qt4 instead. Early versions of Qt5 have other issues as well (e.g. for a long time the system tray icon didn't work).

**Comment by Vascom** [comment]
I am already build it with Qt 4 in rpmfusion repo.
