### ISSUE TITLE
Request: Include --version in ssr manual, not only in usage info for ssr

### ISSUE THREAD

**Issue by juozaspo** [MaartenBaert/ssr#643]
By adding --version option to ssr command line (Commit 65edfeb03bf903e31f0fdc14ab2567753cde41e8), the manual files for ssr need to be updated too. Now the description for --version command line option is not included in manual, while ssr usage prompt includes it.

**Comment by trebmuh** [comment]
Good catch @juozaspo .

**Comment by juozaspo** [comment]
@trebmuh Neat; Only found a typo in commit name :grin:

**Comment by juozaspo** [comment]
` Update manage fix #643 ` should be `manpage` or `man page` instead of `manage` or something similar in commit name above, not PR name.
If you have command line git you can rename commit by amending it in your local copy, then reupload by doing force update:
```
git commit --amend
git push -f
```
where `-f` is shortcut for `--force`
If you're using Linux and have `man` utility installed (on debian/ubuntu it comes from man-db package), you can get more details about commands above by running commands below:
```
man git-commit
man git-push
```

**Comment by trebmuh** [comment]
Honestly, I'm not going to spend time changing the commit name for a missing letter which is quite obvious when looking at what the commit is actually changing.
