### ISSUE TITLE
Request: Stop OpenGL recording if application is closed or crashed

### ISSUE THREAD

**Issue by juozaspo** [MaartenBaert/ssr#653]
When recording an OpenGL program (e.g. game) if it crash/closes/etc while recording ssr should automatically stop the recording w/o trying to grab more frames from already gone application. It's annoying if you need to stop it manually, as it still would render the same last grabbed frame in the video output.

**Comment by MaartenBaert** [comment]
This is not as easy as you think. Many games have multiple processes and open multiple OpenGL windows. The risk is too high that the recording will be stopped too soon and the entire video will be lost. Just use the hotkey to stop the recording when you want it to stop.
