### ISSUE TITLE
recording vhs playing on the desktop with ssr

### ISSUE THREAD

**Issue by Rodartist** [MaartenBaert/ssr#655]
using av to usb 2.0
then playing the streams (audio and video) seperately and since they are streaming thought that ssr could capture the streams together but running into something beyond where they won't record how it actually is streamed on the desktop

its a long shot but i thought this could be possible though it maybe be because im using aplay to playback the audio stream?

so it wont record in sync..
`$ arecord - | aplay -
Playing raw data 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
Recording WAVE '-' : Unsigned 8 bit, Rate 8000 Hz, Mono
underrun!!! (at least 129.769 ms long)`

does give an underrun warning, but when its streaming its ok...
so maybe this computer is too slow???
its a quad core though.

it would be easier to record this vhs through ssr without having to use audacity then edit the sound with the video.

**Comment by Rodartist** [comment]
i do think this may be an issue with ssr, but luckily on my end the solution is the command line https://askubuntu.com/questions/682144/capturing-only-desktop-audio-with-ffmpeg

`ffmpeg -f x11grab -video_size 1360x768 -framerate 30 -i :0.0 -f pulse -i default -preset ultrafast -crf 18 -pix_fmt yuv420p out.mkv`

cheers!

**Comment by MaartenBaert** [comment]
I still have no idea what you were trying to do or how it was related to SSR. But if you think you've fixed it, good for you :).
