### ISSUE TITLE
Black video

### ISSUE THREAD

**Issue by ItsWatterson** [MaartenBaert/ssr#664]
Hi,

First, sorry for the wrong words in English ...

So I've always used SimpleScreenRecorder, but since the last update on my system the video is black.

Ubuntu Linux
Distribution Version: 17.10

I have no idea what the problem might be ...

**Comment by Username-with-no-name** [comment]
Maybe Update again?

sudo apt-get update

**Comment by ItsWatterson** [comment]
No, i try this...
The problem continues..

**Comment by MaartenBaert** [comment]
Duplicate of #431. Switch to a non-Wayland session as described here:
http://www.maartenbaert.be/simplescreenrecorder/troubleshooting/#the-recording-is-completely-black-except-for-the-cursor

**Comment by ItsWatterson** [comment]
It worked! Thanks a lot!
