### ISSUE TITLE
Can't open PCM device!

### ISSUE THREAD

**Issue by myname99** [MaartenBaert/ssr#667]
Hello, first of all thank you for creating this little but very useful program. It worked well on my desktop PC, but on acer laptop (Ubuntu 18 fresh installed) I get this error: 

```
 [SimpleSynth::Init] Error: Can't open PCM device!
[PageRecord::OnUpdateSoundNotifications] Error: Something went wrong while creating the synth.
```

Anyway I manage to record video, but keyboard shortcut seems to not work, also no sound notifications. As the laptop is much slower than the desktop it's not clear if the problems are due to hardware or software issues.
Anyway, something is going wrong as the tray icon has a red x across the button.
Any help is appreciated.

**Comment by MaartenBaert** [comment]
There appears to be something wrong with your audio setup, since the default playback device isn't working. The easiest workaround is to disable sound notifications, this will avoid the error.

**Comment by myname99** [comment]
Thank you
