### ISSUE TITLE
CPU Usage with PulseAudio+pacat goes through the roof

### ISSUE THREAD

**Issue by Veek** [MaartenBaert/ssr#673]
Hi I was using a slightly older version of Debian Stretch and all was well - I could pacat+NoiseProfile to simplescreenrecorder and it worked nicely. Then I upgraded to latest Stretch-ISO and I've been having problems.

If I connect Mic-->Loopback--->Virtual1 it works nicely with low cpu usage **but I do NOT have noise.profile**

When I pacat-->sox+noise.profile-->'Virtual1'NULLDevice, CPU usage goes through the roof 70-80% and I get messages about too many audio packets in SSR:

```
alsa_card_id=`pactl list modules|egrep -i module-alsa-card -B 1|egrep -o [0-9]+`
pactl unload-module $alsa_card_id

pactl load-module module-alsa-card device_id="0" name="pci-0000_00_1b.0" card_name="alsa_card.pci-0000_00_1b.0" namereg_fail=false tsched=no fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes card_properties="module-udev-detect.discovered=1" fragments=1 fragment_size=15

export input=alsa_input.pci-0000_00_1b.0.analog-stereo
export output=Virtual1
pacat -r -d $input --latency=1msec | sox -b 16 -e signed -c 2 -r 44100 -t raw - -b 16 -e signed -c 2 -r 44100 -t raw - noisered noise.prof 0.2 | pacat -p -d $output --latency=1msec

```
This used to work in my previous Stretch install so I do not understand what has changed (without tsched=no etc)?

**Comment by trebmuh** [comment]
@Veek where does SSR come from in your case, debian repository package? self-compiled? other?

**Comment by Veek** [comment]
it's from debian distro - default install - nothing special.
I did some more checking and it looks like pulseaudio's the culprit.
If I DON'T RUN SSR I still get very high CPU Utilization
```
  603 pulse      9 -11  439016  22072   8628 S  34.6  0.6  26:45.61 pulseaudio        
 2869 root      20   0  152116   3516   2912 R  10.3  0.1   1:00.35 pacat             
 2870 root      20   0   27536   3188   2768 S   8.6  0.1   0:50.61 sox  
```

(with just the pcat+sox+pcat)

**Comment by trebmuh** [comment]
You'd be better to report against pulseaudio/debian, rather than here then.
Please close.
