### ISSUE TITLE
GetDeb links

### ISSUE THREAD

**Issue by vomae** [MaartenBaert/ssr#674]
**GetDeb** is closed and this time there is little hope to see it back soon. I suggest Maarten Baert to change the links to the software sources he offers on his website (e.g., "Ubuntu, Linux Mint, ..." under "_Download_" in [http://www.maartenbaert.be/simplescreenrecorder/#download](http://www.maartenbaert.be/simplescreenrecorder/#download)).

**Comment by MaartenBaert** [comment]
Done. It's rather redundant anyway since the package is now in the official repos.
