### ISSUE TITLE
"Dinamically choosen entire screen" recording mode

### ISSUE THREAD

**Issue by Ashark** [MaartenBaert/ssr#676]
It would be good to create another recording mode called "Dinamically choosen entire screen". In this mode ssr should be able to change recorded screen with some condition.
Now there is a mode called "Follow cursor", but it is not working well for my needs. I am recording my workflow from several monitors. When I am moving mouse or want to circle some area or draw something with a mouse, then the recording area is "following" it and it is very inconvinient to view, because it shakes like crazy. Also, the viewer is watching the border between screens almost all time (which I do not want to happen).

This new "Dinamically choosen entire screen" mode is like a mix of two modes: record entire screen and follow cursor. I want this mode to switch to screen to which mouse was moved.

In OBS you are able to make several scenes (for example scene_screen1 and scene_screen2) and switch dinamically between them using shortcuts or just using selector in obs gui. While shortcuts gives you more control of when and to what scene you want to switch, it is inconvinient for me, because I cannot concentrate on my workflow (or when I am concentrated, I always forgive to switch scenes). But switching recorded screens with shortcuts is still a good option to have.

As of transitions, I am ok with just jump cuts, but it would be more beautiful with "slide effect" or "fade effect".

Also there is such a thing with different resolutions on different screens. For handling this I think there could be options such as stretch and centralize.

**Comment by StripedMonkey** [comment]
The difficulty with this "mode" is that most containers have fixed resolutions. If you decided to switch resolutions then things change size and shape, leaving basically black bars on nonstandard sized monitors which is even less ideal.

**Comment by Ashark** [comment]
I am not saying to change resolution of recording file. I do not think it is even possible. I just mentioned that for handling switching recorded screen with another resolution there could be options to scale it or to leave it recording with black bars.
And personally for my case, I have three monitors with the same resolution, so I do not need such scaling.

**Comment by MaartenBaert** [comment]
Added to master branch. I haven't done a lot of testing but it works fine for me, even with two different resolutions. SSR still doesn't handle resolution changes after the recording has started though, so you should set the correct resolution(s) before starting. Also, like with OpenGL recording, SSR will use the initial resolution of the video stream as the output resolution of the video file when scaling is not used, so if you have two screens with different resolutions it's a good idea to enable scaling in SSR to fix the output resolution to a known value.

**Comment by Ashark** [comment]
Thanks, really cool.
But now it only works with two monitors. I have three monitors, and in a preview I can see that ssr normally switches to left and to right monitor. But when mouse is in the middle monitor, ssr preview only shows mouse cursor itself on the black background.

**Comment by MaartenBaert** [comment]
Ok. If you ever see the problem again, can you please post the output of the `xrandr` command? That way I can see your exact screen configuration.

**Comment by Ashark** [comment]
I do not know if it should be considered as bug, but ssr does not switch recording to screen, that was added after starting recording. I mean such scanario:
1) you have two monitors and start recording in follow mouse and entire screen mode.
2) you pause recording
3) you connect and enable a third monitor
4) you continue recording
and then ssr normally switches captured screen when mouse is on one of the previous two monitors, but do not switch to newly added third monitor when mouse goes there.

I consider such behavior as not bug, but a feature. So I can place ssr preview window to the third monitor and it won't be captured accidentally.
So, no actions required. I just wanted to let you know and maybe share this lifehack with others.

**Comment by Ashark** [comment]
Unfortunately, black background in middle monitor is still happening.
I have removed nvidia gpu, disabled intel igpu in bios, and the only one gpu is my amd RX580.
I have tried to connect three monitors to it in different variations: via hdmi, dp and dvi. And independently of interfaces used for monitors, in ssr preview I can see that middle monitor only has a mouse cursor on black background, but nothing else. See screenshot:
![ssr black bg middle screen](https://user-images.githubusercontent.com/22634975/48897329-d1418700-ee5a-11e8-8846-c476e476e82c.png)
Reproducible always.
<details>
  <summary>Here is my xrandr configuration (click to expand)</summary>

```
$ xrandr
Screen 0: minimum 320 x 200, current 5760 x 1080, maximum 16384 x 16384
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
HDMI-A-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 476mm x 267mm
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
HDMI-A-1 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 476mm x 267mm
   1920x1080     60.00*+  50.00    59.94  
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DVI-D-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 476mm x 267mm
   1920x1080     60.00 +  50.00*   59.94  
   1680x1050     60.00  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      60.00  
   1280x800      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08
```
</details>

**Comment by MaartenBaert** [comment]
Should be fixed now, can you try it again? It depends on the order of the monitors, for you they appear in the order 312 rather than 123 which is why I couldn't reproduce this.
