### ISSUE TITLE
access built-in webcam on my surface pro 4

### ISSUE THREAD

**Issue by phobos6995** [MaartenBaert/ssr#680]
Whenever I try to access the front (or rear) camera for an overlay on my surface pro 4, I get the error message below:

System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Captura.Webcam.CaptureWebcam.RenderGraph()
   at Captura.Webcam.CaptureWebcam.StartPreview()
   at Captura.WebcamControl.ShowOnMainWindow(Window MainWindow)
   at Captura.Models.WebCamProvider.set_SelectedCam(IWebcamItem value)

Thank you in advance!

**Comment by MaartenBaert** [comment]
How is this in any way related to SSR?

**Comment by phobos6995** [comment]
My apologies if I posted in the wrong location (?)  This is my first time posting to github.  I can't seem to get your program (Captura) and my computer (surface pro 4) to interact nicely.  Any suggestions?  I also have no idea what ssr (soviet socialist republic?) is, but thank you in advance for any insights you might have.  Again, if I posted in the wrong place, please accept my apologies, I'm new here.

**Comment by trebmuh** [comment]
You seems to be not in the right place. SSR (Simple Screen Recorder) is another video capture software. The forge for captura [is here](https://github.com/MathewSachin/Captura).
