### ISSUE TITLE
Problem building translations

### ISSUE THREAD

**Issue by Vascom** [MaartenBaert/ssr#694]
In src/translations/CMakeLists.txt you have `find_program(LRELEASE lrelease)`
But in some cases it must be `lrelease-qt5` (in Fedora)  or `lrelease-qt4` (in CentOS).

So please correct this to depend on used Qt version.

**Comment by MaartenBaert** [comment]
This should be fixed now. CMake will now search for the qt4/qt5 version first and fall back to plain 'lrelease' if that fails.

**Comment by Vascom** [comment]
Thanks.
