### ISSUE TITLE
Black rectangle in the upper right corner

### ISSUE THREAD

**Issue by arfaWong** [MaartenBaert/ssr#698]
I have two 4k screens. One works fine, but the other one has a black rectangle in the upper right corner when recording.

I'm using Ubuntu Mate 18.04.2 LTS

![screenshot at 2019-02-23 09-22-34](https://user-images.githubusercontent.com/8801749/53279692-bfb79600-374d-11e9-8cc9-9cf117ab9732.png)

**Comment by MaartenBaert** [comment]
Are you using the latest SSR from the master branch? The code related to this has recently been changed to deal with high-dpi displays like yours.
