### ISSUE TITLE
Automatically save when stopping recording in headless mode

### ISSUE THREAD

**Issue by juneyon** [MaartenBaert/ssr#702]
In headless mode, i.e. `simplescreenrecorder --start-hidden`, there doesn't seem to be a way to save the file. I can mitigate this by exiting the process, which will auto-save the file, but then the process needs to be rerun again each time you want to listen for the hotkey.

**Comment by MaartenBaert** [comment]
You can enable 'separate file per segment' which does pretty much what you want.

**Comment by hahaluckyme** [comment]
Thanks! That's perfect and does exactly what I want. Feel free to close this!

**Comment by MaartenBaert** [comment]
There are now also some commands that can be sent over stdin, see https://github.com/MaartenBaert/ssr/pull/749.
