### ISSUE TITLE
Scheduled start

### ISSUE THREAD

**Issue by johnbrox** [MaartenBaert/ssr#709]
Hi Maarten
Thank you!  
Is there a quick hack to start ssr recording at a set time, or after x mins?  I've tried combinations of '(sleep x ; echo R)' | ssr --start-hidden' but  to no avail - it really does seem to want a keystroke.  Only there's a webinar I'd like to see which starts at 4am...
Best,
John

**Comment by MaartenBaert** [comment]
This is on the todo list but hasn't been implemented yet.

**Comment by MaartenBaert** [comment]
This is now available in the master branch, see https://github.com/MaartenBaert/ssr/pull/749.
