### ISSUE TITLE
matlab can't be installed on Arch Linux

### ISSUE THREAD

**Issue by callmelord** [MaartenBaert/ssr#712]
System: Arch Linux
Step:
[cp@archlinux ~]$ sudo umount /mnt/iso
[cp@archlinux ~]$ sudo mount -t auto -o loop R2018a_glnxa64_dvd1.iso
/mnt/iso
mount: /mnt/iso: WARNING: device write-protected, mounted read-only.
[cp@archlinux ~]$ sudo chmod 755 /mnt
[cp@archlinux ~]$ cd /mnt/iso
[cp@archlinux iso]$ ls
activate.ini  install                licenses        ui
archives      installer_input.txt    patents.txt     version.txt
bin           install_guide.pdf      readme.txt
etc           java                   sys
help          license_agreement.txt  trademarks.txt
[cp@archlinux iso]$ sudo ./install
Preparing installation files ...
Installing ...
Finished
Problem:No gui installation interface,The software can't be installed

**Comment by MaartenBaert** [comment]
How is this related to SSR? ;)

**Comment by callmelord** [comment]
> How is this related to SSR? ;)

Have nothing to do with SSR, I just have a problem with matlab.

**Comment by MaartenBaert** [comment]
Uhm, then maybe contact their customer support instead of me ...
