### ISSUE TITLE
Option to skip the intro screen

### ISSUE THREAD

**Issue by madduck** [MaartenBaert/ssr#720]
Hello Maarten,

First off, thank you for this awesome piece of software. It does exactly what I need, and so well, that I end up recording more screencasts than ever before, including times when they are totally overkill. :)

I have a couple of ideas that I think could make ssr even better, and I'd love it if you could entertain them. I'll file separate issues about each.

First, I wonder if you'd be open to the idea of having an option to skip the intro screen. I've read it once, and now I just click "Continue" right away, which is an extra click I'd love to be able to avoid.

Thank you!

**Comment by MaartenBaert** [comment]
Done.

**Comment by trebmuh** [comment]
Nice :+1:
