### ISSUE TITLE
Rectangle selection invalid with higher DPI settings aka ignoring QT_SCREEN_SCALE_FACTORS

### ISSUE THREAD

**Issue by jboero** [MaartenBaert/ssr#725]
I use a 4k screen and I see quite a few QT apps (including Gwenview) ignoring screen DPI settings.  This is typically indicated by the environment variable QT_SCREEN_SCALE_FACTORS

In my case: QT_SCREEN_SCALE_FACTORS=DVI-D-0=1.5;HDMI-0=1.5;DP-0=1.5;DP-1=1.5;DVI-D-1=1.5;

This results in invalid selection rectangles within the app, which can be resolved with a manual workaround of unsetting QT_SCREEN_SCALE_FACTORS in the shell running simplescreenrecorder.  It would be nice to take QT_SCREEN_SCALE_FACTORS into account or maybe just unset it at startup.

Thanks
John

**Comment by MaartenBaert** [comment]
This should have been fixed already, are you using the latest version from the master branch?

**Comment by jboero** [comment]
Latest in Fedora 30.  I just reproduced it now to verify. v3.11

Name         : simplescreenrecorder
Version      : 0.3.11
Release      : 7.fc30
Architecture : x86_64
Size         : 3.7 M
Source       : simplescreenrecorder-0.3.11-7.fc30.src.rpm
Repository   : @System
From repo    : rpmfusion-free
Summary      : Simple Screen Recorder is a screen recorder for Linux
URL          : http://www.maartenbaert.be/simplescreenrecorder/
License      : GPLv3
Description  : It is a screen recorder for Linux.
             : Despite the name, this program is actually quite complex.
             : It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC



Thanks!

**Comment by MaartenBaert** [comment]
I haven't released the fix yet, it's only on this repository. I really should do a release but I haven't had enough time yet to do proper testing. Can you try to compile from source?

**Comment by mstawick** [comment]
For what's it worth, I've built master and I'm getting:

```
[X11Input::UpdateScreenConfiguration] Error: Invalid screen bounding box!
    x1 = 0, y1 = 0, x2 = 10560, y2 = 2160
[PageRecord::StartInput] Error: Something went wrong during initialization.
```

I have 3 screens, two identical hidpi (3840x2160 native) and one older with lower res (2880x1800, scaled up). 10560 is total width. Doesn't matter if I choose one of the screens or a rectangle.

Latest release works fine with `$ QT_SCREEN_SCALE_FACTORS="" simplescreenrecorder`

**Comment by MaartenBaert** [comment]
You are exceeding the maximum screen resolution of 10000x10000 pixels. However this restriction is artificial (mainly to avoid excessive memory usage). I will raise the limit.

**Comment by MaartenBaert** [comment]
The limit is now 20000x20000. This is about the highest I can go without risking overflow in code that uses 32-bit integers.

**Comment by mstawick** [comment]
I've tested and it works perfectly fine on my machine. Thanks!
