### ISSUE TITLE
Possible to configure a different (newer) ffmpeg for AV1 support

### ISSUE THREAD

**Issue by dietmarw** [MaartenBaert/ssr#727]
I was wondering if it was possible to specify newer codec as supported by newer ffmpeg versions via some configuration or is this hooked into ssr itself?
My usecase is that I'm running ffmpeg 4.x from the snap channel which has support for AV1 codec and would like to utilise this also for ssr.

**Comment by MaartenBaert** [comment]
New codecs should show up under 'Other' if they support a pixel format that SSR understands. For me `libaom-av1` works fine but it is extremely slow. I get below 1 FPS for a 300x300 video even with the fastest settings. IIRC libaom-av1 is the reference encoder so it's not optimized for speed.

**Comment by dietmarw** [comment]
Thanks. That answers my question.
