### ISSUE TITLE
Screenshots and More Description in README

### ISSUE THREAD

**Issue by zicklag** [MaartenBaert/ssr#733]
Hey there! This is a great project, exactly what I was looking for. Unfortunately for me, I hadn't installed it earlier because I didn't realize that it had a GUI for doing the recording. There wasn't a whole lot of description in the README so I didn't know if it was just a commandline tool or a user-friendly GUI.

It would be great to have screenshots of it in the README along with maybe a little bit more explanation of what it provides.

**Comment by marafa** [comment]
can you provide the screenshots?

can you also provide the PR for it?

**Comment by zicklag** [comment]
Sure, I'll do that if I get the chance. Not sure exactly when. Could you assign this issue to me to help me remember?

**Comment by MaartenBaert** [comment]
The screenshots are already there in the `data/screenshots` folder.

**Comment by zicklag** [comment]
That's perfect, thanks!
