### ISSUE TITLE
No option of "add timestamp" Linux Mint 19.2

### ISSUE THREAD

**Issue by sanghalinux** [MaartenBaert/ssr#739]
SSR 0.3.11 on my laptop with Mint 18.3 Xfce (Based on Ubuntu 16.04) have the important option of "add timestamp"
SSR 0.3.8-3 on my PC with Mint 19.2 Xfce (Based on Ubuntu 18.04) Unfortunately have no option of "add timestamp"
"Add timestamp" beside "separate file per segment"  is so important, how to update or what can I do to have back "add timestamp" with the newer Linux Mint ?
Thank you !!! I love SSR

**Comment by MaartenBaert** [comment]
You can get a newer version from the PPA:
```
sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder
sudo apt-get update
sudo apt-get upgrade
```

Or you can uninstall the version of SSR from the repositories and compile from source instead using the instructions in the README file.

**Comment by sanghalinux** [comment]
Thank you so much "add timestamp" is back with the new version form the PPA. 

It would be great if this newer version of SSR 0.3.11+1 from the PPA would be the regular version in the Software Manager of Linux Mint 19.X or soon in the version 20.x in April 2020.

I'll try to learns how to compile from source in virtual box using the instructions, I'm new to linux since May 2018, I switched to linux because I don't like Windows 10. And Simple Screen Recorder is THE reason why I will stay with Linux.

Thank you again! Sorry if my english is not perfect my mother tongue is french!
