### ISSUE TITLE
How to fix a "not a saved correctly" video ?

### ISSUE THREAD

**Issue by Spheerys** [MaartenBaert/ssr#746]
Hi !

I have recorded a video but I complety forget to "Save" it correctly after stopping the record.
I have close simplescreenrecorder and restart my computer and finally, my video file is not "correctly finished"
Is there a way to fix it manualy ?

**Comment by mathieu-aubin** [comment]
What format is it?

**Comment by Spheerys** [comment]
.mp4

**Comment by MaartenBaert** [comment]
There is probably very little you can do - this is a known problem with the MP4 file format. A crucial part of the file is written only at the very end, so if the recording is interrupted, the file becomes unreadable. Use MKV in the future to avoid this.

**Comment by Spheerys** [comment]
Pssffff bad news for me :(
But thank you for the MKV tip.
I just have to check if Youtube will accept it for the upload....

**Comment by MaartenBaert** [comment]
They accept MKV without issue. And you can always convert MKV to MP4 losslessly with the ffmpeg command line tool.

**Comment by Spheerys** [comment]
Thanks, it's working :)
