### ISSUE TITLE
Terminal initiated videos

### ISSUE THREAD

**Issue by jozsefmorrissey** [MaartenBaert/ssr#747]
Update: I implemented the requested feature in this [pull request](https://github.com/MaartenBaert/ssr/pull/749).

This command should illustrate exactly what I am looking for.

simplescreenrecorder --audio_profile=[profile name] --video_profile=[video name] --record_interval=[time in seconds to record] --save_file=[save location/filename]

You have created a great application, but i am trying to automate my recording process and you application is the last piece of the puzzle. It seems like it would be fairly simple to add this feature. If your too busy and I get the time I will try to do it myself.

Thanks again for a great product!

**Comment by MaartenBaert** [comment]
See https://github.com/MaartenBaert/ssr/pull/749.
