### ISSUE TITLE
Output file does not have any content

### ISSUE THREAD

**Issue by david-kohen** [MaartenBaert/ssr#759]
Ubuntu 18.04
output files are not growing - they consist of the header only (around 811-814 bytes) 
I removed and reinstalled, but it didn't help. Worked fine until recently (I had to remove my NVidia card - maybe relevant?)
[log-2020-04-09_19.17.16.txt](https://github.com/MaartenBaert/ssr/files/4457374/log-2020-04-09_19.17.16.txt)
In the record screen the FPS out, File size and the Bit rate all
![Screenshot from 2020-04-09 19-21-40](https://user-images.githubusercontent.com/20706803/78917364-72080500-7a97-11ea-8d3a-e2f56420ead0.png)
 (correctly) show zero

Any suggestions?

**Comment by MaartenBaert** [comment]
Does it work if you try to record without audio?

**Comment by david-kohen** [comment]
Good call - indeed it does. And with that hint I switched the audio from Pule to ALSA abd now it works perfectly- thanks
