### ISSUE TITLE
Feature Request: record for a maximum time period

### ISSUE THREAD

**Issue by bjd-pfq** [MaartenBaert/ssr#767]
Title says all: make it possible to tell ssr: record for e.g. 45 minutes, then save and stop.

That's a bit cleaner than running a kill script concurrently (I don't even know if ssr would write out the current recording when it receives a KILL signal).

I'm on Linux.

Additional possible variations: tell it to record up to a maximum of thus and so Megabytes.

**Comment by conualfy** [comment]
Yes, I'd totally like this, without having to further edit to cut a recording or to need to stay around the computer for some automatic recording. For me, some automatic start scheduling would be a nice feature, too, but this would be great for now, too.

**Comment by MaartenBaert** [comment]
This was already added in 0.4.0 (record schedule).

**Comment by bjd-pfq** [comment]
Hi Maarten,
I see. I'm running 0.3.8.3 on Linux Mint, so I'll just await the update. Thanks for by far the best screen recorder.

**Comment by conualfy** [comment]
I have 0.3.11 on Ubuntu 20.04, is there some .deb / something else (not compiling, as I am not that good at it) with the latest version? Thanks!

**Comment by MaartenBaert** [comment]
I'm pushing out an update to the PPA, if you have it installed you should get it soon. If not, run this:
```
sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder
```
And wait for the next update.
