### ISSUE TITLE
Will it work on Windows 10 64bit?

### ISSUE THREAD

**Issue by in2Rafi** [MaartenBaert/ssr#769]
I am using Simple Screen Recorder on my Linux Mint 19 and very impressed by its quality and simpleness. My question is will it work on Windows 10 64bit OS too? For my YouTube channel I need to record a lot of screens using Windows 10 OS.

Also how can I record best screens? I mean what is its best screen recording set up?

**Comment by MaartenBaert** [comment]
Currently SSR does not support Windows. You could try Open Broadcaster instead.
