### ISSUE TITLE
Click on Continue does not do anything

### ISSUE THREAD

**Issue by hannob** [MaartenBaert/ssr#771]
I observe some strange behavior which I believe is a bug.

Sometimes when I click on "Continue" after the first settings screen (the one starting with "Input profile") nothing happens.

I can reproduce this reliably with this order of actions:
* Set "Video input" to "Record a fixed rectangle".
* Click on "Select window".
* Select any open window.
* Click on "Continue" -> nothing happens.

**Comment by MaartenBaert** [comment]
You're right, it should be fixed now if you compile the latest version from the master branch.
