### ISSUE TITLE
one string missing in the translation file

### ISSUE THREAD

**Issue by trebmuh** [MaartenBaert/ssr#773]
Hi @MaartenBaert : it seems that the "Skip this page next time" from this page:

![ssr-capture](https://user-images.githubusercontent.com/8705846/80764991-31edec80-8b42-11ea-81b2-b7f39bbfddd8.png)
is missing from the French translation file.

Could you please update it then I can provide the translation for this string?

**Comment by MaartenBaert** [comment]
I just regenerated the translation files, you can translate it now.

**Comment by trebmuh** [comment]
Thank you @MaartenBaert .
There were a bunch of new strings, no just one! Good to be clean and fresh now.
I've fixed the supernumerary ">" too.
