### ISSUE TITLE
Can't put the file where I need to

### ISSUE THREAD

**Issue by reverendfuzzy** [MaartenBaert/ssr#776]
While trying to use SimpleScreenRecorder, I noticed in the current version, I can't set the output file to a folder on a secondary hard disk.

* Using Ubuntu 20.04 LTS
SimpleScreenRecorder 0.3.6
Compiled with GCC 5.2.1
Qt: header 4.8.7, lib 4.8.7
libavformat: header 56.40.101, lib 56.40.101
libavcodec: header 56.60.100, lib 56.60.100
libavutil: header 54.31.100, lib 54.31.100
libswscale: header 3.1.101, lib 3.1.101

**Comment by MaartenBaert** [comment]
So what happens when you try this? Any error messages?

**Comment by reverendfuzzy** [comment]
Well, it took the repository without issue, and attempted the update and upgrade, but it's still at version 0.3.6

As for being outdated, you may want to speak with the folks that run the software store for Ubuntu, as that's the version they still have listed.

**Comment by reverendfuzzy** [comment]
Ok, it took the repository (needed apt-add-repository instead of add-apt-repository to make it work)
Deleted, and purged the previous version (0.3.6).
Went back, and checked the Ubuntu Store some more, and found the newer one (0.4.1) listed as "ssr", with no icon art.

Installed... works great,now. (Love the new desktop icon, btw).
Thanks.
