### ISSUE TITLE
Small typo in the french translation

### ISSUE THREAD

**Issue by esperlu** [MaartenBaert/ssr#777]
Small typos 

### src/translations/simplescreenrecorder_fr.ts:1683

```
- (et de nombreux lecteurs de multimédia ne lise que l&apos;audio AAC).
+ (et de nombreux lecteurs de multimédia ne lisent que l&apos;audio AAC).
```

### src/translations/simplescreenrecorder_fr.ts:1625:
```
- <translation>Profile de sortie</translation>
+ <translation>Profil de sortie</translation>
```
### src/translations/simplescreenrecorder_fr.ts:1330:
```
- <translation>Profile d&apos;entrée</translation>
+ <translation>Profil d&apos;entrée</translation>
```
Cheers.

Jean-Luc

**Comment by big-tree-wang** [comment]
unsubscribe ------------------ 原始邮件 ------------------
发件人: "Maarten Baert"<notifications@github.com>
发送时间: 2020年5月4日(星期一) 晚上7:19
收件人: "MaartenBaert/ssr"<ssr@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [MaartenBaert/ssr] Small typo in the french translation (#777)




 
Closed #777 via 83f8d34.
 
&mdash;
