### ISSUE TITLE
Set keyframe interval

### ISSUE THREAD

**Issue by giorgiobornia** [MaartenBaert/ssr#778]
Dear all,
  how can one set the keyframe interval in SSR?
  For what I tried, it seems like that is always 8 seconds,
  but I would like to have something below 6 seconds.
   In fact, I need to upload these videos to an online platform that does transcoding if the keyframe is above 6 secs, causing a file bloat of about 20 times the original size.

 Any help is appreciated,
  Giorgio

**Comment by MaartenBaert** [comment]
The option you need is `keyint`. The value is expressed in number of frames, so at 30 fps you could use 150 to get 5 second keyframes. Note that keyframes in x264 are flexible, the encoder can choose to insert more keyframes when it determines that this is beneficial (e.g. at scene cuts). But the keyframe interval should never become higher than the `keyint` option.

To add this option, you need to set the video codec to 'other', select libx264, set bitrate to 0 and add the custom options `crf=23,preset=veryfast,keyint=150`. `crf` and `preset` correspond to the quality and preset that is normally configured through the basic GUI.

**Comment by giorgiobornia** [comment]
Great! Thanks a lot, and congratulations on this software.
