### ISSUE TITLE
No sound on UBUNTU 18.04 cascades to show deficiencies in SSR default setup

### ISSUE THREAD

**Issue by joemhiggins** [MaartenBaert/ssr#780]
I have been using simplescreenrecorder (SSR) for 5 - 8 years and I really never touch it, except I use it to take courses online so I lower the frames per second from the default of 30 to 10 frames per second because no one can type 30 letters per second

My logs do not show why I upgraded from Ubuntu 16.04 to 18.04. But I did upgrade it 5 days ago to Ubuntu 18.04. All I know about my dell laptop is it is an XPS with a 4K screen (I am unwilling to pick it up from it's current location and examine the bottom of it and I have only been using Ubuntu for 2 years and I never go into my BIOS - unless everything is torn to shred - which is once in the last 5 years).

The default setup for SSR is incorrect for my laptop because
1) my left front speaker is blown on my laptop (I blew out a car speaker 30 years ago so I know my laptop speaker is blown).
2)the default setting for SSR picks up the noise of my fan on my laptop and since my laptop is 5 years old, the fan starts to get very, very loud - I mean very loud - when I record a video.

I have looked on the internet and no one is doing what I am doing and no one really understands what you can do with SSR.

The actual original error of "no sound", I *think* I have traced back to operator error - that would be me. I think when I plug my external speakers in my laptop - it turns the output volume to off on my laptop. I do not know if that is true. I do not touch my laptop system settings (I only had the speakers removed because I had to do construction in my condo).

The "profiles" implementation in SSR is totally spectacular. I totally love it.

Here is my config for SSR on my Dell XPS laptop (and I highly recommend people buy a headset WITH a microphone - I just have a headset so I have no redundancy).

Everything is working with SSR so I am not touching a thing.
My actual log is thousands of pages long and I am going to omit 99% of it on grounds of mercy and show what my setup is
now:

20200506004 SSR still not working, reinstalling UBUNTU 18.04.3 ISO
20200506005 begin SSR testing
20200506006 moved diary contents to y /MY_TMP/SSR_TSHOOT
20200506007 CREATED SSR PROFILE SECONDARY SCREEN AND MOVED TO y /MY_TMP/SSR_TSHOOT

PREREQUISITE:
	PHYSICAL
		HDMI TV PLUGGED IN AND WORKING
		EXTERNAL SPEAKERS PLUGGED IN AND WORKING
	SYS SETTINGS - DEVICES - DISPLAYS
		JOIN DISPLAYS
		PRIMARY DISPLAY - TECHNICAL CONCEPTS LTD 36"
			BUILT-IN DISPLAY
				ORIENTATION - LANDSCAPE
				RESOLUTION - 3840 X 2160 (16:9)
				SCALE - 200%
				REFRESH RATE - 60.00HZ
				NIGHT LIGHT - OFF
			TECHNICAL CONCEPTS LTD 36"
				ORIENTATION - LANDSCAPE
				RESOLUTION - 3840 X 2160 (16:9)
				SCALE - 200%
				REFRESH RATE - 60.00HZ
				NIGHT LIGHT - OFF
	SYS SETTINGS - SOUND
		OUTPUT
			OUTPUT VOLUME - 100%
			OVER-AMPLIFICATION - OFF
			DEVICE - HEADPHONES
			SETTINGS - BALANCE 50% EACH
			PROFILE - ANALOG STEREO OUTPUT
		INPUT
			OUTPUT VOLUME - 100%
			OVER-AMPLIFICATION - OFF
			INPUT VOLUME - 50%
			INTERNAL MICROPHONE - BUILT-IN AUDIO
		SOUND DEFECTS
			OUTPUT VOLUME - 100%
			OVER-AMPLIFICATION - OFF
			ALERT VOLUME - ON, BUT NEAR 0
			ALERT SOUND - DEFAULT
		APPLICATIONS
			FIREFOX - 100%
SSR PROFILE LAPTOP_SECONDARY_SCREEN
	VIDEO INPUT
		CHECKED RECORD THE ENTIRE SCREEN - SCREEN 2
			SCREEN 2 IS THE LAPTOP SCREEN IN 4K MODE
			SCREEN 2 3840X2160 AT 3840,0
		FRAME RATE 30
		UNCHECKED SCALE VIDEO
	AUDIO INPUT
		CHECKED RECORD AUDIO
		BACKEND - PULSEAUDIO
		SOURCE - MONITOR OF BU...ANALOG STEREO
SSR OUTPUT
	PROFILE - NORM_SECONDARY_SCREEN_OUTPUT
		DESCRIPTION - NORM MODE IS NOT TROUBLESHOOTING
		FILE
			SAVE AS: THIS IS A VARIABLE
			SEPARATE FILE SEGMENT -
				UNCHECKED IN NORM MODE
				CHECKED IN TSHOOT MODE
			CONTAINER - MATROSKA (MKV)
		VIDEO
			CODEC - H.264
			CONSTANT RATE FACTOR - 23
			PRESET - SUPERFAST
			ALLOW FRAME SKIPPING - CHECKED
		AUDIO
			CODEC - VORBIS
			BIT RATE (IN KBPS) - 128

20200506 21:00 SSR successfully recorded sdn programmability 06-10

**Comment by MaartenBaert** [comment]
I don't really understand your question - by default SSR will simply select the first audio source on the system (which is usually the microphone), because there is no way SSR can guess what the intention of the user is.

Also, whether the left speaker is working or not should not affect SSR functionality.

**Comment by joemhiggins** [comment]
First for clarity sake, this is ubuntu 18.04.4 LTS and this is simplescreenrecorder.

The left speaker being "blown" is different than the left speaker not working.
A blown speaker makes loud crackling noises when sound is transmittted on it
at certain frequeencies. It has been 30 years since I have looked into it.
But from my memory, low ferquencies put a tremendous strain on speakers at
about 10 times the level of frequencies at which people speak.

The crackling noise is very noticeable during the default setup of simplescreenrecorder because the learning institutionI that I use  likes to
start off their videos with what I would describe as a lightning strike. Simplescreenrecorder records the bad speaker noises into my video.
Doing forencsics on the speaker being blown, I would venture to say
that is the culprit of the speaker being blown because I do not listen to
any kind of music on my laptop.

Simplescreenrecorder just chooses the "first audio source" - that is "the problem".
Again, ideally, I would have a headset with a microphone and then manually
select the headset/microphone as the input source and I would have never confronted this problem.

Oh, my logs are not thousands of pages long, but thousands of lines long and I made a major, major mistake and tried to troubleshoot the problem I had with simplescreenrecorder for 8 straight hours when I could have just reinstalled ubuntu in 10minutes.

In any event, everything is working here. You can put "a don't fix" or "wont fix" or whatever github thing it is to close the problem. But choosing the "first audio source" as an input as the default is, in my opinion, a mistake.

**Comment by MaartenBaert** [comment]
For what it's worth, you can mute the left speaker only by running 'alsamixer', selecting the control corresponding to the speakers, and press '<' such that the control displays "MO" (i.e. muted-open) rather than the default "OO".
