### ISSUE TITLE
HD recording

### ISSUE THREAD

**Issue by rrjanbiah** [MaartenBaert/ssr#782]
Forgive me if this is already possible. But, can't get it with below configuration on Ubuntu 16.04:

```
Video input
All screens: 1440x900
Frame rate: 30
Scale video: no
Record cursor: no
Audio Input
Record audio: yes
Backend: PulseAudio
Source: Monitor of Built-in Audio Analog Stereo

File
Container: MP4
Video
Codec: H.264
CRF: 23
Allow frame skipping: yes
Audio
Codec: Vorbis
Bit rate: 128
```

**Comment by MaartenBaert** [comment]
I don't understand your question. What is the problem?

**Comment by rrjanbiah** [comment]
@MaartenBaert Recorded video is not in HD with above configuration. Are there any configuration issue or HD is not yet supported?

**Comment by MaartenBaert** [comment]
What do you mean by 'HD'? 720p? 1080p? With the settings you've selected you will get a 900p video which isn't a standard resolution, but it is the best resolution you can get with your screen. If you want higher quality you need a 1920x1080 screen.

**Comment by rrjanbiah** [comment]
@MaartenBaert Ah, that makes sense. Thanks for your time.
