### ISSUE TITLE
Unable to record any windows game since 0.4.1 arrived

### ISSUE THREAD

**Issue by IvoAndonov** [MaartenBaert/ssr#785]
Ever since version 0.4.1 arrived I can't record any windows game (ran with wine). Before 0.4.1 all I had to do was to set SSR to capture sound from "Analog surround 2.1 output" and that was it. But now with this settings when I run the windows game, it has no sound and the recorder video doesn't have a sound either. If I open winecfg and select "pulseaudio" (instead of "system default") the game does have a sound but the video isn't recorded and usually becomes several kilobites and is long 10 seconds tops.
Soon I'll buy a webcam which I'll use to record the game recording process with SSR, so that you can see what exactly is happening.

**Comment by MaartenBaert** [comment]
Which version were you using before 0.4.1? Are you using the ALSA or PulseAudio backend in SSR? Can you post the SSR log?

Also, can you please post the output of the following command:
```
arecord -l
```

There has been a recent change in the ALSA backend which was supposed to work around another bug, that might be the cause.

**Comment by IvoAndonov** [comment]
The version was 0.3.11.
SSR was installed (updated) from Arch repo (community), so it must have been a precompiled package.
'arecord -l' says "bash: command not found" and there's no such a package in the Arch repo either, nor in AUR.
I have 2 SSR logs, I'll archive them both cuz I don't remember on which date exactly the problems started.

[SSR-Logs.zip](https://github.com/MaartenBaert/ssr/files/4643977/SSR-Logs.zip)

I also tried with downgrading SSR back to 0.3.11 but the problem remained. Right now a Windows game (ran by Wine) is recorded either with image but no sound (both the game and the recorded video have no sound) or with sound but no image (just black screen) or the most frequent problem - the game has sound but the video becomes several kilobytes and sometimes there's a red X mark on the SSR icon in tray.

**Comment by MaartenBaert** [comment]
`arecord` can be found in the `alsa-utils` package. Based on the version information you've given, this seems to have nothing to do with the recent change to the ALSA backend (which is not yet released).

Can you please also post your SSR settings file (`~/.ssr/settings.conf`)?

I think you meant to record `[alsa_output.pci-0000_00_1b.0.analog-surround-21.monitor] Monitor of Built-in Audio Analog Surround 2.1` however I'm seeing the following message in the log:
```
[PulseAudioInput::InputThread] Stream is not a monitor.
```
Which is weird if you were indeed recording a monitor.

**Comment by IvoAndonov** [comment]
Here are the settings:
[settings.conf.txt](https://github.com/MaartenBaert/ssr/files/4644443/settings.conf.txt)

Until recently when I wanted to record from the microphone I was choosing "Monitor of/from Built-In Audio bla-bla-bla". If I wanted to record desktop audio which also includes games or desktop itself, I was choosing "Built in Audio bla-bla-bla" (without the words "Monitor of/from").
![system-screenshot](https://user-images.githubusercontent.com/41172201/82221376-9a054680-9928-11ea-8564-7a35f11d8b7b.png)

**Comment by MaartenBaert** [comment]
> Until recently when I wanted to record from the microphone I was choosing "Monitor of/from Built-In Audio bla-bla-bla". If I wanted to record desktop audio which also includes games or desktop itself, I was choosing "Built in Audio bla-bla-bla" (without the words "Monitor of/from").

This makes no sense, it should be the other way around. If this is really how it behaves for you then there is something very wrong with your audio setup. If you use a different program with PulseAudio support to record audio (e.g. `parecord` from the `libpulse` package), do you get the same behavior?

**Comment by IvoAndonov** [comment]
Well, after so many years (4, actually) I've been using "Monitor of [source name]" for mic recording - first with Mint 18.3 Cinnamon and in the last year with Arch Linux Cinnamon (the rolling release).
Anyway, I decided to try what you said - that it should be the other way around, so I tested it a bit and now it seems to be working - even windows games have sound when recorded, so I apologise I wasted your time with this thing. But in the last 4 years I had to use SSR in the way I mentioned above, that's why now I thought there was something wrong with it.

P.S. I noticed 2 things though:
• SSR is now 0.4.2 (which I don't remember updating it, lol)
• Until today when I recorded a game the output video had a very quiet sound, so I had to use Handbrake or a cracked windows program to amplify it.
However, after installing package named "samba", all the desktop recordings (not mic) have loud and clear sound volume, so no external intervention is needed. IDK why is that, I'm just mentioning it, if it means anything to you.

**Comment by MaartenBaert** [comment]
If the audio was extremely quiet, it is possible that you were in fact recording the microphone input, but without a microphone plugged in it may have picked up the signal from the headphone jack, since the two cables usually run in parallel inside the PC. My desktop does the same thing, but the sound is very quiet and contains only the high frequencies.
