### ISSUE TITLE
BUG: SSR UI gets recorded in middle of screen at 2FPS

### ISSUE THREAD

**Issue by joemhiggins** [MaartenBaert/ssr#787]
After the last "problem" with SSR and after so many years of using SSR, I started to investigate SSR.

The chain of events is as follows:
1) I primarily run SSR on Ubuntu 16.04.3 VMs that are located inside of GNS3. I run multiple VMs at the same time - usually 4 VMs across 2 machines. Consequently, I am using some type of VNC client to connect to the VMs. I will just stay focused on my physical Windows machine because my physical Ubuntu machine is presently out of action.
2) Please forgive my ignorance, but I did not know that the VMs default resolution was 1072x768 and my 4k monitor for my physical machine was 3840x2160 and I just did not know that the blatantly obvious concept that a recording on the physical Ubuntu machine would be 10x larger than a recording on the VMs.
3) So, after so many years, I decreased the SSR input profile to record from frame rate 10 down to a frame rate of 2 on two of my VMs. One of my VMs is "working perfectly" at 2 FPS, but the other one became broken yesterday and I stopped and started it yesterday and the SSR UI disappeared from staying stuck in the middle of the screen. The problem returned this morning and I have isolated the problem to me changing the default 30 FPS down to 2 FPS. For so many years, I have never touched anything in SSR because it always, always, always has worked. But the problem I had with the default audio setup in SSR for my laptop led me down a wrong path.

My confidence level is extremely high at this point that the 2 FPS recording level causes a bug. That being said, I never, never should have changed the default recording rate from 30FPS to 10FPS to 2FPS.

I further investigated SSR and I will say after recording probably 1000 plus videos, to the best of my limited knowledge of the command line options, it is absolutely extremely damaging that I can not run ssr entirely from the command line with a "stop and save" recording option. I literally have lost 150+ hours of recording because I inadverantly "click" my mouse in the field of recording and it can either pause the playback (and it takes me 30minutes to figure out I paused the video) or mute the recording (and since I am running on SSR on VMs I have to wait until the recording is complete until I am able to figure out I muted the recording). With multiple VMs running on multiple monitors on multiple machines this is the choice I have made and it leads to losses in time.

But, minimizing all my vnc clients and running SSR entirely from the command line (or better yet an ssh client - I do not know anything about the limitations of xWindows), I would not have to worry about my mouse running AMOK.

(Oh, as a quick aside in reference to my last post, a "blown speaker" is a slang term and, from my recollection 37 years ago, it means the glue from the woofer has been broken from the speaker frame so the speaker sound is extremely distorted - sorry, I am guessing your native language is French).

With elearning from home, SSR can be extremely be powerful and it can reduce the time to take classes by 10 times.

**Comment by MaartenBaert** [comment]
I don't understand the problem, SSR works file at 2 FPS in my tests. Also I don't understand what you mean by 'staying stuck in the middle of the screen'.

It is in fact possible to control SSR from the command line as of version 0.4.0, see:
https://github.com/MaartenBaert/ssr/pull/749#issuecomment-586619617
Combine this with --start-hidden to hide the GUI entirely.

**Comment by joemhiggins** [comment]
Well, I am sorry, I did not see that record-save in a simplescreenrecorder --help.
As far as I am concerned, that command fixes everything for me.

But to your question, my vnc client, tnyvnc, takes up 1/3 of one of my monitors when I log into a VM. When I open up the SSR GUI inside of the vnc client, it takes up 1/2 of my vnc client screen. When I start to record a video at 2 FPS in one of my 2 VMs, it SSR records the SSR GUI being placed in the middle of the VNC client screen. This only started to happen when I switched to 2 FPS on both of my VMs. One of my VMs does not have this problem, but one of them does.

I can not really troubleshoot this because I have recorded hundreds if not 1000s of videos with SSR and it always worked at 30FPS and SSR is designed to "skip frames".

Furthermore, it is absolutely wonderful that there is a "record-save" option that I did not know about. It is really, really great that there is a "record-save" because recording 5 hours of videos on 10 different subjects makes no sense because I do not know what is inside of them. I need to put titles on the videos so I can refer to them quickly when I want to look something up.

Please close this out with a "don't fix" or "won't fix" or "No trouble found".

**Comment by joemhiggins** [comment]
![SNIP](https://user-images.githubusercontent.com/57160630/82132022-6223c500-97a9-11ea-8162-d93ea191c0f5.PNG)

This is a snip of a segment of 10-12 hours of video yesterday.
As you can see from the VLC media player, the video shows to be almost done.
However, the SSR recording shows the video to "not have started" and the SSR GUI is stuck in the miiddle of the screen.

I am just answering your question with a complete explanation. I do not want to belabor the point.

As far as there being no "record-stop-and-save" option, I will just kill the video after doing the "record-save" option - unless you have any protest against that.

**Comment by MaartenBaert** [comment]
You can run `record-save` followed by `quit`, but you have to wait a bit between the commands to give SSR time to finalize the recording (otherwise it will ignore the `quit` command).
