### ISSUE TITLE
Do ssr support command / scripting?

### ISSUE THREAD

**Issue by johnwmail** [MaartenBaert/ssr#790]
Hi, as title said, do ssr support command line or scripting?
what I want is sleep 10s && start record with --start-hidden mode.
how can I do this, thanks?

**Comment by MaartenBaert** [comment]
Yes, see:
https://github.com/MaartenBaert/ssr/pull/749#issuecomment-586619617

**Comment by johnwmail** [comment]
Hi, thank your reply.
Debian package seems to be not support --start-recording yet

john@redcat:~$ simplescreenrecorder --start-hidden --start-recording
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-john'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-john'
Qt: Session management error: Could not open network socket
[main] Error: Unknown command-line option '--start-recording'!
Usage: simplescreenrecorder [OPTIONS]

Options:
  --help              Show this help message.
  --version           Show version information.
  --logfile           Write log to ~/.ssr/log-DATE_TIME.txt instead of stdout.
  --statsfile[=FILE]  Write recording statistics to FILE. If FILE is omitted,
                      /dev/shm/simplescreenrecorder-stats-PID is used. It will
                      be updated continuously and deleted when the recording
                      page is closed.
  --syncdiagram       Show synchronization diagram (for debugging).
  --no-systray        Don't show the system tray icon.
  --start-hidden      Start the application in hidden form.

------------------------------------------------
john@redcat:~$ simplescreenrecorder --version
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-john'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-john'
Qt: Session management error: Could not open network socket
SimpleScreenRecorder 0.3.11
Compiled with GCC 9.2.1
Qt: header 5.12.5, lib 5.12.5
libavformat: header 58.29.100, lib 58.29.100
libavcodec: header 58.54.100, lib 58.54.100
libavutil: header 56.31.100, lib 56.31.100
libswscale: header 5.5.100, lib 5.5.100

**Comment by MaartenBaert** [comment]
I don't maintain the debian package. Debian isn't exactly known for quick updates, if you want the latest version you should probably compile it from source, or maybe try to use a package from the Ubuntu PPA:
https://launchpad.net/~maarten-baert/+archive/ubuntu/simplescreenrecorder/+packages
