### ISSUE TITLE
Mono microphone output to stereo (using pulseaudio)

### ISSUE THREAD

**Issue by Veek** [MaartenBaert/ssr#791]
https://i.imgur.com/lXjVHg8.png
(i've enabled noise cancellation but i tried from the device - no luck) 
Is there a way around this problem?

How can I record stereo on a MIC? I am getting a MONO channel/sound on my LEFT earphone and a very faint sound on the right.. I want STEREO. (asked everywhere no luck) I've plugged the MIC into the pink desktop socket - i can record mono just fine - I want stereo.

What should I do in pulseaudio - what module to clone my mic-source and then?
Active Port: analog-input-rear-mic
Volume: front-left: 65540 / 100% / 0.00 dB, front-right: 65540 / 100% / 0.00 dB balance 0.00
Base Volume: 6554 / 10% / -60.00 dB

module-remap-source
master=alsa_input.pci-0000_00_1f.3.analog-stereo

Ref https://github.com/MaartenBaert/ssr/issues/323

**Comment by MaartenBaert** [comment]
I already replied in #323. No need to open a new issue.
