### ISSUE TITLE
Can't create audio with Pulseaudio it's flaky - no obvious errors but no audio except occassionally - video works 

### ISSUE THREAD

**Issue by Veek** [MaartenBaert/ssr#794]
My pulseaudio setup works with firefox and such. With SSR, very often but not always, I just get no audio in the video. Logs included. It's reproducible and occurs frequently. 

I am su - veek (from root) and DISPLAY=:0.0 to root.
Is there a way to debug why SSR acts flakily with Pulseaudio?

[log-2020-06-02_00.58.09.txt](https://github.com/MaartenBaert/ssr/files/4713077/log-2020-06-02_00.58.09.txt)
[pulse.log](https://github.com/MaartenBaert/ssr/files/4713078/pulse.log)

**Comment by MaartenBaert** [comment]
You seem to be using the echo-cancelled source. Do you get the same problems when you use the regular source without echo cancellation?

Do you have sound notifications (i.e. the sound effect when you start/pause the recording) enabled or disabled in SSR?

**Comment by Veek** [comment]
hi, yes - I do get sound notifications from  SSR **every time** record-on|off.
(I'll try with the regular source - thanks - brb)

**Comment by Veek** [comment]
_su - veek bash -c "export DISPLAY=:0.0; export XAUTHORITY=~veek/.Xauthority; simplescreenrecorder --logfile"_
the command i use to su

**Comment by Veek** [comment]
I Enabled --syncdiagram and in the failed audio it shows 'Audio out' etc but there's no audio in the file

**Comment by Veek** [comment]
ugh - so it's working as expected - sorry - there is not problem whatsoever!
Basically - to test I was running pulseaudio within su - veek and that locks the audio so WHILE THAT's RUNNING, mplayer presents no audio.. soon as i close it - everything works as expected!

Grr! so sorry I wasted a lot of time with this :( and there's nothing wrong with your program!

**Comment by MaartenBaert** [comment]
No problem, missing audio can have many causes. I'm glad it's not a new bug ;).
