### ISSUE TITLE
Is there a way to mix sources (your own voice from mic and the running applications)  

### ISSUE THREAD

**Issue by alainpannetier** [MaartenBaert/ssr#797]
This is not an issue but I've been struggling with this for a long time.

Conferencing apps don't feed back your own voice. So it seems you can operate in only two modes.

1/ You record the app but your interventions are left out.

2/ You record your voice but then the app is mute.

Attaching the two settings that work.
1/ ALSA and default source will record your voice (this seems to be the setting with the best S/N ratio)

2/ PulseAudio and Monitor (strangely, with a jack in) records the sound from applications.

How are you guys solving this please ?
Do I need to mix things upstream of SSR ? Any tool for this ?

**Configuration for Mic input (less noise)**
![ssr_audio_01](https://user-images.githubusercontent.com/1625152/83831696-0211a600-a6f9-11ea-8a06-9784ef560c51.png)

**Available ALSA options with USB headset plugged in.**
![ssr_audio_02](https://user-images.githubusercontent.com/1625152/83831699-04740000-a6f9-11ea-9645-cc09fdc5a52a.png)

**Configuration for applications recording.**
![ssr_audio_03](https://user-images.githubusercontent.com/1625152/83831704-050c9680-a6f9-11ea-989a-2f833c0f4d0a.png)

**Output system config**
![ssr_audio_04](https://user-images.githubusercontent.com/1625152/83831707-063dc380-a6f9-11ea-99a0-631f2c26314d.png)

**Comment by MaartenBaert** [comment]
See: https://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/#recording-game-audio-and-microphone-at-the-same-time
But this approach is slightly buggy. It would be better if SSR could capture both sources and do the mixing internally, but this is currently not supported yet.
