### ISSUE TITLE
JACK audio port pretty-name metadata?

### ISSUE THREAD

**Issue by mxmilkiib** [MaartenBaert/ssr#802]
Currently ssr looks like this in a JACK graph patchbay;

![image](https://user-images.githubusercontent.com/108225/85078827-3b4c1a80-b1bd-11ea-9536-ed0336a279b5.png)

Could a JACK pretty-name property be set for the ports, like "Input L" and "Input R"?

**Comment by MaartenBaert** [comment]
This was done because JACK seems to use the same convention for the system capture and playback ports, i.e. capture_1/capture_2 and playback_1/playback_2. Changing the names for SSR now would break existing scripts and patchbays, so I don't really feel like renaming them to left/right now.

**Comment by MaartenBaert** [comment]
Nevermind, I misunderstood your request, I was unaware of the metadata feature. I will try to add it.
