### ISSUE TITLE
[0.4.2] Interlace mode not set

### ISSUE THREAD

**Issue by MatNieuw** [MaartenBaert/ssr#803]
Recording with SSR works fine, but the recorded video does not have the interlace mode set, according to video editor Cinelerra. I suggest to set it to non-interlaced. 
SSR version 0.4.2 on Linux Mint 19.3 XFCE

**Comment by MaartenBaert** [comment]
AFAIK the ffmpeg API doesn't provide a way to explicitly mark a video as non-interlaced. And according to ffprobe, the file SSR produces is in fact non-interlaced at least when using MKV. I don't think this is an SSR flaw, this is just how ffmpeg works.

**Comment by MatNieuw** [comment]
You are correct, ffprobe shows "yuv420p(tv, bt709, progressive)" on the .mkv file. The error must be in the editor. Bedankt, Mat
