### ISSUE TITLE
Linux: libv4l2 depencency not in readme file, w/o it build fails

### ISSUE THREAD

**Issue by juozaspo** [MaartenBaert/ssr#805]
When trying to build latest SSR on Ubuntu 20.04 LTS build fails if V4L2 libraries are not present. Installing libv4l-dev fixes the problem. The requirement is not included in the README file so building fails since those libraries were not installed earlier as part of build depencencies. Excerpt copied from log: 
```
-- Checking for module 'libv4l2'
--   No package 'libv4l2' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find V4L2 (missing: V4L2_LIBRARY V4L2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindV4L2.cmake:10 (find_package_handle_standard_args)
  src/CMakeLists.txt:13 (find_package)
```
Commit: 7f26bc7850ea7755e9d6f716e47cd6e47e139bcc
Affected commit: 1dfa6066a10e409a11de553cd8ba6d0ac3ea867c and newer

**Comment by MaartenBaert** [comment]
Fixed.
