### ISSUE TITLE
[feature request] Update PPA and Terminal codes website.

### ISSUE THREAD

**Issue by Charlie-Ramirez-Animation-Studios-de-MX** [MaartenBaert/ssr#812]
Hello Team, it would be useful to update the terminal codes and PPA, from the official website, [](https://www.maartenbaert.be/simplescreenrecorder/)

Although they can be used with some basic ingenuity and tricks like removing spaces and changing letters, for beginning users it can be confusing or discouraging, since the links to the PPA are outdated and the codes to install via Apt from terminal still refer to the ppa and earlier versions "simplecreen" instead from "simplescreen" at least for ubuntu (which is the most popular).

![image](https://user-images.githubusercontent.com/64709446/88960678-7c7a2480-d269-11ea-9180-1eb8f61d4711.png)

**Comment by MaartenBaert** [comment]
That's a translation bug, the actual webpage has the correct names and spaces.
