### ISSUE TITLE
Hotkeys with Super+<key> are received by the application being recorded

### ISSUE THREAD

**Issue by ranolfi** [MaartenBaert/ssr#814]
Hi, and thanks for the software.

I noticed that, for most combinations of <kbd>Super</kbd> + some key (i.e. <kbd>Super</kbd> + <kbd>b</kbd> or <kbd>Super</kbd> + <kbd>v</kbd>), the program I'm trying to record will receive the key press (b or v, respectively). For some reason during my testing the <kbd>p</kbd> key does not fallthrough.

Is there a way to fix this so that the tooltip text "The program that you are recording will not receive the key press" remains truthful?

Related: #686, maybe #752

**Comment by MaartenBaert** [comment]
Is it a fullscreen application?

The behavior depends on how the application implements keyboard handling. SSR grabs its own hotkey so it should not fall through to the application, but unfortunately some applications (especially fullscreen games) implement keyboard handling incorrectly and indiscriminately capture all keyboard input regardless of whether they have focus. In this case SSR will still detect the key presses but can't prevent the application from detecting them too.

Some games have a 'borderless fullscreen windowed' mode which usually avoids this problem. In many cases you can also start the application in windowed mode and then use window manager functionality to force the window to fullscreen, which achieves the same effect.

**Comment by ranolfi** [comment]
I observe this with 100% of my applications, from Terminal, to Firefox, to the file browser (Nemo)... Gedit, and everything else.

**Comment by MaartenBaert** [comment]
Which window manager are you using? Do you have anything enabled that might be blocking X11 keyboard grabbing?

**Comment by ranolfi** [comment]
I run Cinnamon 4.6.6 with LightDM. Best as I can tell, no application is interfering. Since this issue is specific to combinations with the 'Super' key, it might be that my DE handles it differently. Are you unable to reproduce on your side?

**Comment by MaartenBaert** [comment]
At least with Xfwm I can't reproduce this. If I set the hotkey to Super+B then the 'B' press event does not reach the application (but other keys do).

**Comment by ranolfi** [comment]
Sure. For Super+B:

```
FocusOut event, serial 38, synthetic NO, window 0x9600001,
    mode NotifyGrab, detail NotifyAncestor

FocusIn event, serial 38, synthetic NO, window 0x9600001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 38, synthetic NO, window 0x0,
    keys:  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   
           32  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyPress event, serial 38, synthetic NO, window 0x9600001,
    root 0x6b5, subw 0x0, time 3549863, (339,363), root:(891,836),
    state 0x50, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x9600001,
    root 0x6b5, subw 0x0, time 3549983, (339,363), root:(891,836),
    state 0x50, keycode 56 (keysym 0x62, b), same_screen YES,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 38, synthetic NO, window 0x9600001,
    root 0x6b5, subw 0x0, time 3550247, (339,363), root:(891,836),
    state 0x50, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Curious how the KeyPress event for Super_L is never registered! I tried many times.

**Comment by MaartenBaert** [comment]
That's really weird. Are you sure that your window manager isn't using the Super key for some special purpose? Especially the Super+P combination?

**Comment by ranolfi** [comment]
I just checked to be sure. Some combinations are in effect, like Super+R ("run" dialog), Super+L (lock screen), Super+D (show desktop) etc. And of course Super is used to open the menu. The combinations I've set up, however, are not used elsewhere.

**Comment by MaartenBaert** [comment]
Since the Super key is used for the menu, it might be interfering with the other hotkeys as well. I suspect that this is a window manager issue rather than a problem with SSR. Can you try changing the menu hotkey to something other than Super, or test with a different window manager?

**Comment by ranolfi** [comment]
Confirmed this is the reason.
