### ISSUE TITLE
No audio when starting from VS Code terminal

### ISSUE THREAD

**Issue by TheBicPen** [MaartenBaert/ssr#816]
When starting ssr from the terminal, no audio is recorded. I am on lubuntu 20.04 with pulseaudio, recording an opengl application. ssr works as expected when I start it from the launcher. I am using version 0.4.2

log file: https://paste.ubuntu.com/p/WMjgTq9yyx/ 

A similar issue occurs when I try to open it with python, except that it fails to start recording. The code is almost identical to the python example in issue #749. The error log for that is below:
```
[PulseAudioConnect] Error: Could not connect! Reason: Connection refused
It is possible that your system doesn't use PulseAudio. Try using the ALSA backend instead.
[PageRecord::StartInput] Error: Something went wrong during initialization.
```

**Comment by MaartenBaert** [comment]
Are you launching SSR from a terminal in a graphical session, or from a 'text terminal' (i.e. outside of X11)? If it's a regular X11 terminal I don't understand why it would be any different than launching SSR through some launcher.

**Comment by TheBicPen** [comment]
I've narrowed the problem down - the audio issue only appears when launching SSR from a VS Code terminal. The system terminal works fine. This is on a local VS Code session, not a remote one. I don't know what changes VS Code makes to the shell environment, but it looks like the problem is not with SSR.
