### ISSUE TITLE
Question: Why is the output sent to stderr?

### ISSUE THREAD

**Issue by gunar** [MaartenBaert/ssr#817]
Hi Maarten,

I was wondering why SSR uses stderr as stdout:
```
simplescreenrecorder >output  # output.txt is empty
simplescreenrecorder 3>output # output.txt contains messages
```

I'm writing some automation for SSR and it confused me for a little while.

PS: SSR is amazing, thank you so much.

**Comment by MaartenBaert** [comment]
The output contains a combination of log messages from SSR and various messages from internal libraries, it is meant purely for debugging, I didn't expect anyone to parse the output so stderr seemed the most reasonable. In theory this would allow me to configure SSR to output raw video data to stdout just like the ffmpeg command-line tool.

**Comment by gunar** [comment]
Got you, thanks for the clarification. My use case for it is that I'm using
SSR programmatically. As you know it's better than ffmpeg. So when I send a
"save" command through stdin, I need to parse stderr to wait until SSR
wraps up saving the file.

Now you've got me curious. You didn't expect anyone parsing stderr yet
you've given us an API though stdin. How come? Do you know of other people
doing different things with the stdin interface?

Anyway, thank you so much for SSR. Makes my life much easier. Thank you.

**Comment by MaartenBaert** [comment]
Most people just use it to automatically start and stop without actually checking whether it worked. If you want I can add some commands to return easier to parse output through stdout, would that be useful? What kind of feedback from SSR do you need?

**Comment by gunar** [comment]
Thank you for the offer! I think I'm good for now. I'm currently listening
stderr for

```js
  if (string.includes("StopPage] Stopped page.")) {
```

which is working well.

**Comment by gunar** [comment]
Thank you for the offer! I think I'm good for now. I'm currently listening `stderr` for

```js
  if (string.includes("StopPage] Stopped page.")) {
```

which is working well.
