### ISSUE TITLE
SimpleScreenRecorder 0.4.2 does not record on Linux Mint xfce 20

### ISSUE THREAD

**Issue by jonau01** [MaartenBaert/ssr#824]
Hi,
I just installed SimpleScreenRecrder 0.4.2 on linux mint 20 xfce.
I initiated a "Record a fixed rectangle" using codec H.264.  I hit the "Start recording"  button.   No error was found in log window.

The Preview screen does show what I wanted to record.  But the "Total time",  File size and Bit rate all stay at zero.
And obviously when I click on Save Recording,  the output file size is only 262 bytes and there is no recording at all. 

How can I debug this issue ?

Thanks

**Comment by jonau01** [comment]
Here is a log file and a screen shot of SimpleScreenRecorder when I attempted to record.

[log-2020-09-03_13.47.13.txt](https://github.com/MaartenBaert/ssr/files/5170401/log-2020-09-03_13.47.13.txt)

![SimpleScreenRecorder_2020-09-03_13-53-41](https://user-images.githubusercontent.com/65045445/92151280-df258980-edee-11ea-9f14-54072965b673.png)

**Comment by MaartenBaert** [comment]
Does it work if you disable audio?

**Comment by jonau01** [comment]
It does work when audio is disable.    
And I now realized that the problem was related with audio setting of the virtual desktop.
I modified audio setting of that virtual desktop and it works fine
Thank you very much
