### ISSUE TITLE
[Feature Request] Optional overlay indicating when recording, paused, not?

### ISSUE THREAD

**Issue by dairefagan** [MaartenBaert/ssr#827]
Due mainly to issues I have experienced with other software freezing, and even with SSR's sound notifications enabled, often I switch back to it when recording to make certain I am still recording my lectures.

Could you please consider implementing an option for some kind of overlay to indicate recording is active, perhaps active, paused, stopped etc?

**Comment by MaartenBaert** [comment]
There's already a system tray icon that will indicate when something goes wrong during recording. Any kind of overlay is going to end up in your video, is that really what you want?

The ideal solution is to use a second monitor, but if you don't have one there isn't really a way to display something to the user without having it end up in the recording - except for sound notifications.

You could use the `--statsfile` option to make SSR write its status to a file, and use an extra script to warn you if it isn't getting updated anymore if you're worried that SSR might freeze.

**Comment by dairefagan** [comment]
> There's already a system tray icon that will indicate when something goes wrong during recording. Any kind of overlay is going to end up in your video, is that really what you want?

I usually fullscreen for the Zoom lectures, with the two smaller windows on top of the speaker and chat. I have seen videos on YouTube where there is a blender animation, and I guess this is what you are talking about. I would prefer not to have that, I had thought perhaps it would be possible without actually putting it in the recording.

> The ideal solution is to use a second monitor, but if you don't have one there isn't really a way to display something to the user without having it end up in the recording - except for sound notifications.

Thanks, good to know for when using multiple monitors possibly in future. 

Closing ticket.
