### ISSUE TITLE
Clarification request: Impact of FPS on filesize

### ISSUE THREAD

**Issue by bdutta** [MaartenBaert/ssr#829]
Was under the impression (perhaps incorrect) that reducing FPS of the screenrecording would result in smaller filesize. I am using 'superfast' encoder, on a rather old PC (Athlon X2 with 3GB RAM) and a small 120GB SSD, so space & compute power are at a premium. I already reduce capture window to bareminimum necessary (but do not enable scaling as I see that it pushes up the CPU consumption a bit). For audio I use aac @ 64kbps bitrate (providing fairly acceptable speech audio). I know that I can reencode offline with a slow but more space-efficient encoder.

Just to push the storage efficiency (at source file level), I tried dropping FPS to 4fps and also 10fps. The recordings were of exact same video source (a terminal window running ffmpeg reencoding vorbis audio stream to aac audio stream), and same duration i.e. 60 seconds. Surprisingly the recording done at 10fps resulted in a slightly smaller file. I repeated this experiment two more times, and again same result.

Would it be possible to clarify the impact of FPS on filesize, encoding efficiency (the smoothness of video aspect is understood) so others like me don't try this false optimization ?

**Comment by MaartenBaert** [comment]
It depends on the encoder. Typically a higher FPS will result in a significantly higher bit rate as well, however if your video contains a lot of static content (like a terminal window) it may not make a big difference. I'm not sure why the high-frame-rate version would be smaller, it could just be a side-effect of how the keyframes align with the changes on screen.

If you try the same with something like video game footage or a movie, you will probably find that the bit rate is roughly proportional to the FPS, unless there is very little movement.

**Comment by bdutta** [comment]
Quite satisfied with the answer and explanation. Would be nice if SSR documentation on site could be updated with this information.
