### ISSUE TITLE
Recorded microphone audio has a lot of static

### ISSUE THREAD

**Issue by dchen327** [MaartenBaert/ssr#830]
My microphone is fine, but for some reason when I record in ssr I always get a lot of static noises. I've tried toggling ALSA and PulseAudio, and the settings for these, but I still get this static. I'm on Pop! OS 20.04.

**Comment by antony2025** [comment]
Same issue for me on Pop! OS 20.04.

**Comment by MaartenBaert** [comment]
What kind of noise is it? Can you upload a recording that has the problem?

Does the microphone work correctly in other programs like Audacity?

**Comment by dchen327** [comment]
It's a very constant static (kinda sounds like TV static). I haven't test Audacity, but the mic works fine in discord/zoom/Google meet, and I don't think there's any issue with the mic.

**Comment by MaartenBaert** [comment]
Those programs do noise filtering, SSR does not, so it's not the best comparison. Try Audacity or some other audio recorder that doesn't modify the sound, even the `arecord` command-line tool should be fine, e.g.:
```
arecord -D hw:0 -r 48000 -c 2 -f S16_LE recording.wav
```

**Comment by dchen327** [comment]
I just tested with arecord and it indeed has some static.

**Comment by dchen327** [comment]
https://sndup.net/45dt

I've attached an audio clip here.

**Comment by MaartenBaert** [comment]
If `arecord` has the problem and you are using the `hw:` PCM directly, then it's probably a driver or hardware issue, not an application issue. You may be able to improve things by changing settings is `alsamixer` if they happen to be misconfigured.

If that doesn't improve things, you can always do noise removal after recording. FFmpeg has a filter called `arnndn` which does noise removal based on neural networks. AFAIK this is the best open-source noise filter available. You can get pre-trained models here:
https://github.com/GregorR/rnnoise-models
There are some demos here if you want to see what it can do:
https://jmvalin.ca/demo/rnnoise/

**Comment by MaartenBaert** [comment]
The file you updated is really not very noisy, it's just extremely quiet. Try changing your settings in `alsamixer` to make the volume more reasonable (you can use the volume indicator in SSR, it should be in the yellow to orange range).

**Comment by antony2025** [comment]
> If `arecord` has the problem and you are using the `hw:` PCM directly, then it's probably a driver or hardware issue, not an application issue. You may be able to improve things by changing settings is `alsamixer` if they happen to be misconfigured.
> 
> If that doesn't improve things, you can always do noise removal after recording. FFmpeg has a filter called `arnndn` which does noise removal based on neural networks. AFAIK this is the best open-source noise filter available. You can get pre-trained models here:
> https://github.com/GregorR/rnnoise-models
> There are some demos here if you want to see what it can do:
> https://jmvalin.ca/demo/rnnoise/

@MaartenBaert thank you for the tips.
I had the same static even in Audacity.
Therefore, it could be a driver or hardware issue as  you mentioned.
I removed the static by using the Audacity noise reduction.
So perhaps this issue can be closed.
