### ISSUE TITLE
Screen flickers constantly and background is visible while recording Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by SanchayanDutta** [MaartenBaert/ssr#833]
Hi. I'm using SimpleScreenRecorder on Ubuntu 18.04.5 LTS. I recorded this video today morning: https://www.youtube.com/watch?v=mp9FJXHGWUQ&list=PL_qCnUr8ZYSBOC9hFSlmBZbq7ByPBXsOB&index=2. If you notice, the screen "breaks" and there is constant fluctuation while recording. How to fix this?

**Comment by MaartenBaert** [comment]
This happens with certain combinations of window managers and graphics drivers. It is not an SSR bug, but a bug in the window system itself. See:
https://www.maartenbaert.be/simplescreenrecorder/troubleshooting/#the-recording-occasionally-flickers-showing-parts-of-the-desktop-background-instead-of-windows

**Comment by SanchayanDutta** [comment]
This does seem to be a problem with the windows manager. After switching back to Unity from Ubuntu, the flickering issue is not so severe anymore but still persists. I'll try to install a different windows manager later. Thanks for the help!

**Comment by akash-258** [comment]
I had this issue in manjaro cinnamon 20.x & found a solution : Refer this video for solution https://www.youtube.com/watch?v=v7OJWts_e-4

Create/Modify this file : /etc/X11/xorg.conf.d/20-intel.conf

Section "Device"
Identifier "Intel Graphics"
Driver "intel"
Option "TearFree" "true"
Option "AccelMethod" "uxa"
EndSection

Video mentions this part is important : Option "AccelMethod" "uxa"
