### ISSUE TITLE
Can't record h.264: [PageRecord::StartOutput] Error: Something went wrong during initialization.

### ISSUE THREAD

**Issue by tifDev** [MaartenBaert/ssr#839]
Hello,

I can record **.mkv** but when I try to record **h.264** I receive this error: **[PageRecord::StartOutput] Error: Something went wrong during initialization.**

I have an nvidia, and these are the settings that I'm using:
![image](https://user-images.githubusercontent.com/39730484/98787796-dd340400-23f7-11eb-886d-e300813d57bc.png)

**Why is this error happening? How can I fix it?**

Thanks and congratulations for this great software.

**Comment by MaartenBaert** [comment]
![image](https://user-images.githubusercontent.com/829608/98837794-ad125280-2443-11eb-96ee-fa0bec35f155.png)
It says 'not supported by container'. Either set the audio codec to MP3 or AAC, or set the container to MKV.

**Comment by tifDev** [comment]
Hi,

I restarted my computer and now it works fine.

Thanks

**Comment by tifDev** [comment]
Just a question, when I first initialized this tool I received a warning that I had an option turned on from NVIDIA and it could cause glitching. I turned this off, but I don't remember the name in case I want to turn this feature back on. Could you please help?

Thanks

**Comment by MaartenBaert** [comment]
It's this one:
![image](https://user-images.githubusercontent.com/829608/98997568-f9898b00-2534-11eb-9987-894e75b6e5b0.png)

**Comment by tifDev** [comment]
Thank you !
