### ISSUE TITLE
OpenGL (ssr-glinject) has stopped working with Google Chrome later than v84

### ISSUE THREAD

**Issue by JazzMusicFan** [MaartenBaert/ssr#843]
Recent versions of the linux Google Chrome web browser no longer load the GLinject library properly.  It used to work reliably for years, by using several cmdline flags and skipping the wrapper shell script.  I am running on Arch linux, and have updated to several of the >v84 versions of Chrome as well as the latest version of simplescreenrecorder.  This functionality is very important in my work, and I am willing to be contacted for more details to get help on a fix.  If a workaround or fix is already know, then please explain it so that Chrome be made operational again with SSR.  Thank you very much for an excellent tool!!  ~Steve

**Comment by MaartenBaert** [comment]
Chrome is a difficult case because it splits itself up into multiple processes and does some kind of sandboxing for security reasons. I have never tried to capture it myself. Which command-line flags are you using? I would like to try to reproduce it.

**Comment by JazzMusicFan** [comment]
Yes, you are correct about the sandboxing and slave processes that are tightly interconnected (such as one just for GPU I/O) - however I solved that and it has worked for over 3 years (until just now).  The cmdline looks like this:
`$ ssr-glinject /opt/google/chrome/chrome --no-sandbox --test-type  {URL}`

I often add a few more flags (w.r.t. accel / GPU) but this is the minimum cmdline to demonstrate.  FYI, it also works using wrapper script '/opt/google/chrome/google-chrome'.  This has been reliable for me up through chrome v84 - it fails in v86, v87, v88 (beta).

The console output looks like this:
```
ssr-glinject: LD_PRELOAD = :libssr-glinject.so
ssr-glinject: command = /opt/google/chrome-beta/chrome --no-sandbox --test-type https://www.netflix.com/
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library loaded (64-bit).
[5230:5230:1212/093255.753093:ERROR:nacl_fork_delegate_linux.cc(329)] Bad NaCl helper startup ack (0 bytes)
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library unloaded.
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library loaded (64-bit).
[SSR-GLInject] Library unloaded.
```
Notice specifically the new error: **Bad NaCl helper startup ack (0 bytes)** - this should point to what has changed.  Thanks!

**Comment by MaartenBaert** [comment]
I did my testing with Chromium rather than Google Chrome, but it seems to have the same issue. I was able to fix it by adding the `--use-gl=desktop` option (to stop Chomium from using GLES, which SSR doesn't currently support). However it seems that chromium creates multiple OpenGL windows at the same time, and SSR will by default try to record the last one created, which appears to be the wrong one. You can tell which one is the correct one based on the frame size:
```
[SSR-GLInject] [/dev/shm/ssr-channel-maarten/video-1179954708590-984754-glx0006-chromium] frame size = 1920x1030.
```
I was able to make it work by manually deleting all streams except the correct one (glx0006 in this case). Perhaps I should improve the detection logic in SSR so it ignores streams that don't have a frame size set, that would filter out a lot of bogus OpenGL streams.

**Comment by MaartenBaert** [comment]
I've just pushed a change that delays stream creation until the first frame is captured, this seems to successfully get rid of the bogus streams that Chromium is creating and leaves only the one 'real' stream. Can you give it a try?

**Comment by JazzMusicFan** [comment]
Thank you, Maarten!!  This was a fast (and simple) solution - I was not aware that Chromium / Chrome would default to GLES on Arch Linux, but this usually works for me.  
I have indeed had a bit of instability with the GLINJECT lib not attaching correctly, I thought it was a timing issue/bug in SSR.  I suspect that using the new version you pushed will resolve that as well, which would be awesome.
I will test it out this week and let you know the result of repeated regression tests using the new code.  Again, many thanks.

**Comment by JazzMusicFan** [comment]
Hi Maarten - So far, I have not had any failure using your new code commit where the OpenGL stream fails, so let's call this a success and I will now close this issue.  Again. many thanks!
