### ISSUE TITLE
Duplicated expression in FastScaler_Scale_Fallback.cpp

### ISSUE THREAD

**Issue by qarmin** [MaartenBaert/ssr#844]
https://github.com/MaartenBaert/ssr/blob/6518c47a443eb5d1657b74f5d8f39ffdf359fdc4/src/AV/FastScaler_Scale_Fallback.cpp#L156

https://github.com/MaartenBaert/ssr/blob/6518c47a443eb5d1657b74f5d8f39ffdf359fdc4/src/AV/FastScaler_Scale_SSSE3.cpp#L241

out_h maybe should be used instead out_w

**Comment by MaartenBaert** [comment]
Good catch! I'm really surprised that you are reading those files, it is probably the most incomprehensible part of the SSR source code.
