### ISSUE TITLE
Feature request: log info about files

### ISSUE THREAD

**Issue by andreymal** [MaartenBaert/ssr#852]
Yesterday I made some videos using ssr 0.4.3. Today I wanted to watch them but they are disappeared. To find out what happened (did I delete them myself or cancel recording by mistake, or maybe I selected wrong directory?), I tried to read ~/.ssr/logs, but to my surprise I did not find absolutely nothing about the files. The logs contain info about encoder/muxer starting/stopping etc. but don't mention any files created or deleted.

So I create this feature request. It would be good to see paths and names of files being created and the recording completion/cancellation events  in the logs.

**Comment by MaartenBaert** [comment]
Good idea, I've added this.
