### ISSUE TITLE
Black region in the screen

### ISSUE THREAD

**Issue by domenicozambella** [MaartenBaert/ssr#854]
Everything works perfectly but for 
a black line in the middle of the screen

In case thi is relevant:

    domenico@xps13:~$ echo $XDG_SESSION_TYPE
    x11

![p](https://user-images.githubusercontent.com/26542246/103987615-0faa7500-518d-11eb-88a9-f8e5d456112a.jpg)

**Comment by domenicozambella** [comment]
It does not solve my problem, but I may have found the culprit.

The black line appears when I rescale the display (I use with `xrandr --scale`).

**Comment by MaartenBaert** [comment]
I think there is something wrong with the resolution detection. Can you please post the output of:
```xrandr```
And:
```xdpyinfo -ext XINERAMA | tail```
And:
```env | grep QT```
as well as the list of screen resolutions and positions reported by SSR in the dropdown menu?

Can you also try launching SSR with:
```QT_SCALE_FACTOR=1 simplescreenrecorder```
and test whether this makes any difference?

**Comment by domenicozambella** [comment]
I tried for some time to reproduce the very same error.
I failed, instead I get a tiny vertical black line  (~ 1px width).

`QT_SCALE_FACTOR=1 simplescreenrecorder` does not help

![image](https://user-images.githubusercontent.com/26542246/104127602-53ef6e00-5363-11eb-9b3f-e4bd617f08e6.png)


Here the information you asked

     > env | grep QT
      QT_ACCESSIBILITY=1
      QT_SCREEN_SCALE_FACTORS=eDP-1=2;DP-1=2;DP-2=2;
      QT_AUTO_SCREEN_SCALE_FACTOR=0

Also

    > xdpyinfo -ext XINERAMA | tail
            class:    TrueColor
            depth:    32 planes
            available colormap entries:    256 per subfield
            red, green, blue masks:    0xff0000, 0xff00, 0xff
           significant bits in color specification:    8 bits

    XINERAMA version 1.1 opcode: 141
           head #0: 3840x2160 @ 0,2160
           head #1: 3840x2160 @ 0,4320
           head #2: 3840x2160 @ 1,0

Finally


     > xrandr
     Screen 0: minimum 320 x 200, current 3841 x 6480, maximum 16384 x 16384
     eDP-1 connected primary 3840x2160+0+2160 (normal left inverted right x axis y axis) 294mm x 165mm
        3840x2160     60.00*+  59.98    59.97    48.00  
        3200x1800     59.96    59.94  
        2880x1620     59.96    59.97  
        2560x1600     59.99    59.97  
        2560x1440     59.99    59.99    59.96    59.95  
        2048x1536     60.00  
        1920x1440     60.00  
        1856x1392     60.01  
        1792x1344     60.01  
        2048x1152     59.99    59.98    59.90    59.91  
        1920x1200     59.88    59.95  
        1920x1080     60.01    59.97    59.96    59.93  
        1600x1200     60.00  
        1680x1050     59.95    59.88  
        1600x1024     60.17  
        1400x1050     59.98  
        1600x900      59.99    59.94    59.95    59.82  
        1280x1024     60.02  
        1440x900      59.89  
        1400x900      59.96    59.88  
        1280x960      60.00  
        1440x810      60.00    59.97  
        1368x768      59.88    59.85  
        1360x768      59.80    59.96  
        1280x800      59.99    59.97    59.81    59.91  
        1152x864      60.00  
        1280x720      60.00    59.99    59.86    59.74  
        1024x768      60.04    60.00  
        960x720       60.00  
        928x696       60.05  
        896x672       60.01  
        1024x576      59.95    59.96    59.90    59.82  
        960x600       59.93    60.00  
        960x540       59.96    59.99    59.63    59.82  
        800x600       60.00    60.32    56.25  
        840x525       60.01    59.88  
        864x486       59.92    59.57  
        800x512       60.17  
        700x525       59.98  
        800x450       59.95    59.82  
        640x512       60.02  
        720x450       59.89  
        700x450       59.96    59.88  
        640x480       60.00    59.94  
        720x405       59.51    58.99  
        684x384       59.88    59.85  
        680x384       59.80    59.96  
        640x400       59.88    59.98  
        576x432       60.06  
        640x360       59.86    59.83    59.84    59.32  
        512x384       60.00  
        512x288       60.00    59.92  
        480x270       59.63    59.82  
        400x300       60.32    56.34  
        432x243       59.92    59.57  
        320x240       60.05  
        360x202       59.51    59.13  
        320x180       59.84    59.32  
     DP-1 connected 3840x2160+0+4320 (normal left inverted right x axis y axis) 344mm x 193mm
        1920x1080     60.04*+
        1680x1050     61.00  
        1280x1024     60.02  
        1440x900      59.90  
        1360x768      59.95  
        1280x720      60.00  
        1024x768      60.00  
        1152x648      60.01  
        800x600       60.32  
        640x480       59.94  
     DP-2 connected 3840x2160+1+0 (normal left inverted right x axis y axis) 597mm x 336mm
        3840x2160     60.00*+  50.00    59.94    30.00    25.00    24.00    29.97    23.98  
        2560x1440     59.95  
        1920x1080     60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98  
        1920x1080i    60.00    50.00    59.94  
        1680x1050     59.88  
        1280x1024     75.02    60.02  
        1440x900      59.90  
        1280x960      60.00  
        1280x800      59.91  
        1152x864      75.00  
        1280x720      60.00    50.00    59.94  
        1024x768      75.03    70.07    60.00  
        832x624       74.55  
        800x600       72.19    75.00    60.32    56.25  
        720x576       50.00  
        720x480       60.00    59.94  
        640x480       75.00    72.81    66.67    60.00    59.94

**Comment by MaartenBaert** [comment]
Based on this:
```
XINERAMA version 1.1 opcode: 141
       head #0: 3840x2160 @ 0,2160
       head #1: 3840x2160 @ 0,4320
       head #2: 3840x2160 @ 1,0
```
It seems that the topmost monitor is misaligned by one pixel horizontally compared to the other two. This may be confusing Qt because it gets rounded to 0 due to the scale factor of 2.

Also, based on the `xrandr` output and the environment variables it looks like you are using Qt-based display scaling, not `xrandr --scale`.

Still, that doesn't explain why there is a black line in the middle of the screen. Which version of SSR are you using? There was a bugfix related to this but it was a long time ago.

**Comment by domenicozambella** [comment]
I confirm that removing that one pixel misalignment eliminates the black line. 

Indeed, I am mixing Qt-based display scaling with `xrandr --scale`. This may be searching for problems.

So far using SSR 0.3.11.  Upgrading to version 0.4.3 solves *all* problems. 

A big thanks!
