### ISSUE TITLE
SSR doesn't capture contextual menus

### ISSUE THREAD

**Issue by abelardolg** [MaartenBaert/ssr#855]
Hi there,

When I click on any option to show its contextual menu, SSR doesn't capture it. Why?

Best regards.

**Comment by MaartenBaert** [comment]
Which application are you trying to capture? Are you using regular screen recording or OpenGL recording?

**Comment by abelardolg** [comment]
I was trying to capture IntelliJ Idea, an IDE to develop software. "Regular screen recording" since I didn't select the "Record OpenGL" option.

**Comment by abelardolg** [comment]
Please, delete this issue.
My fault. Sorry.
