### ISSUE TITLE
SSR Codec "Not Installed"

### ISSUE THREAD

**Issue by nggit** [MaartenBaert/ssr#877]
Hello. I need help. I compiled the latest SSR. It worked, but didn't detect the main codec. I am using ffmpeg 4.3.1. I see that `ffmpeg -codecs` shows h264 is supported (DEV.LS). I have no idea what is missing here. Thank you for your help.
![ssr-codec-not-installed](https://user-images.githubusercontent.com/12218311/112087403-7a7e2080-8bc0-11eb-8782-6938dc125e0c.png)

**Comment by MaartenBaert** [comment]
There is more than one H.264 encoder in FFmpeg. Does ffmpeg show libx264 among the list of encoders? That is the one SSR uses.

**Comment by nggit** [comment]
OK. It worked after rebuilding ffmpeg and ensure to `--enable-libx264`. Thank you.
