### ISSUE TITLE
Ubuntu 21.04

### ISSUE THREAD

**Issue by thwaller** [MaartenBaert/ssr#884]
I understand that there have been topics prior regarding Wayland and that the application itself prompts that X11 is wanted (needed). The purpose of this query is that Ubuntu 21.04 is Wayland by default. I do understand, although not in much detail, that screen recording and screen capture has some difficulties with Wayland apparently related to security issues requiring applications to do this in a different way.

Given this, is the stand remaining that users are asked to use X11 vs the default? I assume that if Wayland remains the default this time (last time was reverted back to X11), this will be a planned update? Unfortunately, we are left with basically no screen recording apps in 21.04, and personally, this has always been my go-to app for such things.

**Comment by darkRaspberry** [comment]
Wayland is not supported, see #431

**Comment by ReneganRonin** [comment]
https://github.com/foxcpp/ssr-wlroots maybe try this fork. It works for me.

**Comment by thwaller** [comment]
@ReneganRonin I will have a look at the fork. Thanks.

@darkRaspberry I know it is not supported, but I did not see that post. I guess this software is just obsolete then as it relates to many new releases, at least for now. That is what I was looking for, although not the answer I was hoping for. I use Fedora and Ubuntu, both are on Wayland now. Like it or not, that is what is used.

**Comment by MaartenBaert** [comment]
I am planning to add wayland support, probably through pipewire, but I haven't had the time to implement and test it properly.

**Comment by thwaller** [comment]
@MaartenBaert Oh, ok. This is good to know. I hope soon, I really do like this softtware.
