### ISSUE TITLE
Webcam stream is showed on desktop but not recorded

### ISSUE THREAD

**Issue by stevexyz** [MaartenBaert/ssr#895]
I tryed with Kamoso and mplayer command line but the behaviour is the same: the rest of the screen is recorded properly but the camera window (that is properly showing the moving picture) show in the recorded file just the initial image as it is frozen, while the audio (coming from the webcam itself) is recorded properly

**Comment by MaartenBaert** [comment]
Sometimes the video rendering method which is used by video players can interfere with recording. If this is the cause, then you can probably fix it by changing this setting. E.g. in VLC this setting can be found under `Video > Output modules > Video output module`. You can try setting this to e.g. 'OpenGL' and see whether that makes a difference.

**Comment by stevexyz** [comment]
Not sure if it was this or just this since I have also firejail and tryed to launch without it but worked!!
Thank you and compliments for your very nice program!!
