### ISSUE TITLE
feature request: CLI commands for starting/stopping recording

### ISSUE THREAD

**Issue by muffinmaster1024** [MaartenBaert/ssr#943]
Hello there!

Is it possible to start a recording through CLI?
It would be useful to pick an existing configuration per option.

I would like to use this to start and stop a recording at a specified time (or duration).

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
Hello, It seems to me that this option is available, at least if it is in GUI mode. under the name of Schedule mode
-you can schedule ssr to start and stop at one or more specific hours or days. either in local time or UTC.

for options in CLI, I recommend you read the details of the February 2020 Pull https://github.com/MaartenBaert/ssr/pull/749#issuecomment-592947059   [click on the "#749 comment to see"]
and https://www.linuxuprising.com/2020/05/simplescreenrecorder-updated-with.html
![image](https://user-images.githubusercontent.com/64709446/153783362-eb414f40-eaf9-4d0f-a549-d81f25f583da.png)

**Comment by jinboson** [comment]
> Hello, It seems to me that this option is available, at least if it is in GUI mode. under the name of Schedule mode -you can schedule ssr to start and stop at one or more specific hours or days. either in local time or UTC.
> 
> for options in CLI, I recommend you read the details of the February 2020 Pull [#749 (comment)](https://github.com/MaartenBaert/ssr/pull/749#issuecomment-592947059) [click on the "#749 comment to see"] and https://www.linuxuprising.com/2020/05/simplescreenrecorder-updated-with.html ![image](https://user-images.githubusercontent.com/64709446/153783362-eb414f40-eaf9-4d0f-a549-d81f25f583da.png)

Hi, what screenshot are you using? It looks great!

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
> 
> Hi, what screenshot are you using? It looks great!

I am using KDE spectacle for screenshoots, It comes by default with the KDE Plasma desktop, but you can install it on any distro using snap or Github. (and it seems to me that it is also available in apt at least in debian)
-If you keep Spectacle open when you press the capture button on the keyboard or in the program there is a button to make annotations and effects on the capture (you can copy the capture to the clipboard, save it when finished)

https://apps.kde.org/es/spectacle/
https://github.com/KDE/spectacle

![image](https://user-images.githubusercontent.com/64709446/154185799-7659efce-7bee-4199-8baa-bdda57ad6dfd.png)

**Comment by jinboson** [comment]
> 



> > Hi, what screenshot are you using? It looks great!
> 
> I am using KDE spectacle for screenshoots, It comes by default with the KDE Plasma desktop, but you can install it on any distro using snap or Github. (and it seems to me that it is also available in apt at least in debian) -If you keep Spectacle open when you press the capture button on the keyboard or in the program there is a button to make annotations and effects on the capture (you can copy the capture to the clipboard, save it when finished)
> 
> https://apps.kde.org/es/spectacle/ https://github.com/KDE/spectacle
> 
> ![image](https://user-images.githubusercontent.com/64709446/154185799-7659efce-7bee-4199-8baa-bdda57ad6dfd.png)

Nice, thank you very much!

**Comment by muffinmaster1024** [comment]
> Hello, It seems to me that this option is available, at least if it is in GUI mode. under the name of Schedule mode -you can schedule ssr to start and stop at one or more specific hours or days. either in local time or UTC.
> 
> for options in CLI, I recommend you read the details of the February 2020 Pull [#749 (comment)](https://github.com/MaartenBaert/ssr/pull/749#issuecomment-592947059) [click on the "#749 comment to see"] and https://www.linuxuprising.com/2020/05/simplescreenrecorder-updated-with.html ![image](https://user-images.githubusercontent.com/64709446/153783362-eb414f40-eaf9-4d0f-a549-d81f25f583da.png)

which version are you using and on what system?
i don't see this options

**Comment by muffinmaster1024** [comment]
ok. I hadn't installed ppa. now i have scheduled option
