### ISSUE TITLE
GLInject stopped working after glibc upgrade

### ISSUE THREAD

**Issue by ITA84** [MaartenBaert/ssr#947]
After a system update (Archlinux) that upgraded glibc from 2.33 to 2.35, the OpenGL recording function stopped working: the Launch Now button didn't launch the injected program like before, nothing happened and no error messages were produced. By using the ssr-glinject command to launch the same program instead, the following error message is produced

[SSR-GLInject] Error: Can't get dlsym address!

The problem is in glinject/Hook.cpp:56, where it tries to find the addresses of the dlsym and dlvsym symbols in libdl.so, but starting from glibc 2.34, those were moved to libc.so, therefore this doesn't work anymore.

I've tried changing libdl.so* to libc.so* and it seems to work for me, but of course it needs to work for older glibc versions as well, and I don't really know how to patch this in correctly; it would be nice if this got fixed here or if someone made a patch.

Thank you

**Comment by ITA84** [comment]
^ I did recompile, and it did work for me, but it'd be nice to have a proper patch (if not a fix in the main repo) out so that distros can include it in their packages. It's fine if nobody patches this anyway

**Comment by Creteil** [comment]
> I did recompile, and it did work for me

Just recompiling against new glibc or patched + recompiling against new glibc ?

**Comment by ITA84** [comment]
Patched + recompiled (I just replaced the libdl.so symbols lookup with a libc.so lookup)

**Comment by Creteil** [comment]
Maybe you can add a « diff  » file of your changes...

Like this, it was easy for another one to patch the source code and compile it for a distribution running glibc 2.35.

Maybe a commit came and definitively fix this problem, but in the meantime...

**Comment by MaartenBaert** [comment]
This ended up being far more work than I expected - just replacing libdl with libc didn't work for me, it just caused the whole program to crash very early in the loading phase, which also made debugging very hard. I ended up completely rewriting the hooking mechanism (it is now based on PLTHook  instead of ElfHacks). Can you give it another try?

**Comment by ITA84** [comment]
It works for me now. Thank you so much for your hard work!

**Comment by petterreinholdtsen** [comment]
Thank you for the great work, indeed.  I believe this is the issue also reported in https://bugs.debian.org/1040375, and was very happy to discover the fix in 83b8f9f5d9c9ab06152657e57f85b6f71954a6b9 .
