### ISSUE TITLE
Is SSR dead? :(

### ISSUE THREAD

**Issue by ofetios** [MaartenBaert/ssr#988]
I really hope its not but it's been 7 months since the last commit.

I'd really love if SSR would get wayland support. SSR is the only thing keeping x11 installed on my system

**Comment by zen0bit** [comment]
ssr and yad

**Comment by MasterCATZ** [comment]
broken on Ubuntu 24.04 , shame I really liked the program

**Comment by ofetios** [comment]
> broken on Ubuntu 24.04

As far as I know they switched to wayland which is why it won't work on ubuntu 24. The project is dead and most likely needs a complete rewrite to make it compatible with wayland
